#+TITLE:素女經
　
* 至理第一
黃帝問素女曰：“吾氣衰而不和，心內不樂，身常恐危，將如之何？”素女曰：“凡人之所以衰微者，皆傷於陰陽交接之道爾。夫女之勝男，猶水之滅火。知行之，如釜鼎能和五味，以成羹霍。能知陰陽之道，悉成五樂；不知之者，身命將夭，何得歡樂？可不慎哉！
 
素女曰：“有采女者，妙得道術。王使采女問：彭祖延年益壽之法，彭祖曰：“愛精養神，服食眾藥，可得長生。然不知交接之道，雖服藥無益也。男女相成，猶天地相生也。天地得交會之道，故無終竟之限。人失交接之道，故有夭折之漸，能避漸傷之事而得陰陽之術，則不死之道也。”
 
采女再拜曰：“願聞要教。”彭祖曰：“道甚易知，人不能信而行之耳。今君王禦萬機，治天下，必不能備為眾道也。幸多後宮，宜知交接之法，法之要者，在於多禦少女而莫數瀉精，使人身輕，百病消除也。”
 
素女曰：“禦敵，當視敵如瓦石，自視如金玉，若其精動，當疾去其鄉。禦女當如朽索禦奔馬，如臨深坑下有刃，恐墜其中。若能愛精，命亦不窮也。”
 
黃帝問素女曰：“今欲長不交接，為之奈何？”素女曰：“不可。天地有開闔，陰陽有施化。人法陰陽隨四時，今欲不交接，神氣不宣佈，陰陽閉隔，何以自補？練氣數行，去故納新，以自助也。玉莖不動，則辟死其舍，所以常行以當導引也。能動而不施者，所謂還精。還精補益，生道乃著。”
 
《素女經》云：黃帝曰：“夫陰陽交接節度，為之奈何？”素女曰：“交接之道，故有形狀，男致不衰，女除百病，心意娛樂，氣力強。然不知行者，漸以衰損。欲知其道，在於定氣、安心、和志。三氣皆至，神明統歸，不寒不熱，不饑不飽，寧身定體，性必舒遲，淺內徐動，出入欲希。女快意，男盛不衰，以此為節。”
 
《玄女經》云：黃帝問玄女曰：“吾受素女陰陽之術，自有法矣。願複命之，以悉其道。”玄女曰：“天地之間，動須陰陽，陽得陰而化，陰得陽而通。一陰一陽，相須而行。故男感堅強，女動辟張，二氣交精，流液相通。男有八節，女有九宮，用之失度，男發癱疽，女害月經，百病生長，壽命消亡。能知其道，樂而且強，壽即增延，色如華英。”
 
* 和志第四
 
《玉房秘訣》云：黃帝曰：“夫陰陽之道，交接奈何？”素女曰：“交接之道，固有行狀，男以致氣，女以除病，心意娛樂，氣力益壯。不知道者，則侵以衰。欲知其道，在安心、和志。精神統歸，不寒不暑，不飽不饑，定身正意，性必舒遲，深內徐動，出入欲希。以是為節，慎無敢違，女即歡喜，男則不衰。”
 
又云：黃帝曰：“今欲強交接，玉莖不起，面慚意羞，汗如珠子，心情貪欲，強助以手，何以強之，願聞其道。”素女曰：“帝之所問，眾人所有。凡欲接女，固有經紀，必先和氣，玉莖乃起。順其五常，存感九部，女有五色，審所足扣。采其溢精，取液於口，精氣還化，填滿髓髒。避七損之禁，行八益之道，毋逆五常，身乃可保。正氣內充，何疾不去？府藏安寧，光滑潤理，每接即起，氣力百倍，敵人賓服，何慚之有？”
 
《玄女經》云：黃帝曰：“交接之時，女或不悅，其質不動，其液不出。玉莖不強，小而不勢，何以爾也？”玄女曰：“陰陽者，相感而應耳。故陽不得陰則不喜，陰不得陽則不起，男欲接而女不樂，女欲接而男不欲，二心不和，精氣不感，加以卒上暴下，愛樂未施。男欲求女，女欲求男，情意合同，俱有悅心，故女質振感，男莖盛男熱，營扣俞鼠，精液流溢，玉莖施縱，乍緩乍急，玉戶開翕，或實作而不勞，強敵自佚，吸精引氣，灌溉朱室。今陳八事，其法備悉，伸縮俯仰，前卻屈折。帝審行之，慎莫違失。”
  
* 臨禦第五
 
《素女經》云：黃帝曰：“陰陽貴有法乎？”素女曰：“臨禦女時，先令婦人放平安身，屈兩腳，男人其間，銜其口，吮其舌，拊搏其玉莖，擊其門戶東西兩傍，如是食頃，徐徐內入。玉莖肥大者內半寸，弱小者入一寸，勿搖動之，徐出更入，除百病。勿令四傍洩出，玉莖入玉門，自然生熱且急，婦人身當自動搖，上與男相得，然後深之，男女百病消滅。淺刺琴弦，入三寸半，當閉口刺之，一二三四五六七八九，因深之，至昆石旁往來，口當婦人口而吸氣，行九九之道訖，乃如此。”
 
* 五常第六
 
《玉房秘訣》云：黃帝曰：“何謂五常？”素女曰：“玉莖實有五常之道，深居隱處，執節自守，內懷至德，施行無己。夫玉莖意欲施與者，仁也；中有空者，義也；端有節者，禮也；意欲即起，不欲即止者，信也；臨事低仰者，智也。是故真人因五常而節之，仁雖欲施予，精苦不固。義守其空者，明當禁，使無得多。實既禁之道矣，又當施予，故禮為之節矣。執誠持之，信既著矣，即當知交接之道。故能從五常，身乃壽也。”
  
* 五徵第七
 
《玉房秘訣》云：黃帝曰：“何以知女之快也？”素女曰：“有五徵五欲，又有十動，以觀其變，而知其故。夫五徵之候：一曰面赤，則徐徐合之；二曰乳堅鼻汗，則徐徐內之；三曰嗌乾咽唾，則徐徐搖之；四曰陰滑，則徐徐深之；五曰尻傳液，徐徐引之。”
  
* 五欲第八
 
素女曰：“五欲者，以知其應：一曰意欲得之，則屏息屏氣；二曰陰欲得之，則鼻口兩張；三曰精欲煩者，則振掉而抱男；四曰心欲滿者，則汗流濕衣裳；五曰其快欲之甚者，身直目眠。”
 
* 十動第九
 
素女曰：“十動之效：一曰兩手抱人者，欲體相薄陰相當也；二曰伸其兩臂者，切磨其上方也；三曰張腹者，欲其洩也；四曰尻動者，快善也；五曰舉兩腳拘人者，欲其深也；六曰交其兩股者，內癢滔滔也；七曰側搖者，欲深切左右也；八曰舉身者，迫人搖樂甚也；九曰身巾縱者，支體快也；十曰陰液滑者，精已洩也。見其效以知女之快也。”
 
* 四至第十
 
《玄女經》云：黃帝曰：“意貪交接而莖不起，可以強用不？”玄女曰：“不可矣。夫欲交接之道，男經四至，乃可致女九氣。”黃帝曰：“何謂四至？”玄女曰：“玉莖不怒，和氣不至；怒而不大，肌氣不至；大而不堅，骨氣不至；堅而不熱，神氣不至。故怒者，精之明；大者，精之關；堅者，精之戶；熱者，精之門。四氣至而節之以道，開機不妄，開精不洩矣。”
 
* 九氣第十一
 
《玄女經》云：黃帝曰：“善哉！女之九氣，何以知之？”玄女曰：“伺其九氣以知之。女人大息而咽唾者，肺氣來至；鳴而吮人者，心氣來至；抱而持人者，脾氣來至；陰門滑澤者，腎氣來至；勤殷咋人者，骨氣來至；足拘人者，筋氣來至；撫弄玉莖者，血氣來至；持弄男乳者，肉氣來至。久與交接，弄其實以感其意，九氣皆至。有不至者則容傷，故不至，可行其數以治之。”
 
* 九法第十二
 
《玄女經》云：黃帝曰：“所說九法，未聞其法，願為陳之，以開其意，藏之石室，行其法式。”玄女曰：“九法：
 
第一曰龍翻。令女正偃臥向上，男伏其上，股隱於床，女舉其陰，以受玉莖。刺其穀實，又攻其上，疏緩動搖，八淺二深，死往生返，勢壯且強，女則煩悅，其樂如倡，致自閉固，百病消亡。
 
第二曰虎步。令女俯伏，尻仰首伏，男跪其後，抱其腹，乃內玉莖，刺其中極，務令深密，進退相薄，行五八之數，其度自得，女陰閉張，精液外溢，畢而休息，百病不發，男益盛。
 
第三曰猿搏。令女偃臥，男擔其股，膝還過胸，尻背俱舉，乃內玉莖，刺其臭鼠，女煩搖動，精液如雨，男深案之，極壯且怒，女快乃止，百病自愈。
 
第四曰蟬附。令女伏臥，直伸其軀，男伏其後，深內玉莖，小舉其尻，以扣其赤珠，行六九之數，女煩精流，陰裏動急，外為開舒，女快乃止，七傷自除。
 
第五曰龜騰。令女正臥，屈其兩膝，男乃推之，其足至乳，深內玉莖，刺嬰女，深淺以度，令中其實，女則感悅，軀自搖舉，精液流溢，乃深極內，女快乃止，行之勿失，精力百倍。
 
第六曰鳳翔。令女正臥，自舉其腳，男跪其股間，兩手處席，深內玉莖，刺其昆石，堅熱內牽，令女動作，行三八之數，尻急相薄，女陰開舒，自吐精液，女快乃止，百病消滅。
 
第七曰兔吮毫。男正反臥，直伸腳，女跨其上，膝在外邊，女背頭向足，處席俯頭，乃內玉莖，刺其琴弦，女快，精液流出如泉，欣喜和樂，動其神形，女快乃止，百病不生。
 
第八曰魚接鱗。男正偃臥，女跨其上，兩股向前，安徐內之，微入便止，纏授勿深，如兒含乳，使女獨搖，務令持久，女快男退，治諸結聚。
 
第九曰鶴交頸。男正箕座，女跨其股，手抱男頸，內玉莖，刺麥齒，中其實，男抱女尻，助其搖舉，女自感快，精液流溢，女快乃止，七傷自愈。”
 
* 八益第十六
 
《玉房秘訣》云：素女曰：“陰陽有七損八益。
 
一益曰固精。令女側臥，張股男側，臥其中，行二九數，數畢止，令男固精，又治女子漏血，日再行，十五日愈。
 
二益曰安氣。令女正臥高枕，伸張兩股，男跪其股間刺之，行三九數，數畢止，令人氣和，又治女門寒，日三行，二十日愈。
 
三益曰利藏。令女側臥，屈其兩股，男橫臥，卻刺之，行四九數，數畢止，令人氣和，又治女門寒，日四行，二十日愈。
 
四益曰強骨。令女側臥，屈左膝，伸其右股，男伏刺之，行五九數，數畢止，令人關節調和，又治女閉血，日五行，十日愈。
 
五益曰調脈。令女側臥，屈其右希伸其左股，男處地刺之，行六九數，數畢止，令人脈通利，又治女門辟，日六行，二十日愈。
 
六益曰蓄血。男正偃臥，令女戴尻跪其上，極內之，令女行七九數，數畢止，令人力強，又治女子月經不利，日七行，十日愈。
 
七益曰益液。令女人正伏舉後，男上往，行八九數，數畢止，令人骨填。
 
八益曰道體。令女正臥，屈其股，足迫尻下，男以股脅刺之，以行九九數，數畢止，令人骨實，又治女陰臭，日九行，九日愈。”
 
* 七損第十七
 
《玉房秘訣》云：素女曰：
 
“一損謂絕氣。絕氣者，心意不欲而強用之，則汗洩氣少，令心熱目冥冥。治之法，令女正臥，男擔其兩股，深案之，令女自搖，女精出止，男勿得快，日九行，十日愈。
 
二損謂溢精。溢精者，心意貪愛，陰陽未合而用之，精中道溢，又醉飽而交接，喘息氣亂則傷肺，令人□②逆上氣，消渴喜怒，或悲慘慘，口幹身熱而難久立。治之法，令女人正臥，屈其兩膝俠男，男淺刺，內玉莖寸半，令女子自搖，女精出止，男勿得快，日九行，十日愈。
 
三損謂雜脈。雜脈者，陰不堅而強用之，中道強寫，精氣竭，及飽食訖，交接傷脾，令人食不化，陰痿無精。治之法，令女人正臥，以腳鉤男子尻，男則處席內之，令女自搖，女精出止，男勿快，日九行，十日愈。
 
四損謂氣洩。氣洩者，勞倦汗出，未幹而交接，令人腹熱唇焦。治之法，令男子正臥，女跨其上，向足，女據席，淺內玉莖，令女自搖，精出止，男子勿快，日九行，十日愈。
 
五損謂機關厥傷。機關厥傷者，適新大小便，身體未定而強用之，則傷肝，及卒暴交會，遲疾不理，不理勞疲筋骨，令人目茫茫，癰疽併發，眾脈槁絕，久生偏枯，陰痿不起。治之法，令男子正臥，女跨其股，踞前向，徐徐案內之，勿令女人自搖，女精出止，男勿快，日九行，十日愈。
 
六損謂百閉。百閉者，淫佚於女，自用不節，數交失度，竭其精氣，用力強寫，精盡不出，百病並生，消渴目冥冥。治之法，令男正臥，女跨其上，前伏據席，令女內玉莖相搖，精出止，男勿快，日九行，十日愈。
 
七損謂血竭。血竭者，力作疾行，勞因汗出，因以交合，俱已之時，偃臥推深，沒本暴急，劇病因發，連施不止，血枯氣竭，令人皮虛膚急，莖痛囊濕，精變為血。治之法，令女正臥，高抗其尻，申張兩股，男跪其間深刺，令女自搖，精出止，男勿快，日九行，十日愈。
　
* 還精第十八
 
《玉房秘訣》云：黃帝曰：“願聞動而不施，其效如何？”素女曰：“一動不寫，則氣力強；再動不寫，耳目聰明；三動不寫，病消亡；四動不寫，神威安；五動不寫，血脈充長；六動不寫，腰背豎強；七動不寫，尻股益力；八動不寫，身體生光；九動不寫，壽命未央；十動不寫，通於神明。”
  
* 施瀉第十九
 
《玉房秘訣》云：黃帝問素女曰：“道要不欲失精，宜愛液者也，即欲求子，何可得寫？”素女曰：“人有強弱，年有老壯，各隨其氣力，不欲強快，強快即有損。故男年十五，盛者可一日再施，瘦者可一日一施；年廿，盛者日再施，嬴者可一日一施；年卅，盛者可一日一施，劣者二日一施；冊，盛者三日一施，虛者四日一施；五十，盛者可五日一施，虛者可十日一施；六十，盛者十一日一施，虛者二十日一施；七十，盛者可卅日一施，虛者不寫。”
　
* 治傷第廿十
 
《玉房秘訣》云：采女曰：“男之盛衰，何以為候？”彭祖曰：“陽盛得氣則玉莖當熱，陽精濃而凝也。其衰有五：一曰精洩而出，則氣傷也；二曰精清而少，此肉傷也；三曰精變而臭，此筋傷也；四曰精出不射，此骨傷也；五曰陰衰不起，此身傷也。凡此眾傷皆由不徐交接而卒暴施寫之所致也。治之法，但禦而不施，不過百日，氣力必致百倍。”
  
* 求子第廿一
 
《玉房秘訣》云：素女曰：“求子法自有常體，清心遠慮，安定其衿袍，垂虛齋戒，以婦人月經後三日，夜半之後，雞鳴之前嬉戲，令女盛動，乃往從之。適其道理，同其快樂，卻身施寫，下精欲得，去玉門半寸，不可過子宮，《千翼》，勿過遠，至麥齒。遠則過子門，不入子戶。若依道術，有子賢良而老壽也。”
 
又云：素女曰：“夫人合陰陽，當避禁忌，常乘生氣，無不老壽。若夫婦俱老，雖生化有子，皆不壽也。”
  
* 好女第廿二
 
《大清經》云：黃帝曰：“入相女人，云何謂其事？”素女曰：“入相女人，天性婉順，氣聲濡行，絲發黑，弱肌細骨，不長不短，不大不小，鑿孔居高，陰上無毛，多精液者；年五五以上，三十以還，未在產者。交接之時，精液流漾，身體動搖，不能自定，汗流四逋，隨人舉止。男子者，雖不行法，得此人由不為損。”
 
房中禁忌：日月晦朔、上下弦望、六丁六丙日、破日、月廿八、日月蝕、大風 甚雨、地動、雷電霹靂、大寒大暑、春秋冬夏節變之日，送迎五日之中，不行陰陽。本命行年禁之重都者：夏至後丙子丁醜，冬至後庚申辛酉，及新沐頭、新遠行、疲倦、大喜怒，皆不可合陰陽。至丈夫衰忌之年，皆不可妄施精。
 
素女論曰：“五月十六日，天地牝牡日，不可行房。犯之，不出三年必死。何以知之？但取新布一尺，此夕懸東牆上，明日視之，必有血色，切忌之。”
　
采女曰：“何以有鬼交之病？”彭祖曰：“由於陰陽不交，情欲深重，即鬼魅假像，與之交通。與之交通之道，其有勝於人，久處則迷惑，諱而隱之，不肯告人 ，自以為佳，故至獨死而莫知之也。若得此病，治之法：但令女與男交，而男勿瀉精，晝夜勿息，困者不過七日必愈。若身體疲勞，不能獨禦者，但深按勿動，亦善也。不治之，煞人不過數年也。欲驗其事實，以春秋之際，入于深山大澤間，無所云為，但遠望極思，唯含交會陰陽，三日三夜後，則身體翕然寒熱，心煩目眩，男見女子，女見男子，但行交接之事，美勝於人，然必病人而難治，怨曠之氣，為邪所淩。後世必當有此者，若處女貴人，苦不當交。與男交以治之者，當以石硫黃數兩，燒以熏婦人陰下身體，並服鹿角末方寸匕，即愈矣。當見鬼涕泣而去。一方服 鹿角方寸匕，日三，以瘥為度。”
 
采女曰：“交接之事既聞之矣，敢問服食藥物，何者亦得而有效？”彭祖曰：“使人丁強不老，房室不勞損氣力，顏色不衰者，莫過麋角也。其法：取麋角，刮之為末十兩，輒用八角、生附子一枚，合之服方寸匕，日三，大良。亦可熬麋角令微黃，單服之，亦令人不老。然遲緩不及用附子者，服之廿日，大覺。亦可用隴西頭伏苓分等捧篩，服方寸匕，日三，令人長生，房內不衰。”
  
黃帝問素女對曰：“女人年廿八、九，若廿三、四，陰氣盛，欲得男子，不能 自禁，食飲無味，百脈動體，候精脈實，汁出汙衣裳。女人陰中有蟲，如馬尾，長三分，赤頭者悶，黑頭者沫。治之方：用面作玉莖，長短大小隨意，以醬及二辨綿裹之，內陰中，蟲即著來出，出複內，如得大夫，其蟲多者卅，少者廿。”
 
* 素女經詳解
** 陰陽與五行
 
黃帝問素女說吾氣衰而不和心內不樂身常恐危將如之何
 
素女曰凡人之所以衰微者皆傷於陰陽交接之道爾夫女之勝男猶水之勝火知 行之如釜鼎能和五味以成羹勝能知陰陽之道悉成五樂不知之者身 命將夭何得歡樂可不慎哉
 
黃帝問素女：「我氣力衰竭，脈理不和，終日憂心仲仲，總覺得危險將至，大限難逃，是怎麽回事？」 素女答：「這種現象是因為陰陽失調，性生活不當所產生的後果。女子精力強勝過男子時，就像火把火燒熄一樣，使男人招架不住。男女性生活，正像是烹調食物，必須水和火互相配合，才能煮出佳餚，作出熱烘烘的食物。能夠體認水火交融的道理，便能盡嗜人間樂趣。否則，敗身喪命，那裏還有樂趣可言？性生活能不慎重嗎？」
 
黃帝就是歷史上的三皇五帝之一。三皇實指伏羲、神農和黃帝。載，伏羲氏發明八卦，窮研陰陽之道，創天地、日月和男女之說，並訂定婚姻大禮。
 
其房中術有云：「天向左轉，地向右轉，男人必如天般向左轉，女子則向右轉，男人向下衝突，女子往上迎合。」這是指出夫婦性交時的基本體位。黃帝是在黃河流域一帶，幾個大部落的領袖，根據史載，時在紀元前二五五0年左 右。黃帝賢能聰慧，發現指南針原理和太陽運行系統。並觀察地上留下的飛禽走獸爪痕 及蹄跡，分辨其異同，而發明造字原理，啟文明記事之肇端。 更重要的是，黃帝和歧伯等六位名醫，完成了醫學重典黃帝內經一書。歧伯受尊為「天師」，是黃帝的醫藥顧問。 黃帝由於出人後宮，禦女多而不得法，年僅五十歲左右，便覺得虛虧，於是先後詢問歧伯和素女。 據黃帝內經，上古天真論篇載：「余（黃帝）問上古之人，春秋皆度百歲，而動作不衰。今時之人，年半百而動作皆衰……」，歧伯答說，以前的人之所以長壽，乃是因為他們懂得陰陽之道，性生活合理所致。
 
老子曰：「萬物負陰而抱陽，沖氣以為和。」 天地陰陽四時，有一定順序，是萬物的始終死生根本道理，違逆這種大自然法則，必然災害叢生。比如春生夏長秋收冬藏的時序，若在秋冬播種，自然要枯死泥中，不能生長 素女對黃帝這個問題的解答是根據陰陽五行之說，認為水性太強自然便滅掉了火性 ，這就是男人體力衰竭的緣故。因為天地間有木、土、水、火和金五個要素，循循不息 的存在著，組成天地萬物萬體。五行又相克，即水能克土、土克水、水克火、火克金、 金又克木，迴圈相生。 因此水性（女子）大強則易傷及火（男性）。而性交時不能調配彼此高潮時間，也會造成不良後果。一般男人在射精後便因困倦而呼呼睡去，此時若女子未能完成高潮， 會造成病態後果，導致夫妻性生活不協調。 美國金賽博士的實驗指出，男人在射精後，隨即由極度快感曲線上，垂直降至無性感感覺狀態。新婚的女子往往會懷疑，在性行為前，男人多方的「花言巧語」，在達到 「逞欲」目的後，便置之不理，甚而逃避性行為，乃至呼呼大睡，實在是卑劣之極。這都是新娘不明男人生理的關係。
 
金賽博士發現，女子的膣道（陰道），會接受男人性器官摩擦愈能感覺快樂興奮， 以致於欲罷不能。這正符合了素女所說，男人是火性，若經大水一潑，便因射精而熄滅 。女子是水性，愈受火勢焚煮，則鼎中水便愈沸騰、洶湧。 素女忠告黃帝，早洩等於是不瞭解正常的性生活，他之所以不能充分享受性愛樂趣 甚而衰竭瀕死的緣故，皆在於不瞭解水火之性，陰陽不調之故。
 
** 攝捕與強精
 
素女曰有采女者妙道到術王使采女問彭祖延年益壽之法彭祖曰愛 精養神服食眾藥可得長生然不知交接之道雖服藥無益也男女相成 猶天地相生也天地得交會之道故無終竟之限人失交絕之道故有夭 折之浙能避漸傷之事而得陰陽之術則不死之道也
 
素女說：「有一位叫采女的女子，對於陰陽之道，頗有心得。」
 
黃帝便令采女去請教彭祖，詢問延年益壽的方法。
 
彭祖答：「愛惜精力，修養精神，服用各種補藥，便能長生不老。然而，要是不懂男女交合之道，服食再多的補藥，也毫無益處。男女交合成一體，正像天地相互相成， 由於天地相輔配合適應，才能永遠生存，無止無境。人們若因不能認識交合之道，便會傷身敗體、以致早夭而不能長壽。假若能不傷身敗體，盡曉陰陽之道，男女交合之術，便能長生不死；安享天年。」
 
黃帝由於日理萬機，事多繁冗，生活中又多酒色，難免不有多少神經衰弱症。常常覺得自己有病，醫藥顧問對他的治療，第一步便是增加他的信心，因此，黃帝接受素女的推薦，命采女去請教彭祖仙師。 采女是一位才色兼備的女子，她極能領會房中術的奧義，且聰慧絕倫，聞一知十，十分美豔。 彭祖是位精通養生術的老哲人，由於攝養得法，又常服食強精補藥，因此雖已年至耄耋，仍然顯得青春而有活力。 據「列仙全傳」記載：采女曾奉西周穆王（時在紀元前九七六年前後）的命令去拜訪彭祖仙師，請教房中術的秘訣，回來後便傳授給穆王，穆王初試後，果見奇效。東晉時，有本「拾遺記」，對於這件事也有略升的記載。描寫西方王母，在那位五十歲才繼承王位的穆王東巡之際，下凡而來，在人間與穆王共用云雨春宵之樂。 在兩情繾綣之際，王母把插人陰道中的乾棗取出，勸穆王即時服下，以作養生強精的補品。
 
這種棗子的功用，經醫學證明，確是有效。因為棗子本身即具很高的藥效。棗子常常被引用在醫治內臟的衰弱。對於防止老化、利尿等症狀確具功效，在安定精神方面也極具效果。自漢以來，中藥有種叫「甘麥大棗湯」的鎮靜藥，便被用來醫治女子歇斯底里病。 中國古傳的強精壯體補藥很多，本書將有專篇介紹，此類補藥和一般催淫藥、春藥不同，後者的作用只使人透支體力，無異是飲鳩止渴，殊不足取。補藥雖然是補，但是若不愛惜身體，縱淫無度，不懂交合之道，不諳陰陽互補之理，那麽，既使服用再多的 補藥，也無濟於事。 彭祖早見於此，因此他認為男女問正確的性交之道，即在於大自然天地一體的攝理之中，人們必明乎此，才不致於喪身敗體，水保福樂康寧。
 
** 多禦與少洩
 
采女再拜曰願聞要教彭祖曰道甚易知人不能信而行之耳今君王禦萬幾治天下必不能備為眾道也幸多後宮宜知交接之法法之要者在於多禦少女而莫教瀉精使人身輕百病消除也采女接著又請彭祖更深入教導。
 
彭祖回答：「此中道理說起來簡單易懂，只是一般人欠缺倍心，或不能腳踏實地的去奉行罷了。現今黃帝日理萬機，處理天下大事，身疲 力倦，心情繁重，自然不能去深入瞭解各種養生道理。好在黃帝擁有眾多妃妾，只要能把握交合要領，便能善自攝養了。這個要領，便是要多與年輕女子交合，並且屢交不洩 ，減少射精次數，便能身體輕快，百病不生。」
 
彭祖很重視心理治療，他認為黃帝終日勞於理政，身心兩倦，容易養老而遲滯，最害青春，因此說要黃帝在後宮嬪妃中，儘量選擇年輕女子為交合物件，而且要保持觸而不洩，儘量減少洩精次數。如此便能常保身輕體快，心情愉悅。
 
「舊約聖經」中的「列王紀」篇裏，也提及少女曾使年老力衰的彼德大帝生氣蓬勃起來。由此可見，東西方的房中術秘訣終究是不謀而合，趨於一致的。 黃帝和彼德大帝都選擇年輕女子作交合物件，以達到返老還童，常保青春的秘法， 主要還是心理影響占著重要的因素。 近代性心理學家，如受理士，都主張夫妻雙方皆需要保持青春活力，彼此影響，以提高魚水情趣。並指出，男人固然天生的富有主動侵略的性向， 容易向外發展，尋找刺激，接觸妻子以外的女性。而女子同樣也有類似程度深淺的傾向，希望接觸丈夫以外的男性。只是這種衝動容易被外在各種道德規範的壓力所壓制而打消。因此，心理學家都勸夫妻要儘量保持心情愉快、青春朝氣，尤其是有問題的家庭， 醫生總要勸太太在家時，別衣衫不整，仍要打扮打扮，以博取丈夫的歡心。又勸作丈夫的，雖然在整日辦公勞倦之下，仍應打起精神，與妻子共同培養家庭和睦情趣。 夫妻性生活的原則也如上述。在結婚初期，雙方均會樂此不疲，然而時久日曠，彼此往往都會感到枯燥無味。試想物件完全相同，為什麽會產生不耐之感—？恐怕這便是日久生厭的心理在作祟。現代夫妻不可能屢換性交物件，丈夫更不可能像彭祖所說的．經常與其他年輕女子交合。若要在夫妻性關係上，符合本章所述的原則，就賴於夫妻互相合作，保持青春活力，相互偷悅。 關於彭祖說的另外一項秘訣——避免射精一項，就是所謂的「觸而不洩」．這在以後各篇中會有詳盡介紹。 總而言之，彭祖的主張，著眼點即在於精神愉快、身心輕鬆，常保青春活力。這是完全符合現代醫學觀念的。尤其現代人，生活緊張而又多彩多姿的生活環境中，總會感 到某種程度的精神不安、心理威脅，自然更容易因情緒不穩而滋生疾患。因此，素女的這篇記載，讀者更不可等閒視之。
  
** 九淺與一深
 
素女曰禦敵家當視敵如瓦石自視如金玉若其精動當疾去其鄉禦女當如朽索禦奔馬如臨深坑下有刃恐墮其中若能愛精命亦不窮也
 
素女對黃帝說：「與女交媾，要把對方看成瓦石，珍視自己如同金玉。發現女子有了快感，身體不禁地擺動時，便應速將陽具抽出女子陰外。」
 
「若想禦服女子，則在交合時須特別謹慎小心。就像用腐朽的韁繩在駕馭奔騰的怒馬一般；又像是行臨在佈滿利刃的深淵一樣，唯恐一失足跌落下去而粉身碎骨。 戰戰兢兢，如能設法不要射精，可以保持生命力於無窮。！
 
根據醫學測驗結果顯示，男子比較容易勃起，達到高潮，而高潮之後，又突然成垂直線的降入無性感期。而女子則不同，女子需要較長時間的前戲，以使性欲提高，以素女有見於此，便提醒黃帝，在交合時應有心理準備，視對方為瓦石，不要太激動 ，要珍惜自己精氣以免洩精太早，而對方還不能達到高潮，以致影響性交情趣。 類似這種男子提早射精的問題，可說是既古老而又新鮮的問題。現代人應該仍然謹 守素女經提示的原則，男女的高潮儘量相互配合。同時男人不可有只顧洩欲的心理，而 忽略女子的反應。 猶太人做愛的習慣，是必須要獲得妻子的完全同意，然後再進行。丈夫只顧自己性欲的滿足，而不能給予妻子相當的快樂，即被視為：「婚後的強姦」，這種事情，在猶太人的倫理社會觀裏，被列為嚴厲之禁，因為他們是很重視：「性為人權」這句話的。 中國古代，一些聰明人，利用針灸的原理，作為培養交合前的性感前戲動作。針灸原理，是根據十四經絡脈穴路線，刺激反應而達到預期效果。若循此系統，愛撫女子， 很能使女子春情勃發，提升性感，完成達到高潮目的。
 
古人房中術的愛撫技巧，是從手指尖到肩膀，足趾尖到大腿，彼此輕緩地愛撫。腳，是先從大拇趾及第二趾開始，而後逐漸向上遊移，因為腿部的神經末梢是由上而下分佈的。 手，則由中指開始，而及食指與無名指，三指交互摩擦。先磨擦手背，而後進人由掌心向上遊移，用四指在手臂內側專心愛撫，漸上肩膀。 在手腳的愛撫動作完畢後，男人的左手就緊抱女子的背梁，右手再向女子重要的感帶愛撫，同時進行接吻。接吻也是依順序漸進的，要先吻頸，再吻額。男人也用嘴吮吻對方的喉頭、頸部和乳頭，並用齒輕咬耳朵等女子的敏感帶。 經過上述的程式，充分愛撫女子身體的各主要部位後，再慢慢進行「九淺一深」或「八淺二深」的交合方式，對方就得到十分快感，顯現出非常滿足的樣子。 雖然西醫根據解剖生理學原理，獲悉性交前必須花相當的時間來愛撫女子性感帶可是遠不如中醫針灸原理，由機能生理學的方式來得有效。因為按前述方式專心一意。 愛撫女子經絡，則對方的感應是非常敏銳快速而自然的。
 
俗云：「九淺一探，右三左三，擺若鰻行，進若蛭步。」這十六字足以描繪男人在交合時應有的技巧。其最主要的目的，還是在教男人自行理智控制，儘量使女子快樂。 達到高潮，而自己能避免過早洩精。 陽具先淺進九次，使女子青春蕩漾，心猿意馬，然後再作很深入的一掣，是謂“九淺一深”。因為在九次淺進時，女子能感受溫柔的撫擦的快感，然後又受到狠命的一插 ，心動氣顫，男人龜頭直抵陰戶深處，女子即刻會陷入極度的興奮狀態，陰道發生反覆膨脹及不斷緊縮的現象。愈是如此，則對陽具的介入，更能體會出交合快感。 除了九淺一深外，陽具還需左沖右突，摩擦女子陰戶右邊三次，再左邊三次，此際 ，女子又複感受到不同的快感，來自陰道兩壁，性欲便更是高漲，不能自已。 此外，男人陽具在進出陰道時，不可呆板地一抽一送，必須像鰻魚遊進，橫向擺動身體，以使女子陰道兩壁都能感受到陽具的衝突。或是在進出陰道時，採用像蛭蟲走路 一般，一上一下地縱著身體拱進。如此女子的陰道上下壁也能明確地感受到陽具插擦快感，終而神魂顛倒，樂不可支而達到高潮。
 
中國隋唐時，有一本性古籍－－「玉房秘訣」，其中載有「八淺二深，死往生還、 右往左往」。九淺一深也好，八淺二深也好，都是殊途同歸，指的是性交的韻律。同時限制深人的次數，除非很特殊的例子，女子才需要每次的插人，都要直抵陰道最深處，因為每次都深人，這種強烈的快感，極易導至性感的麻痹不覺，反而弄巧成拙。正像在背上搔抓止癢！若是過於用力而次數又太多，很容易便造成疼痛的後果。
 
「死往生還」，指的是男子陽具在陰戶內因受內壁的蠕動緊縮和溫度的刺激，很容就會不自主地洩精，因此在發現陽具感動而堅硬時，應立即抽出陰道，待它稍軟後， 再行插入，也就是所謂的死往生還，也就弱入強出的意思。 「右往左往」，是指陽具必須在陰道兩壁，交互磨擦。 玉房秘訣、素女經，以及所有的性古籍的原則，都主張男人應儘量理智，延後射精 ，以配合女子高潮的到來。這種原則，直到今日，仍然是書學界所一致主張的。 男人若能按上法經常鍛煉，必能增強交合的持續力，則不但夫妻魚水永歡，丈夫更能常保精壯，而百戰百勝。
 
** 養生與練氣
 
黃帝問素女說今欲長不交接為之奈何素女曰不可天地有開闔陰陽有施化人法陰陽隨四時今欲不交接神氣不宣佈陰陽閉隔何以自補 練氣數行去故納新以自助也玉莖不動則辟死其合所以常行以當導 引也能動而不施者所謂還精還精補益生道乃著
 
黃帝和素女說：「我想暫時隔一段時間再行交接，如何？」
 
素女說：「不可如此 。天地的陰陽兩氣有開閉的現象，如春夏秋冬和畫夜明暗等，都因時序變化而有不同。 人應依據這種陰陽原理，隨著四季變化而行動。若要停止交合，精氣不宜洩，陰陽之道即行隔絕。如此，怎能按正常的循序攝捕身體？要反覆地作練氣行功法，吐出廢氣，吸 人新鮮空氣，增進身體康健。」 “陽具若不常交合，就會像整蛇一樣，因為不能動彈而僵死在巢穴裏，所以應再練習導引法，使精氣能通體圓滑地流暢著。交合時，再用還精法，使精液不致無謂地浪費 ，把精氣蓄存在體內，便能精神飽滿而生氣勃勃了。」 由素女經中，我們便能發現，古代的春生術，是多種方法的匯合，並非褊執一種。 尤其是房中術，必須配合其他的養生方法，多方面同時並進，方能收到預期的效果。 素女指出，熟練導引法和練氣法後，新陳代謝自然通暢無阻，再加上還精法，使精氣儲存在體內，身體便會健康而有活力，延年益壽更是意料中事。 中國很早就有許多養生長壽的方法，聰明的人，研究各種長壽動物的生活方式、飲食習慣以及性交方法，最後結晶而成各種不同的「養生術」，諸如導引、練氣、胎息、 辟穀、食餌、房中術……等等。
 
素女經就是房中術之一，由於它的效驗，一直是帝王和貴族階級珍藏的秘岌。而它的功效，則是使人快樂和長壽。 導引法，可說是一種柔軟體操。「莊子」一書中即有類似記載。華陀（紀元一四五 至二八0）是中國古代的名醫，在當時他就能藉麻醉法，進行剖腹和挖眼球等的外科手術。他對導引法有深刻的認識，他說古傳的導引法，不外如學熊雙臂吊樹以鍛煉四肢， 學貓頭鷹環轉頭頸搖轉頭部以活絡頸頭等。因此華陀自己又創「五禽術」，由觀察五種 飛禽的運動方法，來鍛煉自己；以使身輕體健，精神爽快，到九十九歲，仍然耳目不衰 ，齒牙不壞。 綜而觀之，導引法就是利用屈伸、俯仰、行臥、侍立、蹲躅、徐步、吟唱和呼吸等 動作的一種健康體操。 和華陀同時代有位叫冷壽光的人，因為常作搖擺環轉頭頸運動和深呼吸，又深諳容成公（神仙名）的房中術，竟活到一百六十餘歲，頭髮雖然斑白，可是氣色望之仍似三 、四十歲人。容成公的房中秘訣，就是采陰補陽。 後漢書，方術傳中記載，上黨郡（山西省）有位年近百歲的王真，臉色紅潤而光澤 ，望之如五十未滿，他的長壽秘訣，即在多行胎息法和胎食法。 所謂胎食法，就是不吃穀物，只吞飲舌下的唾液，若能領悟個中技術，既使看見再 大，也照樣能行房事。 中國古代養生術，主張在作息運動之餘，也同時要滿足飲食與男女的兩大本能，只 有適當地解除食、色二欲的壓力後，才能繼續生存。在生活各方面都能保持平衡，便能強健而長壽。
 
以現代醫學觀點看，導引法即體操，能使筋骨活絡，肌膚強健，身體發育健全。煉氣法就是呼吸健康法，可使體內氧分充足，新陳代謝正常，情緒穩定。加之，對基本欲 給予適當的渲洩，生活井然有序，自然便能防止衰老，延年而益壽。 例如，導引法中要人先停立一段時間，再頭向下作倒立。這便是非常符合現代醫學 念的方法，因為人體血液在倒立時，都向頭部方向迥流，使上半身得到充分的血液供 ，不但能防止脫髮、慢性頭痛症，並能刺激腦下垂體，促使性欲旺盛。 又如練氣法，教人「吐故納新」，放出體內廢氣．吸入新鮮的空氣！這也是頗符合 代醫學要求的。普通人的呼吸，都不能充分吸人空氣，練氣法就是針對這個缺點加以 善。 與王真同鄉的郝孟節，嘴裏經常含枚大棗，坐定時，氣息停止，身體不動，不飲不 食，歷經百日，形如死人。他的妻子性格樸實，目睹丈夫的情景，無動於衷，毫不驚恐 曹操知道郝孟節功行深厚，便拜他為眾方士的總監督。 印度相傳（濫觴於六千年前）的瑜伽術，也有類似這種的人工冬眠。把呼吸時間拉長，脈搏緩慢，體溫和血壓下降。每日消耗極微少的體力，攝食少量的清水和氧氣來維 持生命。如此反覆鍛煉，可以身埋一個月不死。 古人用腹壓式呼吸和食餌法配合，防止衰老，治療高血壓和便秘。又用氣功療法 治癒神經衰弱、胃腸病和結核病等，非常有效。這也是靜坐呼吸法的一種。 中國太極拳，是由華陀的五禽法演進而來，而五禽法又淵源於胎息法和導引法。 簡易太極拳中有二十四個動作，由中國和東南亞一帶，流布廣傳至世界各角落。這種拳法從開始到結束的動作雖有變化，卻無段落之分，都是連續動作，而且都是描畫圓 形的各種曲線。 八段錦也是一樣，練習的要領，是要統一精神、集中意志。雖然全身運動，但呼吸 並不急促，而保持有節奏的自然呼吸，並增加呼吸深度，每天履行不息。
 
這種柔軟體操，對於防治疾病，如高血壓、精神緊張、胃潰瘍、心臟病以及許多慢 性病和現代病基具功效。此外，對於神經系統、循環系統、呼吸系統、消化系統和新陳 代謝等方面均具效果。
 
「太極拳經」的記載，要鍛煉者作丹田深呼吸。丹田就是針灸術中焦點的稱呼。它的位置有三處，在頭上（大腦），一在橫膈膜，一在臍下。此外指的是臍下，根據道家研究，這是全身最重要的位責。在深呼吸時，可使「氣」凝聚於此，保持心平氣和，安定，達到延年益壽目的。美國醫學家已經證實，打太極拳、八段錦，可使人心境安定，情緒平穩。 「丹田呼吸」是鍛煉觸而不洩的不二法門。調息養氣的目的在增加持續力，做愛時持續力差的人，應該多練習丹田呼吸法。 關於丹田呼吸法的內容，古人所言備載。莊子一書就有「真人呼吸深入腳，凡人呼吸淺在喉」。要言之，即是訓練到儘量吸入新鮮空氣，以祛除身體的疲困。馬拉松長跑 選手，就採用此法以補充長時間體內所消耗的大量氧氣。 東晉葛洪（二八一至三四一年）指出「胎息法」。乃是使呼吸方式，作到像在母胎 內一樣。由鼻孔吸氣，默數到一百二十後，再慢慢地吐氣，並且保持吐出的氣要少於吸 入的，這樣才能使精氣儲存在體內。勤練者往往可以由一數到一千再行吐氣。到了這種境界後，即能返老還童，永保青春。
 
胎息法以減少吐氣，和多積新鮮氧氣在體內的方法，是非常合於現代醫學觀念的。 若將這種原理應用在房中術時，就是如何控制洩精的問題。我國古有「采陰補陽」 和「采陽補陰」之說，容我們稍作瞭解。 「采陰補陽」即是吸入女性精氣，蓄於男子體內，或稱「還精法」，這是長壽秘法之一。「采陽補陰」，則是使男子洩精後，加以儲吸於女子體內，成為女子的「還精法」與長壽法。 清代小說「肉蒲團」裏，提到名妓顧仙娘，如何吸取男人精液的秘訣，也是頗為特殊的性交秘技。 男子精液決不可作無謂的浪費，每洩出一次，就要有一次的效益。女子高潮時，就把男人的龜頭密接在陰道口，不要讓他擺動，把女子陰道口的小孔緊緊貼合，儘量吸男人精液人體內，進人女子體內的精液，由尾閭（脊椎終點）游往上方，直抵小腹丹田， 這種效能，不是人參、附子所能比擬。這便是女子的「采陽補陰法」。 男子精液由尾閭到丹田的現象，這雖是傳說的仙道行法，但在經驗上說，這種方法 也是可能的。因為瑜伽行者對此道苦修而成功者確有其人。
 
中國古傳的“小周天”修練法，便是在靜坐中，陽氣由丹田（臍下三寸）、會陰（ 陰部與肛門之間）而尾閭、夾椎（脊椎骨中部）、玉枕（後頭下方）、泥九（大腦）、 膻中（兩乳之間）等順序的全部過程，這種修為功力，通常需要二、三年時間才行。 男人若能修煉好小周天的功夫，則在交合時，把陽具和女子陰蒂密切貼合，進行小周天的過程，可使女子在極度興奮中失散力氣，而永遠不願離開他。 素女指出男人在鍛練這種技巧時，必須練氣法和導引法雙管齊下，才能達到還精法 的目的。 「玉房秘訣」中也記載著，男人如勤加練習腹式呼吸，以增加體力及持續力，在交合抽送擺動時，深吸一口氣凝集在小腹丹田處，默數到三十下，再換氣。如此有助於陽 具的堅挺和持久。陽具堅硬要洩精之前，應立刻忍住，毅然由陰道中抽出，等到稍軟時 ，再繼續進行，如此反覆地硬出軟入，死往生還，勤練不停，不到十天陽具就會堅如鐵棒，熱似火把，百戰百勝，所向無敵。 女子在這方面，應該做些什麽鍛鏈呢？漢朝有位柳腰美人越飛燕，從小就練「行 氣之術」，以快速的舞步鍛煉腰身，束緊腰帶，用呼吸鍛煉強健的閉氣止息力。由於這 種長期的練習，使得陰部收縮力很強，足使陽具感到極樂的高潮。在此之際，吸收男人 。這種功用和煉氣法（胎氣法），同屬於靜態訓練。（拙譯「瑜伽愛情術」介紹人十種 型式、章章附有圖示及本人示範圖片，頗有參考價值。） 前述的趙飛燕，就是把內力聚凝在拇趾，而後隨著音樂快慢節奏起舞，以練氣養力 民國十五年，北京大學社會學教授張競生，著有一本「性史」，要算是最早的性經驗報告書，其中詳述甚明。 據香妹的經驗云：「房中術真難練，先運氣而後收縮陰部，練習此種技巧，非一年 半載則難以成功。此功一旦煉成，陰戶便能收縮自如，且樂此不疲。進行交合時有一定 的順序，即當陽具插進來時，陰戶要鬆開，待插入後便將陰戶縮緊，使陽具有突然被緊緊吸住的感覺。每當陽具一抽一送之際，女子陰戶一放一吸，會使男人快活無比，樂趣無窮。」 類似性愛瑜伽的運動方式，在日常生活中，便能輕易地作到，比如在搭乘巴士時， 可以一邊抓著扶手吊帶，一面緊縮肛門的括的肌，使它一松一緊，加以鍛煉。
 
辟穀，簡言之，就是要少吃食物以達到淨化腸胃的強健法。「服食」也是如此，以 藉服如枸杞等藥物來強身。華陀即經常以服食法來養生，他常吃「漆葉育麥散」，以去 三蟲，健五臟，使身輕體快，祛除疾病。這種服食法，流傳廣遠，是國人皆知的去除寄 生蟲的健康法。 漆葉青麥散的配方，是以一鬥漆葉和十四兩青麥（黃芝）所調成，華陀指出若長期 服用，可驅蟲除穢並促進內臟功能，身輕體健，不生白髮等功效。青麥則多產於陝西、 安徽、江蘇和河南一帶。 長期服用，是中醫的特徵之一。張仲景所提煉的「金匱腎氣丸」，經過清乾隆皇帝 的改良後，成為中醫的十大名藥之一，即為專治腎臟的「保腎丸」。 中醫重視腎臟系統，舉凡精力減退、體力衰弱、性能力弱等皆稱為「腎虛」。長期 服用保腎丸可以加強腎功能、增進持續力。 許多人只能吹熄一公尺半遠的燭火，若長期服會保腎丸後，便能一口氣吹熄三公尺外的蠟燭。
 
** 氣氛與情趣
 
素女經云黃帝曰夫陰陽交接節度為之奈何素女口交接之道故有形狀男致不衰女除百病心意娛樂氣力強然不知行者漸以衰損欲知其道在於定氣安心和志三氣皆至神明統歸不寒不熱不俄不飽享身定 體性必舒遲淺內徐動出入欲希女快意男盛不衰以此為節 前章，素女表示停止交接有違陰陽之道，
 
黃帝便又問道：「那麽男女交合的節度準則是怎樣的呢？」 素女說：「男女交合是天生本能的，但總以不使得男人日漸衰弱，女子能除百病， 彼此身心愉快，身強氣盛為原則。若不瞭解陰陽之道，身體便會日漸衰弱。其實交合的要領在於情緒安定、心境轉松、精神飽滿。若此三氣充盈，精氣神集中，則自然能不畏寒暑，不過飽不中餓。身體狀況良佳，情緒也舒綬悠然。在交合時，仍守淺進、緩動的 要領。想要使女子快感，而又保男人精力不衰，便應謹守上述的原則。」 素女告訴黃帝的交合之道，要領是在乎時注意身心調養，作好鍛鏈和準備。一旦身 臨戰地，便應情緒穩定、心境輕鬆、精神飽滿，然後才能身心兩健，無往而不利。 猶太性古籍－－ 達姆德也有類似而有趣的戒條：「如果夫婦真誠相愛，即使窄如劍刃的床鋪。也能睡得舒適偷快，否則，夫婦感情不睦，睡在再大的床鋪，也不會安適坦然。」
 
這也是指的男女必須心平氣和，兩相愉悅而全無戾氣，夫婦之道，即在其中調節性感度，有朝於大肥性中框的反應、外界剌激和性交技巧的運用，此三者 是基本支柱，缺一不可。 這三項雖說是連鎖反應，可是後二者，卻需要男人主動地培養烘托。
 
心理學家發現 ，性交的氣氛，對女性而言，是很重要的一環。 根據金賽博士的報告，男人僅憑想像，就能造成陽具勃起或導引性興奮。而女子的性感則是比較現實的，必須藉重於視覺、聽覺或觸覺，才能引起性欲。因此，交合時的氣氛，便須特別留意。 女子的性欲也容易受外界不良的刺激而中斷。金賽博士指出，女子比較喜歡不開燈作愛，而男人則相反。男人喜歡看到彼此交合的姿態和女子的全身反應。女子在通室明亮或光天化日下，比較不容易達到高潮。此外，女子也不喜歡中途停止性交，比如正在云雨之際，接聽電話，男人仍可以重新來過，女子欲火則較難再旺，這便是女子比較重視氣氛的明證。
 
性心理權威文理士尊士的結論，也顯示出此種交合氣氛是很重要的。 由於求愛現象與生物現象極有關聯，在動物和未開化的人類之間，性生活是有季節性和週期性的，尤其是牝的一方。大部分的動物並非常年的有性交行為。許多高等動物也都有蕃育季節，一年一度或兩度，即在春季、秋季，或春秋兩季。許多未開化的民族也有這種習性，地球上有許多棲居分散得很遠．而很不相干的民族，在春季、秋季，或 春秋兩季，都有盛大的狂歡節日，讓青年男女有性交與結婚的機會。 在文明國度裏，婦女得胎成孕的頻數，也有它的近期性，大抵是一年中的曲線，在 春季或秋季要高出很多，便是這種原始節日的風流餘韻了。 有時候夫婦兩人，對性交的興趣並不能一致，此時便需要所謂「氣氛的培養」了。 女子固然有生理週期（月經），根據醫學界指出，在月經前後是性欲最烈時期。而男人在納爾遜（julius nelson）的觀察下，也證明出有二十八天的性來複或性迴圈。此外， 柏瑞考斯特（perry coste）和羅默爾（von roemer），也有相同的男人性週期報告。 後者甚至進一步發現，男人每月性來複有兩個頂點，大的頂點在月圓之後，小的則在新月時期。這種說法，又和原始民族的經驗相合，他們的狂歡集會也都是和月圓月缺有密 切關連。 女子性欲熾烈期有的學者主張是在月經之後的幾天內，如德國神經科學家克拉夫脫 埃平（von krafft ebing）、考想曼（kos smann）、瞿嶽（guyot），也有主張是在 經前、經後和行經中的，如奧特雷（otto adler）和卡貝爾（harry campbell）。 晚近幾年，有位女醫師大衛絲（katharine davis），在觀察過二千個女子的性生活後，發現她們性欲最熾烈的時候，幾乎都是在月經前兩天到月經後七天之內。尤其是經前強於經後。 關於上述男女的性欲高漲時間既然不同，則在性交時氣氛的培養更屬必要。 前面提到的性交時，女子不喜歡光亮，這或多或少也是女子羞怯心理之一，在動物 界亦然。最初，羞怯總是牝動物的拒絕表示，因為叫春期（oestrue）尚未到來。等到 叫春期到時，這種羞怯心還在，但和性衝動的力量結合後，就成為若即若離，半迎半拒 的敵媚態度與行為。時至此際，牝的對牡的便是而接近，時而逃避，雖是逃避，而走的 路線卻是個圓圈。女子在交合時態度也複如此。一種原始的害羞心理與逃避總是不時浮現腦際，而主 動攻擊的男人，要想捕捉這頭美麗的牝獸，並共用比翼之樂，便須編織誘人的陷阱，也 就是交合前氣氛的培養。 素女經主張，陰陽之道，在於男女和諧，培養氣氛，真是一針見血之論，如果不遵 行這個原理，則女子的性花自然開不出來，甚而會變成一棵不開傘的硬蕾！
 
** 四時與五臟
 
玄女經云黃帝問玄女曰吾受素女陰陽之術自有法矣願複命之以悉 其遺玄女說天地之間動須陰陽得陰而化陰得陽而通一陰一陽相 須而行故男感堅強女動避張二氣交精流液相通男有八節女有九宮用之失度男發癱疽女害月經百病生長壽命消亡能知其樂而且強壽即增延色如華英。
 
黃帝向宏女說：「關於陰陽之道，從索女處已瞭解了個梗概，希望你再跟我說得深入詳盡些。」 玄女說：「天地間一切事物，都根據陰陽交合衍生得來。陽得陰而化育、陰獲陽而 成長。陰陽相輔相成，互相感應，迴圈相生。 因此，男人陽具一接觸到女性，便會堅硬勃起;女子受性刺激後，陰道自會開啟，於是陰陽二氣相觸，精液交流，琴瑟和鳴。 在交合之際，男人應遵守八戒，女子有九律，若忽視這些戒律而濫行交接，男人身上便易併發癱疽膿腫，女子則會導致月經不順，百病叢生。最後則一命嗚呼，永訣人世 。反之若能瞭解並奉行陰陽之道，便能健康、快樂而長壽。」 雖然沒有明指男人八節，是那八戒？女人九宮是那九律？但是我們可以在以後的其他各篇中，具窺全貌。 玄女與素女都是房中術的權威，後世人常把房中術稱為「玄素之道」。並傳有「玄女經」一書，這是一本假玄女之名而問世的性學醫書，略晚於素女經。 玄女經中也提及性生活必須要順應自然的韻律，要有適當的節度。同時也提出警告 ，謂若無節制，則會百病叢生，甚而招致生命夭折之危險。反之，若能領悟陰陽之道， 實行適度有節的性生活，則不但可以享床第之樂，並兼能有強身長壽之益。
 
中國古哲，將天下萬物皆分為陰陽二種元素。以為太極生陰陽，陰陽成萬物。陰陽 相調；而萬物存焉。日本石原明醫博士的疾病觀，也是根據陰陽二相而來。他說：「人體也不脫陰陽二元的支配，男屬陽而女屬陰，則早已受到天生性別的支配。身體各部位也是如此，背部為陽、腹部為陰；皮膚為陽，皮膚以下為陰；內臟中的五臟（多是實質 性的臟器官，如心、肝、脾、肺和腎）屬陰，六腑（膽、胃、小腸、大腸、膀胱、三焦 ）則屬陽。彼此的功用互相制衡，也互相調和。故而順陰陽之理，即能康健。否則陰陽 失調，失去平衡，情況嚴重時，便會罹患疾病。」
  
黃帝內經門第二卷，記載中指出，天有四時和五行——「天生收藏」和「寒暑燥濕 風」。也就是春生、夏長、秋收、冬藏；專用水故寒、夏屬人故暑、秋屬金故燥、春屬木故風、長夏屬土故濕。大自然中有四時五行，春夏秋冬和水火金木土，以運天時以衍 萬物。人則有五臟，化五氣。五臟是肝、心、脾、肺、腎，五氣是喜怒悲憂恐。 喜怒傷氣，寒暑傷形。人若喜怒不節制，寒暑又過度則必然生機不固，容易生病。 中醫所謂「五勞七傷」，即是喜傷心、怒傷肝、悲傷肺、憂思傷脾、驚恐傷腎。為 了要保護五臟，則在情緒上應該力求平穩。情緒不穩定的人，喜怒無常，自然會影響到 內臟功能，進而危及健康。心情緊張或興奮過度的人常有樂極生悲的不幸結果，因心臟 會受影響，而心的功能在掌理血脈，則此人看起來，必定憔悴而無精打采；天性悲觀的 人，肺臟受影響，肺臟司呼吸和膚發，則此人外表一定是皮膚粗糙，毛髮脫落而無光澤吸呼，器官也必然多病。許多氣喘病患，縱有多少雄心壯志，也會被氣喘的苦痛消磨殆 盡；擔驚受怕，生活緊張的人，腎臟受影響，腎主司骨髓、體液和排洩，則此人常會感 到疲累，精力不繼，排洩不正常，如便秘之類，最為顯著。新兵入營，在起初一星期內 ，由於精神緊張，大多數會便秘，直到生活適應後，才能恢復正常。 五臟不健康不但會顯現在人的外貌，同時也會出現在睡眠時的夢中。 黃帝內經素問第二十四篇說，肺氣虛的人，常會夢見金屬兵刃物和斬人殺雞鴨之事 ，若是在秋天得夢（秋屬金），便會夢見兩兵交戰或與人鬥毆。 腎氣虛的人，常會夏見乘水船溺游泳之事，若在冬天得夢（冬屬水），便會夢見自己戰慄躲伏在水中或冰天雪地裏畏懼恐慌至甚。肝氣虛的人，常會夢見奇花異卉，香菇 菌草，若在春天得夢（春屬木），便會夢見匿伏在茂林密葉，深山叢莽中，心氣虛的人 ，常會夢見火燒紙焚或男人陽物之類，若在夏天得夢（夢屬火），便會夢見大火燒山， 救火救災之事。脾氣虛的人，常會夢見饑餓難當情形，若在二、五、八、十二月得夢， 便會夢見蓋房築屋，填土埋磚，以補腹空。 五臟屬陰，六腑屬陽，以上所述五臟氣虛，陽氣有餘而陰氣不足的現象。反而言之 ，讀者晚間夜夢參加奧林匹克游泳大賽，技冠群倫，獲頒冠軍金牌時，且莫沾沾白自喜， 應當留意腎臟患病，不妨細心回想，此前是否受到驚嚇，近來生活是否緊張，日常生活 是否隱藏什麽壓力難題或危機？再善用自己的智慧去解析疑慮，克服困難。 上述因夢斷病的記載，證諸近世的醫學或心理學理論，也是相同的。 心理學家佛洛伊德（s．freud），是精神分析大師，他對夢作過深入的研究，發現 人在現實社會裏的挫折，會在夢中宣洩。比如一個小職員，經常會見自己發了財，當大 公司的董事長，對手下職員指揮吆喝。膽小的人在夢中常變成戰鬥英雄。因此，脾虛的 人，常會夢見自己據案大嚼，或是填土埋坑，蓋屋造屋。原來都是心理學上的「補償作 用」。 醫學界公認人的身心是一致的，身體能影響心理，心理也能影響身體。所以身體生理上的缺憾，如脾虛，則人便會事無大小皆「大而化之」，不夠精確，雖然天性開朗， 笑口常開，卻失於玩忽。由於脾臟職司肌肉等組織，則易使人虛胖不實，內力饑餒。睡 眠時形之於夢；便會有大吃大喝的現象，甚而會成為偉大建築家，填壑滿谷，營宮建舍 ，巍巍然巨廈廣室，皆為所造。 古哲所云，天為陽地為陰，日為陽月為陰，畫為陽夜之陰。陰陽一體，猶物之兩面 。素女經說：「陽得陰而化，陰得陽而道，一陰一陽相須而行。」旨哉斯言！
 
** 良宵一刻值千金
 
黃帝曰夫陰陽之道交接奈何素女曰交接之道固有形狀男以致氣女 以除病心意娛樂氣力益壯不知道者則侵以衰欲知其道在安心和志 精神統歸不寒不暑不飽不餓定身正意性必舒 遲深內徐動出入欲 希以是為節慎無敢達女既懼喜男則不衰 黃帝又問何謂陰陽交合的原則？
 
素女答道：「男女交合，是天生自然，種族生命固定的自然現象。男人因此而精強氣壯，女子因此而百病消除，彼此心情偷快，身體健康 。若不瞭解交合之道，身體便會受損，逐漸衰危。」 「那麽，交合之道是什麽呢？就是要心情安定、意氣和諾、情緒穩定、身心一致。 依此養生，不暴寒暑，不過飽饑。心思光明行為磊落，性情自然舒泰翩然。」 初交合時緩綬插入，慢慢擺動，少作抽送，以此為要領，切忽犯忌，則女子愉快， 男人不衰。」 素女經非常重視心理問題，所以主張男人應在平時韜光養晦，交合時則要情緒安定 ，心境平和，自然能達到房事偷快，強身長壽目的。 男人性問題裏，感到最苦惱的，恐怕就是「早洩」。深怕自己的早洩，不能滿足女子的要求，這是性生活裏最危險的事。男人若因偶而有過類似的情形，心存顧忌，在此種心理作祟下，日後交合時，便易失去信心，以致萎縮不前。經年累月之後，也就強不起來了。
 
素女有鑒於此，便教黃帝首先要鎮定，要有自信心，儘量增長交合時間，則能治好早洩的毛病。 此外她又傳授如何運用針灸術的經絡原理，作交合前的愛撫，期使女子感到愉快， 提高性欲，最後達到高潮，關於此，可詳見於以後各章。 由於男女性高潮曲線不一致，因此在交合時，男子往往會過早洩精。尤其是沒有經 驗的男人，類似這種情形，更是屢見不鮮。
 
初婚之夜恐怕大都是如此。根據日本石洪淳美博士調查關於初次交合，有無失敗經驗，數字如左：
 
（1）無失敗…………………………七三．四％
 
（2）有失敗…………………………三六．０％
 
（3）不回答…………………………０：七％
 
由這項報告可看出，初次交合失敗的人，要比我們所能想像的要多。 當然初次失敗，也並非完全是男人早洩，但是這種原因卻占十分之一強，也就是說 每十個人就有一、兩個人會因交合前便洩精，而導致初交失敗。然而因為男人不懂溫柔 ，不熟習技巧使得女子痛楚而致初交失敗的數字卻三倍於此。
 
我們且來看看這項初交失 敗的原因統計：
 
（1）交合前陽具萎縮……………四．八％
 
（2）交合前便射精……………一一．三％
 
（3）交合疼痛……………………三七．一％
 
（4）找不到陰戶…………………一七．七％
 
（5）原因不明……………………二0．一％
 
（6）其他………………………三．六％
 
（7）沒有回答…………………五．
 
三％ 由以上的統計可以看出，男人在交合前太興奮或太緊張，以致於在剛接觸到女性器官的 刺激還沒插入腔道便已洩精，有更甚者，由於緊張過度，竟然不能勃起，自然不能進行 交合。第（3）項多是男人太過急迫，用在培養氣氛和前戲愛撫的時間不夠，彼此性器潤滑 度不夠便急著要插入，自然不能順利插入而導致女子痛楚，破壞初交的美感而失敗。至於男人帶槍上馬，竟然找不到孔道，摸不清津度，分辨不出膣道口，便完全是男人愚昧的罪過。 綜合上述（1）（2）（3）（4）項原因，我們不難發現，由於男人的忽略，導致初交失敗的機率 ，竟然高達百分之七十．九，這項數字還未包括另外百分之三十原因未明的答案，所以 百分之七十．九還算是最保守的估計。 素女經指點男人，要「定氣」「安心」「和志」，並要「淺內徐動」「出入欲希」 ，良有以也。 初婚之夜性行為失敗的夫妻，結果如何呢？且看下列統計：
 
（1）在已成為很圓滿的夫妻……七三．四％
 
（2）以後雖圓滿，卻仍離異……一九．二％
 
（3）進行不圓滿而離婚…………一.九％
 
（4）就因此離婚…………………四．五％
 
（5）不回答………………………六.六％
 
由於初交失敗而導致離異的數字的有四分之一，可見男人對於性交的是否完美，不論在技巧上或是心理上，都負有絕對的責任。 初夜陽具勃起不全、早洩或因其他原因不能完成性交時，絕對不能把它視為病態。 這都是心理因素，太緊張或太興奮所致，也有的是因為早期手淫，而產生自卑心理，又誤信傳說，以致恐懼不能達成任務，最後卻真的不能行房。有此現象的男人，只要平心靜氣，沉著準備，必能在第二回合中，過關斬將，直搗黃龍。 在所調查的資料中，第一次性交失敗後，而在以後能達成任務，不辱使命（繁衍種 族，繼往開來的歷史使命）的統計數字如左：
 
（1）第二次成功……………………三０．一％
 
（2）第三至五次……………………四三.八％
 
（3）第六至十次……………………一０．八％
 
（4）第十一次以後…………………八．八％
 
（5）不回答…………………………六．六％
 
男人早洩時，多少總會有些不安和慚愧。有些對性常識懂得很多的女子，會脫口而說： 「你出來了？差勁！」或「陽萎吧！」「是早洩！」等，如此，則會使男人喪失自信和自尊，往往造成日後真的性無能和早洩。遇到這種情形，女子應該溫柔地，若無其事地 勸丈夫早點休息，改日再來，或睡一會再試試看。 若是因為女子疼痛，不能順利交合時，千萬不要勉強括人造成不良後果。不妨暫停一會，等心情轉好後，利用愛撫和情話，培養良好氣氛，待雙方性器得到充份的潤滑後 再行交合。 在一連幾次都不能插入時，夫妻二人便應一起到醫德信譽較好的婦產科，接受醫生診察和指導。像「處女膜強韌症」是極罕見的，大多數還是女子的不安和恐懼所造成。 只要知道性器無異常現象，大可以放心。否則男人若太過勉強進行，觸到窒口造成膣道反射收縮，形成「膣痙攣」，便更麻煩了。
 
為求初夜順利而完美，男女雙方都應該找些正確的參考書，瞭解彼此性器官的構造 ，和一般性知識。然後再以心平氣和的態度，完成周公之禮。所謂「春宵一刻值千金」 ，為不使它白白浪擲，讀者不妨細心研讀本書，自可常保健康永遠愉快！
 
** 心平氣和舒泰自然
 
黃帝曰今欲強交接玉莖不起面慚意羞汗和珠子心情貪欲強助以手 何以強之願聞其道
 
素女曰帝之所問眾人所有凡欲接女固有經紀必 先和氣玉莖乃起順其五常存感九部女有五色番所足扣采其溢精取 液於口精氣還化填滿髓髒避七損之禁行八益之道勿逆五常身乃可保正氣內充何疾不去府藏安寧光滑潤理每即起氣力百倍敵人實服何慚之有
 
黃帝問：「我很想行房，但是陽具卻不能勃起，面對女子，羞愧得汗如雨下，無地自容。既使用手把陽具勉強塞進陰戶，也無濟於事。像這種情形，應該怎樣才能強壯呢？請把其中秘訣詳細地告訴我吧！」
 
素女答：「帝的問題，是大多數男子的通病。凡是要和女子交合，都應要有心理準備，按部就班。首先一定要心平氣和，惟有如此，陽具才會自然勃起堅硬。」 「男人若遵行五常之道，則女子必會有九種反應。女子在性欲反應方面有五個現象 ，等這些現象充分顯現後，體內就會儲滿精氣。此時男人用口吸女子唾液，便能使精氣返回自己體內，充滿在腦髓。如此便能避免觸犯七損的禁律，自然循行八益之法，而不會道溯五常之道。自可保持身體健康，充滿罡氣，還怕疾病不除？」 素女接著又說：「五臟六腑若健全，則形之於外，必然是光澤滿面，容顏煥發。每 次性交，陽具自是堅挺如鐵，氣力百倍，降服對手輕而易舉，再不會因陽萎而羞慚滿面了。」
 
素女指出，男人早洩是普遍現象，但是只要心平氣和，便能領會持久交合的要訣， 自然便能治好早洩的毛病。因此，若說早拽是生理的痼疾，毋寧視其為心理的癥結。 至於心平氣和之外，在實際的交合中，還有些什麽須注意的事呢？原來男女對於性 的反應，自有其一定程式。交合時也有一些不可觸犯的忌諱。若是能完全注意到「五常 」、「九氣」、「五色」、「七損」和「八益」之法，並能純熟運用，男人便會身強氣壯，禦服女子毫無困難。本章所說各法，在以後各章中會再詳為說明。 中醫一向很重視五臟中的「腎臟」器官。以為腎是儲存營養和精氣的所在。許多醫 家都很推崇大蒜，認為它能強腎。有吃蒜習慣的中國人，占著很大的比例。 建築埃及金字塔的工人，也常藉服食大蒜來補充體力。若用大蒜和大豆一齊烹煮， 食後對於強精壯腎，甚具功效。 腎的功能在體液、骨髓和排洩。男人在交台時！吸取女子唾液以補髓，故能精氣滿盈，身體強壯，尤其能加強性的能力。房中術的還精補腦（髓海）法、還精法、吸精法和采陰補陽等，都是由這種原理導引而出。凡是精於房中術者，都是用還精的方法，以吸重播出的部分分泌液。 古代帝王，都在宮內，供養一些採捕道士。這些道士能使皇帝夜禦百婦而不疲，在 三宮六院七十二妃依然夜丈夫，稱雄床第。許多精於此道的衛士，其采陰補陽的功力造 諧甚高，把陽具伸人杯中，吸取杯中盛水，然後複聚力壓出水份再人杯中。如此便能在交合時，熟用探陰補陽之術了。 印度的瑜伽行者，也責際表演過這種道行。他們能用肛門自由放水吸水，把裝滿一杯水的杯子放在地上，一面輕振杯腰處，一面運氣吸水，只需兩、三分鐘就能把水吸盡 ，接著又注回原處。 這種事聽起來似乎有些不可能，但是確有此事。修煉的人以意志集中，達到控制生 理的目的，並非難事。一般人若能注意力集中，也能作若干程度的控制。素女經的要旨 ，不外乎人在交合時，不要太緊張太興奮，穩健把持，雖然說射精是反射作用，但是只 要控制得法，並對自律神經訓練有素，還是不會早洩的！
 
** 愛撫的必要
 
玄女經云黃帝曰交接之時女或不悅其質不動其液不出玉莖不強小 而不勢何以爾也玄女曰陰陽者相感而應耳故陽不得陰則不喜陰不 得陽則不起男欲接而女不樂女欲接而男不欲二心不和精氣不感加以卒上暴下愛樂未施男欲求女女欲求男情意合同俱有悅心故女質 振感男莖盛男勢營扣偷鼠精液流流溢玉莖施縱乍緩乍急玉戶開翕 或實作而不勞強敵自佚吸精引氣灌溉朱室今陳八事其法備悉伸縮 俯仰前欲屈折帝番行之慎莫違失言大經記載，
 
黃帝問：「交合時，女子沒有快感，不覺春情蕩漾，陰道也不潤濕不流津液。男人陽具無法勃起，勢小而力弱，這是什麽原因呢？」
 
玄女答：「陰陽二者，相應相生。所以，女子須受男人的刺激才能產生愉快的性感覺，同理，男人若沒有女子的刺激，也不能勃起。在此情況下，男人想插入，女子必定不偷快，反之，女子想交合，男人也必缺興致。 「男女二心不能相投，因此都引發不起對方性欲，若要強行交合，動作粗暴，自然會使對方嫌惡。相反的情形下，若男有情、女有意，則意氣相投，女子自然會芳心大動 ，意態媚妍。男人的陽具即刻勃起，勇不可當。龜頭並會滴出少許液體，此時男人要扣 壓俞鼠部位，然後將陽具插人陰道。快慢自如，隨心所欲。女子陰戶也能配合作開啟張合動作。如此不必花費太多的氣力，便能使女子得到很大的快感。」
 
「男人際此之時，便應吸入女子精氣，以補充體力。交合的八種技巧，方法具備— ——伸縮、俯仰、前驅、轉折，望帝熟查實地作去．萬勿違反這些原則。」 玄女指出，在交合時，若彼此的性欲程度不同時，則另一方雖有滿盆熱火，也燃不 著北極的冰山，若要勉強交合，不但不能達到快感，反而會使對方發生厭惡感。 她勸黃帝要善用「前戲」的技巧，尤其著重身體重要部位的愛撫。特別是和經絡針 灸穴道關鍵的部位。中國房中術一向主張；為了要使女性及早達到高潮，並又能避免男 人浪費精力起見，都極強調交合前戲的技巧。 並且在性交時，磨擦次數不宜太快。動作也要儘量緩慢，以免太過興奮而造成早洩 。並須壓撫女子「玉門」，然後再向上撫壓「俞鼠」部位。「俞鼠」的意思，俞是「空的小船」，鼠是「四足獸」，意思則是「放進舟形祭器作為犧牲的四足獸」，以此為影 射，語意雙關，意在不言中（俞鼠即是陰核）。 綜觀本章，主要的意思有二，其一是要撫摩性感帶，其二是吸女子精氣，以「還精 補腦」。
 
關於性感帶，粗分一下，可以分為外部性感帶和內部性感帶。素女經於此，談得深入而詳盡，請見以後各章的介紹。至於女子到底是內部或外部的刺激比較強呢？這固然是個人的感覺差異問題，並且與經驗多少也有連帶關係。素女經的記載顯示出，在興奮發生時，外部的感覺會比內部強而敏感。這又是我國先哲的智慧處。因此，現代人切勿以為既然最終目標在於男女性器的交合，便不需再作外部的愛撫刺激，就大錯特錯。而因此造成女子不能達到高潮，男人易於早洩的後果，即是此種急功近利，欲速不達的必然結果。 至於「還精補腦」，以吸取女子唾液為補充男人消耗精氣，此種作法，也是為現代 醫學所認定的。日本石原博士指出，此種方法系暗示著荷爾蒙、腦內的分泌腺與生殖腺 體的關係。同時還精補腦法，利用吸人大量空氣，使體內獲得充分的氧，這種補身的方 法，也和美國庫巴博士主張——「吸氧運動aerobic」原理——相通的。
 
本章提到「男莖盛，男勢營……精液流溢」，指出男人陽具勃起和黏液發生的現象 人們一興奮，血液就會集中在皮膚下的微小血管裏，因此會有臉紅現象，陽具也如此。它的血管構造很特殊，乃由許多的結締組織，動靜脈管和無條紋的肌肉所組成，稱 為「勃起性的體素」，它可由中樞喚起也可以由觸覺激發。因此男人腦中想到色情時， 陽具便會勃然堅挺，若經女子搬弄也會霍然怒張。這都是陽具因興奮充血的結果，因此西諺說：「勃起是陽具的害臊」，雖屬譬喻，卻含至理。 勃起現象，不但是男人有，女人同樣也有，只是這種勃起體素和充血的特點比較不 明顯而已。非洲有種大猩猩，母的在性欲激動時，陰核和大陰唇的充血現象，便是一望即知，非常顯著的。人類一則因為陰核本來就不發達，再則因為有新演化而成的陰阜和大陰唇，於是充血現象便隱而不彰。 雖然不易看到女子充血現象，可是賃藉觸覺仍然可以查知。因將女子這些部位富有海棉式彈性。一經充血，彈性便大增。女子的陰道，包括子宮在內，滿布著血管。因此在性欲發作時，即呈高度的充血現象，可以用手指敏銳的觸覺體會出來，此輿陽具的勃起，實差可比擬。陽具除了勃起外，亞會由尿道滴出些黏液的來源，是一些小的腺體， 共有兩種，即「李脫瑞」和「李考」二氏腺。它們都在尿道旁，和尿道相通，每遇性輿 奮時，便會自動分泌黏液。以前禁欲主義的神學家也知道這種黏液的存在和意義，也曉 得它和精液是兩回事，更知道黏液的流出是心頭有淫念的證據。希臘羅馬時代也曾發現 這種現象輿性欲的關係。可是許多現代人，都把它輿精液混為一談，真是要令人扼腕浩 了。 輿此相反的，女子陰道的分泌物，卻比男人的現象要明顯得多。女子陰道在充血現象時，便會分泌一種液體，散佈浸淫著陰道口四周。這種無色無臭的液體，平時就有， 功用在潤濕陰道內外各部。但是在性欲到作特，會更大量的「放射」出來，其目的自然在使陰道更加潤滑，俾使陽具於交合時，更易進出不滯。胎兒若要由陰道出來，也必須有此種液體的潤澤和滑溜的功用。這種黏液大部份是由腺體分泌而出，此腺體也分佈 尿道口附近，它與腦神經中樞有著密切聯關係。
 
** 愛撫是藝術表現
 
一般說來，女性在性行為中既然是屬於被動的性質。那麽做丈夫的應該知道，急是不為妻子所歡迎的，所以愛撫的本意是誘導，而不是強迫。因此，愛撫的一切動作，都要由溫和的示愛，先不妨深深熱吻，進而撫弄乳峰，撫摩全身肌肉，輕觸外陰，按步就班，得寸進尺，一切都要順著妻子心理的發展，做到她恰好希望你去愛撫的時機和部位 ，這便是愛撫的藝術表現。
 
愛撫既是藝術的表現，熱情而對性交已有經驗的妻子，她們的陰蒂通常都會在被丈夫愛撫之前早已勃起而變硬。但是經驗較少的妻子，就不同了，她的陰蒂必需被丈夫用手巧妙地撫弄之後才能勃起。當這個豌豆大小的小東西被丈夫用手溫柔的加以撫摸時，它就會立刻勃起，而使附著在上的包皮向後捲縮，暴露出陰蒂頭部最敏感的部份。如果丈夫弄不清楚或摸錯了地方，妻子應當引導丈夫的手指至正確的位置。或利用暗示的方法告訴他現在撫摸的位置是否正確，或需要向那個方向移動或修正。丈夫就會慢慢地由經驗的累積，及對妻子陰部的實地研究與探看，而領悟到撫摸的藝術與技巧；不論是對陰蒂、小陰曆、尿道口、陰道口，及陰道裏面的撫摸，都能徹底地體會到它的效果。同時，這些用手指的摩擦，應與對妻子的口唇或乳房的吮吻同時進行，並且應不時插人一些溫柔體貼的情話，以增加愛情的氣氛。上述這些挑逗情愛的動作，絕不要單靠一方面 ，應隨著各種刺激同時進行。妻子的任何回應動作都是疽得嘉許的。當她被充分刺激而挑起性欲之後，她往往會自動去抓摸丈夫的陰莖。丈夫鬆軟的陰莖在她用手撫弄之下， 便漸漸膨脹起來，這時候，她會感覺快樂得無以復加。一般來說，丈夫的陰莖都會在妻子的玩弄之下而勃起。有時極端熱情的妻子，甚至會用自己的嘴去含住丈夫的陰莖，或 用丈夫的硬挺的陰室去摩擦自己的陰蒂，而從中獲得樂趣。雖然，她們並非在每次性交 前都會這樣作，但至少有時會這樣嘗試的。這種刺激方法通常都會使丈夫感到無限快樂 ，只是對他的刺激太烈，所以往往容易引起提前到達快感高潮而洩精。 因此，妻子必需適可而止。她應當只用手掌心或手指圍繞在丈夫陰莖的根部輕揉， 或是僅讓丈夫的龜頭部份摩擦其陰蒂。總之，一切的刺激方法，主要都是為了發動妻子 的性欲。所以她應當把握這項藝術要領，就是不要因為她的動作過火，使丈夫因興奮過 度而洩了精，使自己嘗了一次閉門羹。 當丈夫探摸妻子的陰戶時，假使他缺少經驗的話，妻子應該將他的手拉到自己感覺 最滿意的地方。丈夫還應作一番刺激陰道的實驗。妻子也應該指導他找到對刺激最敏感 的區域。有些妻子渴望丈夫刺激她的陰道，有些妻子歡迎丈夫刺激她的陰蒂，還有些妻 子感覺兩者使其獲得的快感是相等的。這種刺激需要繼續下去，直到徹底引起妻子渴望 性交時止。這時，她可以移開丈夫的手，丈夫可以決定他對妻子性交前的刺激是否徹底完成。一般說來，通常妻子受到充份刺激後，她的外陰唇與陰道壁都會被陰庭中的腺體 所分泌的潤滑液完全濕遍，甚至流到陰唇的外面。在這種情形下，妻子都有強烈渴望性 交的情緒，所以通常都不需要丈夫再察看她陰部對刺激的反應如何。 雖然愛撫是催促女性作性交預備的重要手段，但是，有許多地方是應該要注意的。 因為女性對於愛撫的接受，也有其心理上的步驟。如果一個丈夫在想和妻子做愛時，首 先便用手去撫摸她的性器，這是極易招致妻子反感的，尤其是用手指深人陰戶內部，不 但在女性有刺痛的感覺，和帶人細菌的憂慮，而且因為手指與陰莖不同，手指的經過彎 由探索，可以達到陰莖所不能達到的位置，也就是手指對陰道內臂的刺激，比陰莖所施 的刺激更大，如果經常用這種方式，可能要移轉妻子性交的興趣，甚至使她對正常性交 發生不能滿足之感，那就反而弄巧成拙了。 愛撫時間過長，使女性陰部腺液大量分泌得過多，超過了性交時所需的潤滑分量， 這也是減少性交刺激，降低夫妻性生活的美滿的，不可不慎。 夫妻在同房之內，妻子的心中，除性高潮的刹那間，希望男性的粗野以外，任何時 候，她都是渴望溫柔體貼的，她希望她的被愛，並非只是能供給丈夫洩欲而已，她要求 他愛她的肉體，更渴念他愛她的靈魂，所以愛撫能觸及全身，也可滿足她這種心理的， 假如她自豪有標準三圍的話，他愛撫的手法漏去她三圍之一，也許要令她失望的。 所以在愛撫時，不論是手的撫摸，臉的倚偎，唇的親吻，呼吸的交流，性器的接觸 ，乃至於肢體的擁抱交纏，都是女性渴望的，它的程度是，由上而下，由輕而重，由松 而緊，由外而內，由溫柔而至狂放。
 
** 性交的規則
 
素女經云黃帝曰陰陽貴有法乎素女曰臨禦時女先令婦人放平安身 屈兩腳男人其間銜其口吮其舌拊搏其玉莖擊其門戶東西兩傍如是 食頃徐徐內入玉莖肥大者內寸半弱小者入一寸勿搖動之徐出更入 除百病勿令四旁洩出玉莖入玉門自然生熱且急婦人身當自動搖上 與男相得然後深之男女百病消滅剌琴弦人三寸半當閉口刺之一 二三四五六七八九因深之昆石旁往來口當婦人口而吸氛行九九之 道訖乃如此 素女經中載，
 
黃帝問：「男女交合，須要遵守一定的順序法則嗎？」
 
素女答：「男人在和女子交合前，首先使女子心情安定平躺著，彎曲打開雙腿。男人便俯臥在她兩腿之間，吻其香唇，吸弄玉舌。用手播弄陽具彈擊陰戶和兩旁，如此前戲一段時間後，再慢慢插人女子陰道。」 「陽具肥大的人，插入一寸半，瘦小者插人一寸左右，不要搖動，緩緩抽出後再行插入，更能消除百病。洩時，不可洩溢在陰戶外部。陽具插入陰道後，自然會生熱激動 而射精。此時，女子便會情不自禁地搖動身體，與男人節奏配合。值此，男人再行深深 插入，則男女百病自都消除。」 「再淺刺女子陰核小蒂，更深插入三寸半，在陰戶內緊縮的當口，由一數到九，陽 具再往最探處插人，直抵大前庭腺，在此一進一出之際，男女吸吻著女子的口唇，進行 九九之法。這便是男女交合的順序法則。」 素女經的記載，不得不令現代人擊節讚歎。素女瞭解女子的性高潮，是漸漸上升， 達到頂點後，又緩緩下降而恢復原狀。因此她要男人在交合前，先各種調情動作，並在 射精後，仍需完成相當的交合動作，以使女子逐漸地回復平靜。 素女強調日唇的運用，這是非常有見地的。口唇是刺激性感的副交感神經的通道。 法國諺去：「女要精於烹調和床第工夫」。彼邦之所以特別強調烹調和交合之道，正輿 古云：「食色性也」的道理相通。因為，這兩者畢竟是人之大欲！ 提到陽具插人的尺寸，這裏所謂的「寸」，不是度量衡的寸，而是針灸術取穴法用 的尺度，也就是以中指的第二節長度為標準。男人量左手，女人度右手。
 
前者曾經提到性欲感受部位——性感帶－－可粗分為外部和內部兩大部份。性器官 也可分為外性器官和內性器官。如人的外性器可分為心丘（陰阜）、大陰唇、小陰唇、 陰核、陰前庭和處女膜等。 心丘又稱陰阜，在小腹之下，外陰部上方。皮下脂肪較多，賁起如小丘，業生心毛 。肌肉下有人心骨（骨 骨的一部份），成為交合時男人著力的支撐點之一。 大陰唇，是舟狀的外陰戶，左右一對厚大而隆起，皮膚有褶皺，富於皮下脂肪，心 毛業生（也稱陰毛）。受到陽具刺激時或壓迫時，能產生性欲，但其快樂程度較小。 小陰唇，緊沿大陰唇內側，為兩小瓣狀褶皺皮膚，不生心毛。處女時呈淡紅色，經 過性經驗和分娩後，顏色越濃而暗烏。左右兩瓣小陰唇，上方連接著包住陰核的包皮， 下方則連接在陰道日下方。由於密佈很多知覺神經，故而對性刺激非常敏感。
 
非洲的霍藤族（hottentot）以小陰唇愈大為愈美，女子多喜以手自己拉扯，使之增大以博異性歡心。 陰核，又稱陰蒂（即前章所謂的俞鼠）。在左右小陰唇交合上方，為豆狀大小的海 棉凸起組織，相當於男性的陽具。受到刺激也會充血而增大勃起。它是特別敏銳的部位 ，性感的程度大於小陰唇。 前庭，是小陰層所包圍著船底狀的狹窄部份。其下半部有膣的人口，上半部有尿道 的出口。由陰阜上方看下去的順序，為陰核、尿道口、腔口、會陰和肛門。其中有三個 出入口，其間有兩個性感帶（陰核和會陰）。會陰和肛門間也是很重要的性感帶。但是 女性手淫卻多半利用尿道。 處女膜，遮住膣的入口，為具有彈力的黏膜性薄膜。雖是處女，其膣口也都能有一 指粗空隙，以便月經排洩。處女膜多在初次交合時破裂。但是激烈運動或其他偶然狀況 下（如騎馬、騎車）也很容易破裂。也有韌性大伸縮力強的處女膜，雖有多次性交，仍 然保持原狀。故而以處女膜來衡量是否處女，是極不智的。在屢行性交或分娩數次後， 處女膜便只留殘痕，終至消失。
 
膣旁管和大前庭腺，前者在尿道口的兩側共一對，後者一對在膣口兩側。當興奮 刺激時，小陰唇開啟，此三腺管便分泌透明無味的潤滑黏液。 素女指點出，陽具插人陰戶的深度，是諳合女子生理構造的。因為膣在受到陽具插 入的刺激時，便因被強迫擴張，而力求收縮，以排除外界異物。這種四周緊縮的力量來 自骨盤底肌肉群。特別是腔日收縮肌（球海棉體肌）和膣壁收縮膜（舉肛肌）。膣管外 部三分之一的地方，收縮力特別強大，能夠十分強力地箍緊壓迫陽具，使男人感到非常 愉快而誘使男人感到非常愉快而誘使射精。因此男人陽具摩擦，也以陰道此部位為主。 而陰道內部，又由於男子深入摩擦抵撞，刺激於腹膜，遂而導致女子達到高潮。這便是素女經中早就提到的交合順序和規則的生理剖析。
 
** 性器的倫常
 
黃帝曰何謂五常素女曰玉莖實有五常之道深居隱處執節自守內懷 至德施行無己夫玉莖意欲施與者仁也中有空者我也端有節者禮也 意欲即起不欲即止者信也臨事低仰者智也是故真人因五常而節之 仁雖欲施予精苦不固義守其空者明當禁使無得多實既禁之道矣又 當施予故禮為之節其執誠持之信既著矣即當知交接之道故能從五 常身乃壽也
 
黃帝問：「為什麽叫做五常？」
 
素女答：「陽具有五個必須信守的原則。平時深居隱蔽，持節自愛像清居的隱士， 懷著至高的仁德之心，施於人而不吝惜，如此可謂仁。中問有空道，可謂義。前端有節（龜頭）可謂禮。意欲交合便勃然堅挺而起行，不想交合時又能戛然停止而偃息，可謂 信。房事臨頭亦能平心靜氣思慮交合法度，可謂智。因此君子能藉此五常來節制性欲， 是為交合的不易法則。」 「雖然因心存仁德，想有施予女子，奈因精力不足而不能堅挺，便應固守義德，坦 誠自禁，以免因房事過多而戕害身體，這便是節制之道。」 「若是身體狀況適宜作交合時，要以禮德並以誠心待之，如此便是信德的充分表現 。也即證明能夠確實瞭解交接之道。所以能謹守這五個原則——仁義禮智信－－的人， 便能、水遠健康快樂，長壽延年。」 所謂「人道」，在素經中的解釋可謂備盡。人道不僅是繁殖生育交合的能力，同時 也指的是道德。素女除了講求交合的技巧以達養生目的外，並強調交合的道德，這才是 正確的陰陽之道。因此要習房中術者，要有「仁義獲智信」品德上的修養。正如一些柔 道、跆拳、劍術等武功修為者，必須在品德上更加淬鏈一般。 孔子說「智與聖」，好比射箭的人，力能射得遠，是智的表現，射得遠而又中鵠， 便有賴聖了。以此比之房中術，能在男女交合得到快樂與健康固然是智；但若荒淫縱情 ，戕害對方而只求自利；便是品德上的缺失。 儒家以夫婦為「五倫」之始端，素女以「五常」為男女之始端，真是百世不易的定 論。 「仁」，人也。男子漢丈夫氣概，施予而不吝，同時也是己所不欲勿施予人的思想 。交合的高潮，男人把寶貴的精液輸注到女子體內，以完成繁衍種族、繼存生命的使命 ，充分發揮犧牲小我完作大我的精神。雖然射精是一種損失，但卻應有「施人愈多己愈 有」的態度。反之，若對方不願接受時，則不可勉強，這便是「仁」德精神的具體表現 孔子是尚仁道，他不為世人瞭解時便深居隱藏，若能用世，便以悲天憫人的胸懷義 無反顧貢獻自己。而素女以此譬喻男人五常的仁德，實在與儒家的主張不謀而合。 「義」，宜也。凡所行事必先求其適當，不為己甚。在精氣體力不足以交合時，不 可暴虎馮河，欲逞一時之勇，勉強交合致傷心身，終而害義。儒家主張有謂「小杖受之 ，大杖則逃」，告訴作子女的，萬一惹怒父母而受責打時，小杖便受之，若是大杖可能 會打傷身體時，便應趕快走避，以免受傷而使父母蒙上不義之罪名。男女交合的道理也 是相同。房事可行，可不行。若行而傷義，不如不行。 「禮」，理也。諺云：「鴻案相莊」，既使親蜜如夫妻，在云雨之際，魚水之時， 也應相互禮敬，才是人倫之道。男女交合，實已負有傳宗接代的神聖使命。膚淺的看法 ，以為男女性交，只不過是性欲的發洩。其實，生命為了要繁衍生殖，天生即賦有生殖 能力，並且內分泌還促使這種欲望取得發洩而滿足。以動物而言，每當春、秋或春秋二 季，性的驅力使它們全力追求異性，達到性交繁殖的目的。假若，還以為這也是肉欲的話，那麽植物的花朵，雌蕊和雄蕊，也經由各種方法（如風、蟲、水），達到花粉受精目的，它們是否也有肉欲呢？因此，人類性欲的背後，實在是一股繁衍種族生命的力量，這種力量是聖大而悠久的，是人的權利，也是人的義務。當人們進行性交時，實在已是執行這項神聖任務，因此，男女的交台不可視作淫亂，更不可流於淫亂。要不流於淫亂，便應持之以禮。
 
禮與節合稱，故日禮節。禮的原則即在於節。節，是有節制，不可肆濫。男女交合 ，禮敬的要領也在於茲。床第之歡，鶼蝶之樂，惟有相互禮敬的基礎上，才能獲得真正 的性愛快樂。
 
「信，誠也。言行一致，坐而言起能行，表裏如一。若有意交合，便能堅硬勃起，否則能偃然息止。此即言必行，行必中正。世聞柳下惠坐懷不亂，不是柳下惠性無能，雖有美女當前，也無力性行為。他是君子，誠信為上，不屑苟合而已。人不分男女，志操信守持節不變，乃是信德的最好表現。 「智」，知也。深思熟慮，不但是聰明的表現，也是成熟的顯現。女經說的臨事 低仰，就是警告男人，不要一見女色便冒失向前，魯莽行事。孫子兵法也說：「知己知彼，百戰百勝。」這裏知的解釋可謂是房中術的最佳注腳。
 
** 女性性感的測定
 
黃帝曰何以知女之快也素女曰有五徵五欲又有十動以觀其變而知 其故大五徵之候一曰面赤則徐徐合之二曰乳堅鼻汗則徐徐內之三 曰叫乾咽唾則徐徐搖之四口陰滑則徐徐深之五曰尻傅液則徐徐引 之 黃帝問：「女子快感時，有些什麽徵候呢？」
 
素女答：「女子一有快感，便會顯現出各種征狀，即是所謂五征五欲和十動。以這 些徵候便能知道女子是否快感，並且需要些什麽愛撫。」
 
「女子五徵：
 
一、臉頰暈紅時，男人可將陽具輕輕附在陰阜上。
 
二、乳頭堅硬，鼻間沁汗時，則慢慢插入陰阜。
 
三、喉乾唇燥，吞咽唾液時，陽具慢慢搖晃擺動陰戶。
 
四、陰道潤滑時，陽具徐徐有序地深深插入。
 
五、大量黏液流在臀部俊，便漸漸地抽出陽具。」
 
因為素女除了指出女子有各種性反應外，並且教導男人視對方的反應，作應有的動作。 因為女性性欲高潮出現較慢，費時已較多，男人便須作深度不同的動作，以滿足她的需 要，並達到高潮頂點。由始至終，設想周密。或因各人生理反應不一，表達也有程度上 的差異，然則萬宗不離其本，女子性反應大抵是相似的。男人若能善自觀察，把握時機 ，配合適當的戰術，必能克敵致果，無往不利。 女子性的反應，陰道分泌黏液已在上章提到，現在僅以臉頰變紅及出汗等現象，略 作敍述。 性交過程中，比較明顯的現象有兩組。其一是循環系統和呼吸系統，其二是肌肉動 作。事實上這兩組是分不開的。交合時的呼吸較為淺短而急促，並有斷續間止，這種呼 吸使血液變紫，也即是靜脈的活動高於動脈。因而刺激血管運動的中樞，而提高全身的 血壓，尤其是勃起性體素的血壓。在性交過程中，人們高血壓的提升是顯著的現象。根 據普賽（poussep）的觀察，動物在交尾時，血管的緊縮和鬆弛的轉換現象，快速而驚 人，這種快速的轉換，包括全身和腦部。 心跳加快，皮膚浮現的動脈血管更見鼓暴。眼球結膜或睛衣（conjunctiva）也變 紅。腺體作用也有全般加緊的趨勢，各種分泌的分量都有很大的增減。所有皮膚組織無 形中都加緊工作，因而汗量增加，汗流浹背中所夾雜的臭味，各種分泌，如腋下的狐臭 等也都跟著增加。口腔裏的唾液也大增，同時腎臟工作也增加。 第二組的肌肉動作中，隨意肌的活動力量減小動作，反之，不隨意肌的動作不但增 多！而且散佈得很廣，也很亂。比如，膀胱會在性交時起收縮作用，由於男女構造不同 ，其影響則相反。男子陽具勃起後，常會暫時不能排尿。女子則不但會增加排尿的欲 望，往往還會不由自主的溲溺而出。此外，如全身發攔抖、喉嚨緊收、口乾唇燥、打噴嚏 、放屁和其他類似的不自主的動作傾向。女子性欲亢進時，子宮的頸部（即陰道）會發??生節奏性的張弛動作，同時有大量的黏液放射而出。凡此，都是肌肉動作在交合時常見 的現象。 在性交時，男人面部表情，往往顯得特別的奮發有為，女子則益顯得鮮豔可愛容光 煥發。
 
一旦一屆臨高潮時，雙方的外觀就有了變化，瞳孔放大，鼻孔張大，禁不住地流出唾液，舌尖也不由自主地要來回翻動，綜而言之，無非表示一種官覺欲望的滿足，在快要來之前，大有迫不及待之勢。有些動物連耳朵都會豎起，人們此際往往日中喃喃說些支離破碎沒有意義的字眼，或是呼喚對方姓名，更作愉快的呻吟。 由於瞳仁放大而引起怕光的現象，所以在性交或接吻時，人們總是緊閉雙眼。在此之際，眼部肌肉的活動亢進程度大增，上眼臉的肌肉緊縮，故而眼球會變大，特別流動 而光亮。 高潮以後，這種愉快深人四肢百骸，它的震撼力量有時會引起很嚴重的影響。男人所受的影響更大於女子，因為後者的性欲下降曲線較為和緩不墜，這對女子來說可算是一種天然保障。初次性交的男子，在射精後往往有昏暈、嘔吐、遺尿、遺便的現象。患 羊癲癇的人，每每也會發作。更有的會內臟破裂出血。年事高者，動脈管經不起高度的 血壓，因而破裂的也時有所聞，若破裂出血部位是腦部，就成腦溢血而成中風或半身不 遂。老年人娶聘少婦或宿娼，有時即造成牡丹花下風流死的下場。 當然，上述現象並不多見，除非是神經特別脆弱，經不起刺激或太不自愛，完全不 顧性常識性衛生，才會發生此類事體。通常而言，性交達到高潮後，是有益於身心的。 這是一個十分自然的過程，也是生物體的一種十分美妙的功能。即使是個不很健康的人 ，也不會有什麽不良的影響。只要環境適宜，行之有度，這種過程可說是完全有利的。 因為它能消除在欲望中所蓄聚的緊張，減低血壓，恢復肌系正常狀態。獲取精神上的滿 足，一種通體安閒的感覺，舒適懶散的心情，心神解放，了無掛圭，萬物自得，天地皆 春的愉悅，是很難用筆墨形容的。 性交完成，不但達到生殖目的，完成種族使命，同時，對於個體的身心健康，亦自有其維護與培養的功能。
 
** 女性的生理需要
 
素女曰五欲者以知其應一曰意欲得之則屏息屏氣二曰陰欲得之則 鼻口丙張三曰精欲煩者則振掉而抱男四曰心欲滿者則汗流濕衣裳 五曰其快欲之甚者身直目眠 素女接著又說：「五欲，是女子在性交時，因性欲程度，而有不同的動作反應。由此，男人可判斷出她的快感程度。」
 
「女子五欲： 一、女子有被摟抱欲望時，就會屏息凝氣以待。 二、陰部需要撫弄時，鼻孔口唇會開張翕合。 三、陰液流出，欲望激增時，會振動身體，緊抱男人。 四、達到高潮、快感滿足時，即汗流浹背，濕透衣裳。 五、若到了極度快感，此時欲仙欲死，身如騰云駕霧，神魂飄升，身直目閉， 陶醉仙境而不自覺。」 陰陽交合，陰靜陽動，陰受陽施。關乎此，不但人類，大自然中絕大多數的動物都是如此。
 
女子的性欲無寧說是較為被動的，需要男人發動、引導而達成。因此男人不但要引發女子性欲，加強其性欲，並須善用方法使對方完滿地達到頂點高潮。 女子對性的需要，不是沒有，也不是不強烈，只是天生得比較隱晦而不明顯。但是 在她的動作中卻能尋出蛛絲馬跡。至於女子在這方面的需求，不容否認的，也和男人相 差無幾。有過性交經驗的女子，自然對男女交合有著渴求和希望，即是從未有過性交經 驗的女子，也會以撫弄或被撫弄身體器官，作為取得性欲滿足的替代。日本東京，目黑 區，菅井婦產科醫院菅井正朝醫學博士，曾經有過廣泛調查，發現在初次性交前的女子 ，和男人的性經驗統計如下：
 
（1）牽水……………………………六五．九％
 
（2）接吻……………………………六六．三％
 
（3）撫摸乳房………………………三五．七％
 
（4）摸女性生殖器…………………二五．０％
 
（5）摸男性生殖器…………………一一.七％
 
（6）吻男性生殖器…………………二．六％
 
（7）吻女性生殖器…………………二．０％
 
（8）皆無此經驗……………………九．四％
 
（9）不回答…………………………八．０％
 
由以上的統計可以看出，女子不但有被愛撫的欲望，也有主動撫愛男人的衝動行為 。有的人，尤其是女子，在沒有或一時不能完全的交合行為之前，這種愛撫的觸覺，已 經足以供給適當的快感與滿足。
 
女子的情緒生活中，觸覺是比較明顯的一部份。馬丁（lilian martin）研究大學女 生的審美情緒，發現她們觸覺的情緒比其他的情緒都要彰明。女子在春機發陳的年齡， ——— 所表示性的欲望，大抵不在性交，而在接吻或擁抱一類，比較單純的觸覺行為。就是已婚女子，或有交合經驗的女子，亦莫不如此。許多名作家，在小說裏都寫著：「她儘管 竭力的抵抗、掙扎，想擺脫他兩臂的環抱，但一望而知，她的目的無非是要把他和她接 觸的點、面、線，儘量的增加」。女詩人維菲思（renee vivien）說：觸的藝術是詭異 的、複雜的，它和香的夢境，以及音的奇跡，佔有同等的地位。」這句話，出自女子之 口，尤其值得我們重視。 素女深知女子對觸覺的敏感，因此在房中術裏，屢屢提示愛撫的重要性。因此本章 弟一點列出的，便是全身的摟抱，第二點是陰部的撫弄，第三點以後便是陰道的摩擦。 最後便水到渠成達到高潮的頂點
 
** 女性欲求的徵象
 
素女曰十動之效一曰丙手抱人者欲體相薄相當也二曰伸其兩腿者 切麽其上方也三曰張腹者欲其洩也四曰尻動者快善也五曰舉兩腳 拘人者欲其深也六曰交其兩股者內庠滔滔也七曰側搖者欲深切左 右也八曰舉身者迫人搖樂甚也九曰身巾縱者支體快也十曰陰液滑 者精已洩也見其效以知女之快也
 
素女說：「女子十個動作的象徵是： 一、兩手抱男人時，是想緊摟對方，陰部相觸。 二、挺伸雙股，是希望陰戶上方受到充分的摩擦。 三、露張腹部狀若迎奉，無非是希望男子射精。 四、臀部拽動，顯示女子已有快感。 五、雙腳彎曲，勾搭男人身體，是要陽具插得更深。 六、雨股腿相交，表示陰道內淫難禁。 七、腰向惻擺，希望陽具深插且左右搖弄。 八、曲身向上緊依男人時，已在高潮之途。 九、全身縱擺伸直，顯示出四肢百骸已達快樂頂點。 十、陰戶津液肆流，表示已達性感巔峰，完成高潮。 由以上女子十種動作，便能看出她快樂的程度。」
 
素女雖然羅列「五徵」、「五欲」和「十動」，發現女子在性交過程中有各種不同的姿態和反應，但不是說每個女子都會有這種過程或反應。是因人而異的，有時候即使 是同一個人，也會有其區別而不定。尤其一些感覺分散的女子，其個體差異很大，因此 表現出來的動作，自然不一致。 女子由性交初期而達到高潮頂點，雖然是有一定的程式，但是在實際交合時，卻未 必能每次都順利地達到高潮。其中原因固多，前面各章都已提到。尤其是已婚婦女，又 比較困難，更不易達到高潮。因為她們在家庭中，要照顧丈夫，要養育子女，要管理家 務，若又兼是職業婦女，則在一身數役之下，身心疲憊，就比較不易在性交時，順利達 到高潮。男人的生活，通常大部份在家庭以外，他對於家庭生活和家人的關係，所處的 地位比較超然。在男人的活動範圍內，家庭只占比較小的部份。而在這一小部份裏，他不必多作活動，只須休息而已。所以當一對夫妻在進行性交時，男人的態度，多是解欲 、鬆弛精神和一享云雨之樂。再加上生理反應，故而很容易達到性欲高潮。女子就不能 如此好整以暇地進行。她們顧忌事情比較多，尤其生育問題，人口和經濟的壓力，又使 她喘不過氣來。加之，女子生理結構的不同，性欲高升很慢，很不容易達到性交高潮。 如此，夫妻在性高潮上不能配合，男人比女子早洩精，不但造成性欲不滿足的問題 ，同時也會形成彼此心理上的疾症。女人由於經常不能得到滿足，容易自怨自文，發生 身心不調現象，甚而造成性冷感、性不感等現象。於是在日常生活中也覺得格格不人， 閨房勃溪時起，終成一對怨偶。至於男人，由於經常早洩，每每引起自尊心大受打擊， 總覺得一股歉疚，遂而發生逃避心理及行為，或是由此而生出相反的自衛行動，對於女 子的一言一行提出強烈的抗拮。於是，在雙方面都不讓步的情形下，自然造成家庭悲劇 。 根據美國女醫學博士大衛絲的調查，發現一千個大體上認為正常的已婚女子中，有 一一六人認為婚姻之不美滿，主要原因是性的不協調。 另外一位文哲家愛默生（emerson），研究到他診所來就診的女子，發現在調查一 千個女子中，有五分之二的人對性生活不滿意。 分析得更為精細的是漢密爾頓醫師，他所取的物件比較少，但男女兩性都有，而且都很正常。其中男女性各一百人。他根據每人所得的積點，把滿意或幸福的程度分為十 四級。發現男人滿意的程度，很明顯地在女子之上。在最高度的滿意各級（第七級至第 十四級）裏，男人占五十一人，女子只四十五人。其餘四十九位男人和五十五位女子皆 屬比較低級的滿意各級中。漢密爾頓醫師認為上，這個結論和其個人接觸時所得的印象很 相近。因此下個結論說：「一般而言，女子對於婚姻的失望，比起男子要來得更見嚴重 些。」 看了以上的研究報告，我們發現，世界上怨偶儘管有許多表面的原因，但是背後， 恐怕“性不調和”才是最主要的因素。因此，在尋求性行為正當、性生活健康之時，對於素女經所載的知識，便應深切瞭解，確實施行
 
** 從腳趾運動看性生活
 
玄女經云黃帝回意貪交接而莖不起可以強用不玄女曰不可矣夫欲 交接之道男候四至乃可致女九氣 黃帝曰何謂四至玄女說玉莖不怒和氣不至怒而不大肌氣不至大而 不堅而不熱神氣不至故怒者精之明大者精之間堅者精之戶熱者精 之門四氣骨氣不至堅至而節之以道開機不妄開精不洩矣
 
古女經記載，黃帝問：「一直想不停地交合，無奈陽具不能堅挺，是否能勉強去作呢？」
 
玄女答：「不可以！在交合時，男人必須四至齊備，女子要九氣周到，才能進行交合。
 
黃帝又問：「男人是那四候？」
 
玄女答：「陽具不怒張，便是蓄力不充足；怒張而不硬大，便是肌力不充足；硬大而不堅硬，便是筋力不充足；堅硬而不熱燙，便是內力不充足。所以，陽具怒靈，就表 示蓄力可發，戰志高昂；陽具硬大，就表示軍容壯大，即可進擊；陽具堅硬，就表示磨 拳擦掌，叩關攻城；陽具熱燙，就表示烈火沸鼎，欲罷不能。」 素女接著又特別提到：「既使和氣、肌氣、骨氣和神氣齊備到來，也不要逞強好勇 損耗元氣。應該曉得節制之道，不隨意興啟交合，交合時也不濫行洩精。」 黃帝陽具勃起無力，恐怕是現代繁冗社會中，大多數男人的通病。男人精力的強弱 ，固然和先天的因素有密切的關係（如遺傳、種族、食物、生活習慣等），但是後天的 鍛煉卻能改變上述的各種影響。 讀者或許在全球旅行中有過經驗，有些旅館飯店的衛生設備箱中，總會附有男用保險套，在東方人或米食國度的旅館中，大概附有一至二付保險套。在歐美，則每每附有半打以上。由此可見，歐美男人的性能力顯然要比較強些。當然，東方人也有性能力強過彼邦的，以上只是一般現象。
 
男子氣概等於零的時候，可能就是女子無法得到滿足之際，兩人眼睜睜地看著奄奄一息的「玉莖」，像條僵蠶一般垂頭喪氣，不禁想起窮途末路的楚霸王，這種羞愧，真會逼得人要烏江自刎。 對於這種性無能，中國醫學古有秘方。古賢發現「腳趾能影響性能力」，身體的經絡，由五趾的筋循踝、膝而上，經大腿、尻而直通性器。若是腳趾屈伸的機能不夠，就 會影響到性器的強健，終於使得性器萎縮，不能人道。此外，肝臟和腳筋也有密切的關 系。一旦肝臟生病，功能惡化，經絡道發生故障，腳趾便屈伸困難，連帶地影響到性器 官，使性器萎縮不振，不能人道。 腳趾的五趾中，由於經絡通道之故，使它們與肝、腎、胃和膽等皆發生密切關係。 所以性無能的關鍵雖然在足，可是間接的影響，卻是不少。古傳的觀趾法（足心道）， 由大拇趾診脾肝、二趾斷胃心、中趾察胃脾和無名趾觀膽肺、小趾看膀胱和腎。只要觀 察腳趾變形的狀態（彎曲、腫大、細小、僵硬）即知有關五臟機能的盛衰，而及早治療 、祛除疾病。 相反地，若是腳脖經常作彎曲運動，腳趾不斷地作屈伸，則不但可使內臟健全，陽 具勢必也會日見茁壯，所向披靡。 蘿匐腿或是小腿太粗短的女子，大都是性能力不強。這是因為連絡性器的腳筋，受 到拘束，不能充分活動的關係。補救的惟一方法，便是多作腳趾屈伸運動。 在前述各章中提到，鍛鏈陽具的方法，就是「死往生還」，最早見載於「玉房秘訣 」。若依照那種方法，約摸十數天，則陽具會堅如鐵棒，熱似火把，成為百戰百勝的利 器。許多古籍小說中也提到關於陽具鍛鏈之事。南北朝時，武成帝的專寵胡氏，曾與西 域僧曇獻作云雨之歡，曇獻僧極擅運氣術，鍛鏈成百鋼打造般的陽具。每逢交合時，都 能伸縮自如，縮小時像宦官去勢一般，萎縮難見。伸長時，又暴突怒張，長達二十公分 ，並且粗壯熱燙，觸手炙熱。 據說日本大正末期，在小撙地區有族叫「愛儂」的搬貨工人，他們有著很強的性能持續力，在交合之際，可以一直維持到天明，即使妓女見著他們上門，也嚇得從後門溜掉。原來，他們有一種特別的陽具鍛煉法，就是用一顆類似秤錘的鐵墜子，吊在陽具上 ，除了性交和小便外，都不取下來，鐵墜子是用繩子綁著吊在陽具上，看起來發好像長著三個睾丸一般。
 
** 房中的重要過程
 
玄女經云黃帝曰善哉女之九氣何以知之玄女曰伺其九氣以知之女人大息而咽唾者肺氣來至嗚而吮人者心氣來至抱而持人者脾氣來 至陰門滑澤者腎氣來至勤殷昨人者骨氣來至足拘人者筋氣來至撫 弄玉堂者血氣來至持弄男乳者肉氣來至人與交接弄其實以感其意 九氣皆至有不至者則容傷故不至可行其數以治之
 
玄女經記載，黃帝問：「我已明白男人的四至，那麽女人九氣又是什麽呢？
 
玄女答：「女人九氣也不難觀察，分述如下：
 
呼吸急促、吐咽口水，表示肺氣已組充實；
 
低吟呻嗚、吸吻男人，表示心氣已經充實；
 
雙臂抱人、緊纏不已，表示脾氣已經充實；
 
陰部滑濕、濃霧迷蒙，表示腎氣已經充實；
 
意態勤殷、齒咬男人，表示骨氣已經充實；
 
雙腳上曲、勾纏男股，表示筋氣已經充實；
 
輕舒柔夷、撫弄陽具，表示血氣已經充實；
 
意亂神迷、撫摸男乳，表示肉氣已經充實；
 
常與女子交合，撫弄對方的陰核（即俞鼠），體察她的九氣，務必要等到時機成熟 ，水到渠成才能交合。否則身心蒙受戕害。若有各氣不充足的現象，便要用九九之道（ 見第十二章）加以治療。」 男人有四至，女子有九氣。四至和九氣是相對相成的。早如玄女者，就發現男女的 性反應特徵，教導先民在男女交合時，必須顧及彼此的生理反應。一定得到時機湊巧， 果熟蒂落再行交合，這種論點，證之以今日的醫學，是非常明智的見解。美國金賽博士 也曾有類似的臨床報告。雙方若不顧及這種自然的性反應，不待時機成熟便行交合，便 會因為性高潮的不一致，而使單方面有「早洩」現象，往往造成身心的傷害。 前一章曾提到內臟與腳趾的密切關係。在此不妨再探討一下，內臟和五官的關係。
 
中醫發現： 肺的反應在鼻； 心的反應在舌； 脾的反應在口， 腎的反應在耳； 肝的反應在眼。 所以當女子九氣充足時，便自然反應在她的動作上，
 
如肺氣充實便會呼吸急促，吐咽口水；心氣和腎氣充實使低吟呻嗚，舌弄男口；腎氣充實時，陰部就會分泌黏液而潤濕， 骨氣充實時，齒牙便想齧人等等……。 所遺憾的是，玄女經雖云「九氣」，卻只明載了八氣，獨缺一氣，可能是少掉了肝內臟除了與五官有密切關係外，根據黃帝內經素問的記載，「天食人以五氣，地食人以五味」，五味影響五臟，故酸甜苦辣鹹不可多吃，否則內臟會受到傷害，略列如下
 
多食酸，則皮膚褶皺、唇皮揭舉， 多食甜，則骨骼酸痛、毛髮脫落； 多食苦，則皮膚乾燥、發毛掉落； 多食辣，則筋絡急暴、指爪乾枯； 多食鹹，則血行不暢、膚色不良。 五味養五臟，過食則傷之。五味又養那五臟呢？ 酸味益肝，食酸易生津，津液內溢而強肝，肝盛後影響到脾，脾受損後皮膚便起褶 皺，唇皮翻舉，更嚴重的會導致脊骨彎曲，排尿困難。因為肝屬木、腎屬水、脾屬土， 木克土之故。 甜味益脾，但是多食甜又傷腎，便會令人氣悶、骨骼酸酸、毛髮脫落。因為脾屬土 、腎屬水，水克土之故。 苦味益心，多食後又傷肺，造成皮膚乾燥、發毛脫落現象。因為心屬火，肺屬金， 火克金之故。 辣味益肺，可是吃多了又會傷肝，以致筋脈急暴，指爪乾燥，精神不濟。因為肺屬 金、肝屬木，金克木之故。 鹹味益腎，然而吃得太鹹後又傷心，造成血行不暢、膚色不良等現象。因為腎屬水 、心屬火，水克火之故。 我國古代房中術的特色，在於利用男女交合，達到享樂和養生的雙重目的。因此特 別強調男人四至和女子九氣。其一，是希望男女皆能達到高潮，享受性愛之樂；其二是 希望彼此的官能和內臟都能充分發動，完成應有的功能。所以玄女說九氣不至，易傷身毀容，必須用九九之法來醫治才能挽救。
 
** 九法之一－－龍翻
 
玄女經云黃帝曰所說九法未聞其法願為陳之以開其意藏之石室行 其法式玄女曰
 
** 九法第一曰龍翻
 
令女正偃臥向上男伏其上隱於床女 舉其陰以受玉莖剌其轂實實又攻其上疏緩動搖八淺二深死往生返 勢壯且強女則煩悅其樂如倡致自閉固百病消亡
 
玄女經記載，黃帝問：「你曾說房事技巧有九種，今請一一說明，詳細講解，似便 撰錄成冊，妥為收藏，演練其中的秘法。」 玄女答：「第一種名叫龍翻。」 「女子面向上躺臥，男人伏趴在對方身，男股在女子兩腿中間。女子陰戶上迎陽具 ，陽具刺戮陰核，攻擊陰戶上部。然後在插入陰道時，疏緩搖動，行八淺二深之法，陽 具堅硬時抽出，稍軟時再行插人，遵照死往生返的原則，陽具便能日益壯強；女子也會 無雙愉悅，春情蕩漾。陰道緊縮，百病消除。」 九法之中，首推「龍翻」。是因為這種女在下，男在上的交合，為所有人適用，大 多數人採用的姿勢。交合時，男人雙手和兩膝彎曲支撐身體，望之似龍，故名曰龍翻。 翻，則是龍的動作了。 性交，是上下起伏，和左右摩擦的韻律動作所構成。房中術所主張的「八淺二深， 古往左往，死往生返」，龍翻姿勢足以滿足這種技巧的條件。因此，讀者不妨多多利用 龍翻姿勢，達成素女經的要求。
 
在九法中，可以看出特別強調撫弄女子外部器官。如本章中提到「刺其穀實」，即是用手或用陽具刺戟女子陰核（或稱陰蒂）。因為這一部位是女子最敏感的地方，刻意 地愛撫後，能很快地提高女子性欲，使她性欲高漲達成高潮，得到滿足。「龍翻」姿勢，男人壓伏在女子身上，也能帶給女子身臨交合之境的快感。女子正面的一對乳房和陰阜，承受著男人壓力，產生出肌膚相親的觸覺快感。對男人而言，壓伏著女，可以滿足「征服欲」。這種潛意識的優越感，並遍存在男人腦海裏。雖然口中不說，但是在性交過程中，一種虐待狂似的動作，卻一覽無遺，因此也更提高了交合的興致和樂趣。這種心理若是變態發展，即成為「開苞」狂，許多腦滿腸肥的人，花費百 千倍以上的嫖資，在貪利的老鴇撮合下，專揀處女性交，度「破瓜」之夜，極肆其虐待 狂態。 龍翻姿勢，不但是中國人通常採用的姿勢，也是世界各地人所探的傳統姿勢。西洋 人稱之為「愛神正看式」。由這個名稱，就知道它是多麽為人們所推崇。正像玄女經中 將它與「龍」並稱一般。龍是神物象徵吉祥，和「愛神」的崇高、神聖之意，恰有異曲同工之妙。
 
** 九法之二－－虎步
 
第二曰步令女俯伏尻仰首伏男跪其後抱其腹乃內玉莖剌其中極務 令深密進退相薄行五八之數其度自得女陰閉張精液外溢華而休息 百病不發男益盛
 
「第二種名叫虎步。」
 
玄女接著說：「女子面向下俯伏，屁股高墊，頭部向下。男人跪在她股後，雙手抱女腰腹，插人陽具後，直抵最深處。速抽速送，約四十次左右，自行適度控制，待女子陰戶一緊一縮，津液溢流而出，就可以嗚金收兵，靜靜休息。如此便能百病不生，男人更力壯。」
 
這種姿勢下男人，很像是猛虎蹲踞在獵物後面，虎視耽耽，隨時可以攫取對方，故名曰「虎步」，極為傳神。包括演化史上，與人類最近的一切高等動物中，它們的交合方式，都是公性動物， 走到牝的背後，進行性交。直到了人類，才漸漸採用面對面的正交方式。因此，當男女採取，或是由男人提出此種「虎步」姿勢的建議後，雙方會立刻有原始世界的刺激感。這種刺激可以迅速地提高彼此的性欲，是很有價償的一種態位。 孩童經常會對兩隻正在交尾的狗，發生好奇的圍觀。男女成人雖然一眼即知那是怎麽回事，可是心中對這種交尾的姿勢，仍會留下深刻的印象，以及對這種姿勢會帶來什樣的樂趣？總是惦念不忘的。大多數的女子，可能羞懼心理的影響，會拒絕傳統（龍翻 ）方式以外的性交姿勢，更遑論冀求她們主動地提出。於是姿勢的變化，便有賴於男人的主動提出和指引。 男人在女子背後，可以飽覽圓肩、潤背、細腰和豐臀，雙s形的弧線，背後看來更誘人。採用虎步的優點，是男人不必用兩手支撐身體，空出的一隻手可盡情撫摩雙乳、 把握細腰、扣擦會陰等。在抽送進退之際，可以緊摟女腰，狠力抽送直達陰道。也可以用雙手擺動女臀，配合陽具左右的擺動。因此，陽具的靈活進攻，該是虎步最大的特色 。然而所要特別注意的是，在這種姿勢下的女子，陰戶與肛門同時暴露向外，若遇粗心 大意的男人，很容易因為插錯孔道而人肛門，粗大的陽具遽入肛門這種劇痛足以破壞交 合美好的氣氛。女子在虎步的姿勢下，雖然陰核無法得到陽具磨擦的滿足，但是陽具能 更深人抵達陰道深處，這快感足以作為彌補。同時，也能獲得左右輕鬆擺與男人節奏配合的樂趣。 男人在撫摸豐腎之際，不禁要讚美母性和女性的偉大特徵之美。國際審美標準，要求臀部比胸圍大二公分的理由，不僅是基於美感，也是源自種族繁衍的意識。 崇尚大臀之美，主要是把胎養在母道的基本條件並觀所在。臀部大，骨盤也大，才能生出較大頭顱的嬰兒來，而優秀種族的頭顱也一定是較大的。同時，世界上高級的種族也都是大臀的
  
** 九法之三——猿博
 
第三曰猿博令女偃臥男擔其股腹還通胸尻背俱舉乃內玉莖刺其臭 鼠女煩勸搖精液如雨男深案之極壯且怒女快乃止百病自愈
 
「第三種名叫猿博。」
 
「女子仰躺，高舉雙腿。男人面向女子，跪在股後，雙手棒扶女腿擔在雙肩上，使 女雙膝高度過胸，並略提起對方屁股脊背。」玄女接著又說：「此時再插人陽具、刺戟臭鼠（俞鼠的別名），女子就會快樂無比，黏雨如雨下滴。陽具就再深深插人，則會更形堅挺硬壯；待女子高潮後即大功告成。用此技巧，自然百病消除。」 「猿博」姿勢，以男人肩抗女子雙腿為特色。是我國古代男性非常喜歡採用的姿勢 ，以前的春宮圖裏，有很多這種交合的姿勢。男人姿勢在虎步和猿博中相同，只是後者必須肩擔對方的雙腿。
 
這兩種姿勢的好處，即是能把女子的陰戶升高而凸出，比較利於進行交合的動行，對於陰戶位置生得比較低的女子，更能補救此缺點。同時還能避免陽具因短小而不時滑出的機會。若是女子屬於窈窕型，而男人又是圓胖型時，採取這種姿勢真是最恰當不過了的。肥胖的人在性交時，由於腹圍太大，減少陽具與陰道接觸的深度，雙方都不容易得到快感，同時陽具由於不能深人，便會不斷地滑出陰道，因此便會 減少了性交的樂趣。但若採取虎步或猿博的姿勢，便能補救這項缺點。 女子雙腿由男人雙肩來承擔，是很新鮮的。但這也只限於擁有如玉美腿的女子。若 是一雙癡肥頭大而粗壯不雅的「愚」腿，不但不能產生美感，恐怕還會令這位男士，作 嘔三天，還談什麽猿博呢？ 男人都很喜歡窈窕型的美女和小腳女子，這恐怕是因為肥大的腎部和大腳丫，有不易搬動的缺點所使然。 把「足」和「性」聯繫在一起，原是中外古今很普遍的一個現象。猶太人說到性器官時，常會婉轉的用「足」字來代替。舊約以賽亞書中，就有所謂「腳上的毛」，意思就是陰毛。在中國、西班牙和羅馬，以及許多民族，古時候女子的足，也是怕羞的一部 份，必須隱匿起來，不輕易示人。同時，足（甚至是足所穿著的鞋子）也是戀慕物件之 一，這種現象還非常普遍。如中國許多名詩都是用來吟讀「三寸金蓮」或是繡花鞋的。 西洋人也經常用高跟鞋痛飲白蘭地。 「小腳」和大腳相反，常能刺激男人的性欲。六朝時代有本小說，名叫「飛燕外傳 」，描寫趙飛燕和合德姊妹的軼事。提到成帝晚年因房事過多，患了精力減退、陽萎的毛病。但是每次一看到合德的小腳時，便忽然精力飽滿，性欲激昂。 飛燕的腳也被形容得「能為掌上舞」，可見她不但身輕如燕，一雙金蓮還沒男人一隻手掌大。
 
據說，楊貴妃在亂軍中被皇帝賜死後，有人拾到她的一隻繡花鞋，縱長只十公分而已，被視為無上珍寶。怪不得詩人描寫女子小腳為金蓮，小腳就像一瓣一瓣的蓮花一樣裹小腳的習尚。大抵由此開始，約在北宋以後。纏足再配合柔軟體操和呼吸法， 使女子在交合時，表現出特別的技巧，令男人樂不可支。趙飛燕幼時便束緊腰部、調練呼吸勤練快舞，而得寵君前。風氣所趨，形成社會普遍對小腳好感，產生很高的評價。造成母親在女孩很小的時候，就用布巾將她們一雙腳緊緊纏裹住，走起路來也一搖一擺 ，婀娜多姿。這都是根據古代的導引法和胎息法想出來的絕招，由於不合乎健康原則， 早已為國人所唾棄。 也有人說，纏足為的是要使女子行動不能太自由，防止她們逃亡而作的必要措施。 這種論據是稍為牽強而論理也略嫌薄弱。因為貧窮的丈夫，希望婦人分擔勞務，並同負 擔經濟開銷，她所作的事愈多愈好，至於推車擔漿在所不計，小腳怎能負擔？富有的家庭，三妻四妾雖有逃跑可能，但數倍於此的家丁家將，把莊守院，既使再大腳的女子， 插翅也難逃。 我們若把「纏小腳」和三妻四妾的制度相題並論，是比較合理的想法。當時的男人 ，把女子視為財產之一，作為寵玩的禁戀。小腳只是此種制度的衍生而已。 清朝的李笠翁，曾著「肉蒲團」一書。他素來反對女子纏足，但也明確指出，纏足 的用意，除了是要被男人愛惜和撫弄外，同時也還有性的作用。 古代許多武術師，雖然纏足，也照樣能手提重物，健步如飛，至若舞刀弄棍更是不 讓鬚眉。這是因為她們練藝習武，自然與平常女子不同。 由於女性纏足，配合房中術的技巧，發展出四十八種閨房秘技，成為所謂的「第二 性技」。例如纏足應用在「食」的方面，可以在五趾彎曲的深溝裏，放入瓜子和葡萄乾 之類的食物，男人用舌頭去舔食，這是一種刺激性興奮的調情動作。 至於在「承」的方面，即是把小腳分別在頰上、膝上以及陽具上撫弄，藉以提高性 欲。「懸」，則是把女子纏足的布解開，再用此布把女子的腳倒懸在床臺上，用以提升 男人性欲。「捉」即是將女子小腳，放在男人腳上，然後逐漸抬高。「挾」是要女子把 小腳緊抱在胸前。「推」是女子的兩腳當作車病，雙手推握作推車狀。「挑」是將女子 的一隻腳擔在男人肩上所作的性愛動作。這種放一隻腳在男人肩上的動作，也曾在「洞 玄子」一書中出現，是「卅法」之一，稱之為「馬搖蹄」，為許多男人所樂於採用。 此外，用到舌頭和牙齒的有「吮」和「舔」。前者是男人用嘴像吸母乳般地，吸吮小腳蓮尖；「舔」是吻著小腳腳掌。「齧」是輕輕齧咬金蓮；「咬」則是用力齧咬腳趾 。 「金瓶梅」中，西門慶用三根手指，撥弄賞玩潘金蓮的腳趾，這叫「撚」。雙手掬 握叫「握」，還有「捏」，大拇指搔小腳腳板底叫「搔」。中指插人腳趾間的深溝裏， 輕輕摩擦叫「控」。 「肉蒲團」書中所說的「順水推舟」，即是古女經中的龍翻。順水推船而下， 用用力少而船行速，所以作者才用這個名稱。 「龍翻」和「猿搏」，都是使陽具壯大的性交秘技。「肉蒲團」書中，表演性 主角是「未央公」，他因曾蒙仙家的指點，故而陽具長如竹箸、粗以茶碗，堅韌則 於豆腐。他之所以比喻成豆腐，是有一番道理的。因為金銀銅鐵雖硬，但是就怕火 水浸。豆腐不但是水浸它不壞，即使在鍋中煮，也是愈煮愈硬。以此譬喻，實在是 風味。明代小說，「僧忠孽海」中的喇嘛高僧，有兩種交合秘法，稱為雙修法，即 翻和猿搏的姿勢。這兩種交合姿勢都是能使陽具壯大，又使女子歡樂的絕佳技巧。
 
** 九法之四——蟬附
 
第四曰蟬附令女伏臥直伸其軀男伏其後深內玉莖小舉其尻以扣其 赤珠行六九之數女煩精流陰裏動意外為開舒女快乃止七傷自除
 
玄女說：「第四種名叫蟬附。」
 
「女子面向下，身體正直俯臥。男人趴伏在她背後。將陽具深深插入後，略抬高女股，再用陽具刺戟小陰唇（赤珠），反覆作五十四次，等到對方春情蕩漾，黏津流溢， 陰道顫動，陰戶大開，達到高潮後就停止動作，便能消除因喜、怒、憂、思、悲、恐、 驚等十種情緒導致的病症。」 「蟬附」交合中，女子的姿勢是面向下俯臥，在交合時動作較少，多半在左右擺臀 迎合男人的陽具衝刺，這也是很適合陰戶部位生得比較低的女性運用。 男人雖然說是趴在女子背上，但卻不是將全身力量放置在她身上。而是用雙肘支撐 著身體重量，雙腳打開依靠床上。因此，在下位女子，不會因為因男人全身重量壓得她透不過氣來。行房時的呼吸比較急促，若肺胸部受到壓迫，會造成呼吸困難，破壞性交情趣。男人行此法時，得顧名思義，蟬是「附」，而非「壓」。 女子因受姿勢限制，身上又有男人趴伏，若想要她有很理想的配合動作是不太可能 的。因此男人便是負責絕大部位的「勞務」。假如女子陰戶生得太低，或是陽具長度不 夠，便會在抽送之際滑出陰道，此時不妨在女子骨盤下墊個小枕頭之類的東西，以使陰 戶抬高暴露。 由這種姿勢變化而出的，是男人與女子同樣側身並臥，進行交合。在這種並臥姿勢 下，女人可免受男人重量壓迫，男人也可以不必用雙手兩膝來支撐身體。甚至於懶一點 的男人根本毫不出力，而完全由女子擺動。
 
大詩人白樂天的弟弟白行簡，曾作賦歌頌皇帝和武則天交合之樂。唐皇在性交方面是比較懶於行動的，他喜歡採用並臥蟬附式。自行簡的這篇賦，是在甘肅省、敦煌縣的嗚沙山一個石室中被發掘出來的，名叫「天地陰陽交歡大樂賦」。其中描寫「武後（武 則天）打開帳，爬上龍床，花容月貌，星眼明醫。由侍女攙扶著褪褫衣裳，露出雪玉般肌膚，獻出豐潤的玉臀，皇帝將陽具三番兩次地抽送，以滿足武後無邊的情欲……。」
 
玄女經，九法中雖然沒有上述的側位，但以後所述的「七損」裏卻出現了側位。白 樂天作的「長恨歌」裏，曾有「在天願作比翼鳥」，據說就是描寫玄宗和楊貴妃，像比翼鳥一般的側臥位的性技法。
  
** 九法之五——龜騰
 
第五曰龜騰　令女正臥屈其兩膝男乃推之其足至乳深內玉莖刺嬰女 深淺以度令中其實女則感悅軀自搖舉精液流溢乃深極內女快乃止 行之勿失精力百倍
 
「第五種名叫龜騰。」
 
「女子面向上正躺，雙膝提起彎曲至胸前。」玄女又接著說：「男人跪姿面對女子 ，雙手推女腿至女乳。陽具刺激大前庭腺，並刺戟陰核。在一抽一送之際，必須深淺適度，並充分愛撫摩擦陰核。」 「女子時就會有很高的快感，自然擺動起身體，黏液也大量地分泌而出。陽具便更 深插人，使女子達到高潮後即休戰罷兵。若依此訣竅，男人定會精力百倍，身體強壯。 用這種交合的姿勢，女子在快感來臨時，由於全身為男人所束縛，雙腿又被緊推至 前胸前，此時為要宣洩快感情緒，必然會左右搖擺不停，連帶地使男人也左右勝翻不已 ，再加上陽具左往右往，便會像只烏龜般地沉醉在騰云駕霧中。因此，稱這種姿勢為「 龜騰」，實在描寫得淋漓盡致。 龜騰交合法，可以使陽具深人陰道。由於女子雙腿提高，臀尻也自然升高，陰戶便能為男人飽覽無遺。有些人觀念非常不正確，尤其女子更怕男人欣賞她的陰阜。其實女性的生殖器也是身體各種器官之一，它的功能和構造是偉大而神奇的。 一般女子毛髮較多的部分，除了頭髮外，便是陰阜附近業生的沁毛。有許多民族間 ，或在某些時期，非常風行拔除陰毛。像古羅馬的女子，陰毛的拔除，已經成一種時髦的習尚，正像今日的舞女剃掉腋毛一般。在希臘人的雕塑女像裏，我們固然找不到有陰毛的女像，但是這不過是藝術創作的習慣而已，它然和實際生活無干。因為我們發現在同時代的花瓶畫像中，所有的女像都是有陰毛的。此外，一般藝妓的裸像上，也是有陰毛的。
 
希臘女性美的典型人物，脫埃城的海倫（helen of troy）她的遺像就有陰毛，其他就可想而知。這顯示出各個民族，在各時期中的審美觀點，都是大同小異的。 女子沁毛的命運，和男人的鬍子一樣。它們早先只不過是純粹的生理保護作用和第二性徵的表像，正和許多禽類所生的羽毛、馬獅的鬣鬃一樣。沁毛和鬍子，有時候價值很高。
 
在男人，它代表著人格的尊嚴與華貴；在女子，它是美貌至高無上的標識。但是有時候，它又不免遭人厭棄，以致被截短、剃光或完全拔淨。 早年基督教力反留須，後又主張芟除陰毛。英國維多利亞女王時期，公認把陰毛畫梳理和眉毛之上了。
 
** 九法之六——鳳翔
 
第六曰鳳翔令女正臥自舉其腳男跪其股間兩手處席深內玉莖剌其 昆石堅熱內交令女動作行三八之數尻急相薄女陰開舒自吐精液女 快乃止百病消減
 
「第六種姿勢名叫鳳翔。」
 
「女子面向上正躺，雙腳彎曲打開。男人跪俯在女子兩腿中間，雙肘撐地。」「陽 具探人陰道，並刺戟陰核。在堅挺燙熱的陽具插人陰道時，讓女子搖擺二十四次。」 玄女又說：「務必要使女股密接陽具，陰道因興奮而大開，黏液如泉湧至。待女子 達到高潮後便偃旗息鼓。常行此法，百病自然消除。」 鳳，常和凰並稱。鳳是雄的，凰是牝的。鳳凰也可稱為鳳皇。諸如鳳凰這稱呼的，還有鴛鴦、蝴蝶等等，它們都是夫唱婦隨，恩愛逾恒，形影不離令人歆羨的對象。左傳 有「 鳳凰於飛」句，形容夫妻婚姻甜蜜，愛情彌堅。用「鳳翔」來形容本章交合的姿勢 ，真是恰當之至。 連同鳳翔，我們已經介紹過六種和以後的三種交合姿勢，對於人的生理都有很大的 助益。那麽姿勢的變化，對於男女雙方的心理，是否也有程度上的影響呢？當談到交接 的方式或姿勢，有人以為正常而合理的姿勢只有一種，就是男人在上，面向下趴俯在女 子身上，女子則面向上平躺仰在男人之下。也就是我們在第十八章中所提到的「龍翻」 姿勢。至於其他的姿勢，都被視為淫蕩或邪惡。
 
美國名醫師，范特弗爾特在談到歐洲人的性生活時，說那些作丈夫的，大部份都不知道床第生活的單調，也不知道這單調的生活，是可以用姿勢的變換來改進的。而這種姿勢的改變，並沒有逾越出正常的範圍之外。然而，他們由於瞭解不夠，始終無法打開這個癥結，以致一直不能改善他們刻板無味的性生活。
 
近世，許多醫師和心理學者，承認性交姿勢的變換，只要彼此在心理上不生反感， 生理上又能接受，則對於交合姿勢的改變和調整，是非常有益身心而又能進戀愛情趣的。
 
因為心理學家的分析，「性美」觀念大約有三：
 
（1）種族習尚： 每個種族都有它體格上的特點，愛護這種特點的心理，很容易發展成讚美和崇尚的心理。如歐、亞、非洲的土著，他們天生臀部肥大，因此便產生出喜歡「豐臀」的習尚 。此外，中古歐洲人頌揚瘦弱身材的女子（連胸臀都要求平坦）以及中國古代風尚女子纏足等，都是「種族習尚」所導致。 至於性交姿勢亦然，每個種族所採取的方式雖說大同小異，卻都有其喜好的姿勢變 化。人類最古的一幅交合圖書，是在法國西南部的多爾頓（dordogne）發現的。它屬 於舊石器時代的一個文化期，即所謂的索留特累期（solutrian age），在這幅圖畫裏 ，交合的姿勢，並不是像龍翻的姿勢。而是男子面向上躺臥，女子則是蹲踞在上。由此 可知，性交姿勢的變化，無論中外，皆是古今有之。
 
（2）個人風趣： 每個人的體力、性格和經驗，每每影響到對「性美」的觀點。大焉者在選擇配偶， 小者則表現在性交姿勢的採用。如有的男人喜歡肉彈型女子，有的則喜歡窈窕型的淑女 。反之，女子也然。有的喜歡體育健將，有的則喜歡文弱書生。對於有些人，只須要一種姿勢，便能解決問題，但是有些人，問題就比較複雜而嚴重。
 
因為女性有二大特徵： 害羞和高潮緩慢。 害羞的女子！往往羞於要求變化交合姿勢。即使男人提出要求，也不好意思爽然配合。而女子又因高潮緩慢，對於日常例行的性交，總覺得單調不夠刺激，希望藉變換情調來提高快感，滿足性欲。而性交姿勢的變化，往往能使男女都能很快地提升性欲，達到高潮。 因為性欲的高低，很難用自己的意志力來完全控制，而是需要性的刺激方能發生。 尤其是男人陽具的勃起，和女子的性興奮，都不是因意志力量而能直接發生。它們都需要透過視覺、觸覺或其他足以使性興奮的因素加以刺激，才能達成。交合姿勢變換的本 身，即有這種刺激性興奮的特點。然而也不是所有能變換的姿勢，都能適合所有的人。
 
在各種姿勢中，有的特別適合某些人，有的人又特別喜歡某幾種姿勢。這些都當視個人興趣而定。
 
（3）受其好奇： 這是「性愛」的第三大因素。
 
溯至愛情的起初，男女雙方大多是對於對方存著幾分好奇心理。人們早在幼孩時，便會對異性身體的構造，產生好奇的心理，尤其是女孩， 看見男孩檔下的東西，竟是自己沒有的，便會產生探求原因的好奇心理。及長，男女方仍然存著對異性身體構造的好奇心理，漸漸地，這種好奇不但是在身體生理方面，也會擴漸及異性的心理上。 無論是心理的特徵，都是異性彼此相吸的基本因素。所以男人多喜歡女子的溫柔嫵媚，女子則多喜歡男人剛健豪放。
 
在生理上的互補喜悅，也是相同。女子的軀體美，足供男人低徊思慕。而男人的力，則又是女子仰慕依偎的對象。因此，異性彼此的喜好， 基礎上，是建立在凸曰身所缺少的部份，以及此種缺少所導致的部份。 婚後的夫妻，或是已有足夠性經驗的男女，對於性的好奇，尤其是列人日常生活的性交，已經毫無新奇感。那麽，像往常的那種羅曼蒂克的情調便應該消失殆盡嗎？尤其是處於現代生活的人們，早已對日常單調的生活感到厭煩，加之生活緊張，經濟壓力和生育問題的影響，在在都使人對於交合興趣銳減。男人寧願每夜留戀在麻將桌上或舞廳 ，而不願回家和「黃臉婆」同床並枕。女子則又流連在百貨公司，娛樂場所，而懶得回家共效於飛。即使夫妻都按部就班，循規蹈矩的過活。卻因不懂性愛情趣，使得男女交合，只滯留在「發洩性欲」的原始需要範圍。
 
通常，凡屬罕見的事物，人們對他總存有神秘和珍愛的好奇心。性交婆勢的變換， 必將使得原本就應該是刺激而神秘的性生活，變得更加的刺激和神秘。如此男女雙方的愛情，必然更甜蜜，篤實和美滿。
 
** 九法之七——免吮毫
 
第七曰兔吮毫
 
男正反臥宜伸腳女跨其上膝在外邊女背頭向足處席 俯頭乃內玉莖刺其琴弦女快精液流出如泉欣喜和樂動其神形女快 乃止百病不生
 
「第七種名叫兔吮毫。」
 
「男人面向上正躺，雙腳伸宜。女子跨在上面向男腳，雙膝跪在兩側。二手扶地， 頭修向下。」 「男人陽具插人陰道，並刺戟女子陰核玉蒂（琴弦）。女子快感亢進，黏液流出如泉一般，愉快欣喜，形之於色，達到高潮後停止交合動作，可使百病不生。」 這種交合姿勢下的女子，曲膝俯頭，有如玉兔吮舔細毛銀亮一般，所以稱這種姿勢為「兔晚毫」，真是維妙維肖，生興極致。一般人常見貓咪俯頭舔梳自己的絲毛。像位細心的女孩在梳理錦緞。有些曾經養過白兔的人家，常能發現可愛的小白兔更善於舔梳自己銀絲，它們的好潔與細心更不在貓仔之下。
 
采「兔吮毫」姿勢，男人除了雙手扶握女股外，並可任意撫愛女子身體各部位。動作時，必須是女子主動地上下或左右搖擺臀部，才能使陽具在陰戶內衝突鑽動。在不熟練的情形下，陽具初插入時，會因尋不著津渡，不得其門而入。此時便有賴女子用手導入，或是以陰戶去就陽具，才能順利插入。 由於陽具長而不穩，在女子上下運動、陰戶吞吐之際，很容易脫離軌道，滑出陰道 ，造成暫停場面。所以女子必須動作細心，就像小白兔一樣謹慎溫柔。否則，女子臀部上下的動作若太過於鹿魯和快速，往往會使陽具滑出或是折痛。 女子身體主動地擺晃搖曳，是兔吮毫的特徵。動作須賴雙腿和腰的力量來維持，因此腿腰比較容易疲累。女子天生就體力較弱，加以性交時多為被動，很少出力，可能會覺得更累而不採用此法。其實，只要彼此配合得當，習慣自然後便會覺得困難，尤其女子由被動改主動，在心理上，便會有奇異的感覺，彼此在動作熟練後，會更覺得刺激、 愉快。 　　大書法家，王羲之善用筆，他曾提到兔毛作筆，有云：「兔毫無優劣，管手有巧拙 。」這句話若把它用在「兔吮毫」的性交技術上，也是非常恰當的。世上男女交合，混混沌沌的不知幾凡，宜把交合當作性欲的發洩。惟有巧者，才能善用房中術，達到既能享樂又能長壽的雙重目的，真是所謂「管手有巧拙」了！
 
** 九法之八——魚接鱗
 
第八曰魚接鱗男正偃臥女跨其上兩股向前安徐向之微入便止繩授 勿深如兒含乳使女獨搖務令持久女快男退治諸結聚
 
古女說：「第八種名叫魚接鱗。」
 
「男人面向上，雙腿伸直平躺在地。女子跨坐在他前腿與跨骨間。」 「女子將臀股前移，徐徐以陰道吞夾陽具。切勿深人，淺插即止，像小兒含著乳頭 一樣。」 「男人不必有所動作，僅由女子單獨搖動，並且須持續較長的時間。待女子達到高潮後，男人便息鑼停鼓結束交合，常行此法能祛除各種疾病。」 僅由「魚接鱗」的宇義，便可體會出這種交合姿勢的韻味，是兼采旖旎和細膩二項特色。
 
女子天性即以溫柔嫵媚見長，在這種交合姿勢下，女子用溫柔的動作，主動地發動攻勢。在女子本身而言，就是反賓為主的新嘗試。由於完全是她自己主動的關係，一種控制全局，掌握場面的主宰權，會更提高她的性欲和快感。 至於男人，一反往常的地位，扮演著被動的角色。靜靜地欣賞騎跨在上的女子，品味乳波扣臀浪，粉拳和繡腿。尤其是女子的雙乳，由於動作的關係，無論上下顫動或左 右搖擺，都會使男人神魂顛倒，意亂情迷。這種乳房跳動，也是其他交合姿勢所沒有的魚接鱗，很像兔吮毫。
 
惟一的區別是後者的女子面向後，而前者的女子面向前。 男人在交合時，雙手可以任意撫弄女子雙乳，盡情品嘗詩人所形容楊貴妃般的「新剝雞頭肉」。
 
根據金賽博士的研究，女子的性感帶以陰道和乳頭為主要部位。通常撫弄其中任何一部份，都足以帶來女子根大的快感。若是雙管齊下，即一面刺激磨擦陰道， 一面撫弄乳頭，則會導致女子有相乘的快感。因此，以魚接鱗方式的交合姿勢，男人固然可以飽覽乳波臀浪，且在不費吹灰之力下，使女子得到更高的快感和滿足。
　
** 九法之九——鶴交頸
 
第九曰鶴交頸男正箕座女跨其股手抱男頸內玉莖剌麥齒中其實男抱女尻助其搖舉女自感快精液流溢女快乃止七傷自愈
 
「第九種名叫鶴交頸。
 
男人跪姿正坐雙膝打開，女子跨他騎在他身上，兩腳分置在男人左右兩側，雙手環抱男頸。」 「陽莖插入陰道的同時，摩擦女子陰唇，刺激陰核。男人雙手捧抱女臀協助她搖晃 ，上下刺插。」 「女子幾經交合後，黏液淋漓，達到高潮後便停止，如此可使七傷不治自愈。」
 
前人的智慧，彌足珍貴。形容男女燕好，不用「交尾」而用「交頸」，於此可見。 鶴交頸的姿勢中，男女雙方面對面地相互摟抱，面頰交貼、頸項交吻，其樂也融融，是別種姿勢所無法體會的。
 
據「僧尼孽海」一書的記載，元朝第十二代皇帝順帝——普供養喇嘛僧，順帝向他們學習「雙修法」，這是喇嘛教密傳房中術的九種體位性交方法。這九種體位法和 玄女所說的性交九法大同小異。二者不論是討論養生祛病的方法和目的，或是技巧上的 插入深淺，動作快慢及性交次數，除了少部份外，大都是不謀而合。甚至兩者的名稱也都大抵相同。名稱中，除了第二法的「虎步」異變為「虎行」，第八法的「魚接鱗」為「魚遊」外，其他稱呼則完全相同。
 
「洞玄子」一書所載的「卅法」！也和雙修法一樣，研究討論的都是做愛的技巧， 性交的體位和各種秘戲等等。總而言之，無論是卅法、雜修法或素女經九法，都在藉性交的方法來達到健康長壽的目的，還是在求男人女子都能祛病身、健康而長壽。 素女經九法、喇嘛僧雙修法、洞玄子卅法，雖然大體相同，卻也各有小異之處。 素女經九法，強調男人應力求鎮靜，培養氣氛，把握時機，所用的「招術」，主要 是要使女子得到快感，性交時以一男配一女為原則，並且著重插入的次數多寡。 喇嘛雙修法，顧名思義是在「雙」修，也就是要使男女雙方都獲得性交樂趣的技巧 研究。雙修法於性交時，陽具插入陰道的研究比較講究。如龍翻是八淺五深，虎行是五 淺三深、猿博是九淺六深、蟬附是十淺四深、鳳翔是六淺三深、兔吮毫是四淺一深、鶴 交頸是十淺七深；只有龜騰和魚遊沒記述。而素女經則只有龍翻（八淺三深）有這種深 淺的敍述。 此外，只修法中還介紹兩女一男的性交法，如「魚遊」的姿勢，便是一男二女的性交體位，這和素女經中九法之八的「魚接鱗」不同。它的方法是，兩位女子之一仰臥床上，另一則面對面地趴俯在她身上，像男女交合的姿勢一般。三人相互調情嬉戲，直到性興奮後，男人便仰躺下來，由二女輪流時騎在他的身上，向上攻擊，任意施為。在這種姿勢下，男人雖然不主動地出擊，可是躺著不動，冷眼看二女輪番爭搶著吞噬自己的陽具，尤其是當二女性興奮時，欲罷不能，急切想達到高潮的樣子，必然樂趣橫生，滋味無窮。 類似這種魚遊的性交體位，在隋唐時代的性古典——洞玄子中也有記載。這本書卅法中的第十五法是「鸞雙舞」，取名的意思是因為這種姿勢，像二鸞弄舞。性交時 ，二女作男女交合姿勢，面面相對，男人則趴俯在上面女子的背後，如此便能上下交互 攻擊二女的陰戶。用這種性交姿勢時，男人最好是雙膝打開，膝蓋略跪地上，如此便能 使陽具上下調度，任意交互換插兩女的陰戶。 鸞只舞和魚遊的最大不同處，便是男人易被動為主動，此時的男人更要力求鎮靜， 不可太過興奮，否則很快地便射精達到高潮，中止了性行為，美中不足，使三人都會敗興而草草收場。
  
** 強化性機能的各種體位
 
房中術除了前述的九法之外，還「七損」和「八益」之法。
 
它們的作用，都是在使陰陽調和，藉著性交技巧的修練，使得男女不但水乳交融，愛情彌堅，同時更能祛病強 身、健康長壽。
 
中醫比較著重身體內臟器官，認為強身固本，應由內而外。就拿做體操一項而言， 如果內臟不健康，肌肉和骨骼也沒法正常的發展。因為內臟的功能，即在控制全身的部 落，內臟本身不全，怎能使身體的肌肉、骨骼、膚發健康呢？
 
這種理論早在黃帝內經索問中有所記載：「心之合脈也、其榮色也；肺之合皮也、 其榮毛也；肝之合筋也，其榮爪也；脾之合肉也，其榮曆也，腎之台骨也，其榮發也… …。」心臟健全，必使血脈暢通，人的血氣自然紅潤；肺臟健全，必使皮膚潤滑，毛髮自然柔亮；肝臟健全，必使筋肌強健，指爪自然健康；脾臟健全，必使肌肉力活，口唇自然鮮豔。
 
八益法，便是根據這項理論，應用各種性交體位元，強化筋肌、關節、內臟、血行、 脈絡和神經等機能。八益法除了積極地強化內臟，健全器官組織外，也能在男女行使性交時，去除身體疲倦和精神困頓。 最值得注意的是，在這八法中，性交體位的變化很大，尤其加入了許多側臥的姿勢 。這種側位法，是前述九法中所不曾提到的。由此，我們更能看出素女經的變化多端， 考慮周詳。 八益法中女性的姿勢，多為膝部的彎曲、張開、靠緊，腰部的扭轉和其他各部位的 充分運動。其目的都在強化內臟的功能，尤其是強化腎臟的功能、使骨盤內血行良好、 強健腹部筋肉、健全子宮，並且能使女子保持良好的性欲機能。 總而言之，八益的作用乃在強化內臟功能，並使性機能強固，使男女不但能充分享 受性樂，而且能延年益壽、永保健康。 八益之一－－固精 素女曰陰陽有八損八益一益曰固精令女惻臥張股男側臥其中行二 九數數畢止令男固精又治女子漏血曰再行十五日愈 素女說：「男女性交能損身、也能益身，苦行之不得法便會戕害身心。令列下七損 八益之法，作為治療規範。」 「第一益是固精」 「女子側臥，張開兩腿，上方腿可略曲。男人與她面對面側臥，陽具插入陰道連續十八次，數畢就停止。如此男人可因精，並使精液濃厚，女子能治月經過多症。」 「按照此法，每日作兩次，連作十五天，可以治癒漏血及散精之病。」
 
素女經中，在前述的九法和即將介紹的七種七損八益法中，有許多性交姿勢的介紹性交運動，雖然只是男人性器官——陽具，和女子性器具——陰道等的摩擦運動。
 
看起來動作很單純，然而男女的姿勢卻有很多種，細分起來，不下百餘種。粗略的分析 ，約有八種基本姿勢。現在且依男女方向和主被動關係來列述：
 
對向位（面對面） （1）
 
女子面上仰躺位…………男人主動 （2）
 
女子側臥位………………男人主動 （3）
 
男人面上仰躺位…………女子主動 （4）
 
男人坐位…………………女子主動 （5）
 
男女皆側臥位……………男人主動 背向位（女背向男）
 
（1）女子面下趴俯位…………男人主動 （2）
 
男人面上仰躺位…………女子主動 （3）
 
男人坐位…………………女子主動 （4）
 
男女皆側臥………………男人主動
 
以上羅列九種性交主要姿勢，可以說是百餘種性交姿勢的基本姿勢。其他各種變化雖多，但是總是些小動作的不同而已。比如在對向位第一種裏，女子因姿勢的小改變， 便又衍生出許多不同的姿勢和名稱。如女子曲一腿、曲一腿，或二腿皆舉……等等不一而足。
　
** 八益之二－－安氣
 
二益曰安氣令女正臥高枕伸張兩股男跪其股間剌之行三九數數畢 止令人氣和又治女門寒日三行二十日愈
 
「第二益是安氣。」
 
「女子仰面正躺，頭墊高枕。雙腿打開平放兩側，男人雙膝及雙掌撐地，跪在女子雙腿中間，雙掌分置女臂兩側。」 「陽具插入陰道計二十七次，數畢停止。此法可使人心靜平和，氣脈爽暢，也能醫治女子陰門寒冷症。」 「上述方法，必須每日三次，連續作二十天，即可收效。」 性交的技術，也是藝術。比較粗心，魯莽的男人，「一根蠻秤十八兩」，提槍上馬 ，兩三下就清潔溜溜。這種只顧自己洩欲而不顧女子反應的性交，是不智且錯誤的。 性交，顧名思義是兩性交媾。必須雙方偷悅，而不是單向的洩欲。在心理上，彼此 也都以使對方滿足愉快為目的。 交媾姿勢儘管是五花八門，總不外乎是其中一方採取主動，對方細心來配合。而主動權的歸屬，完全要依性交姿勢作為取捨。大致說來，男女是各自一半。一般而言，男人採取主動權的機會較多，且多為平躺位。女子掌握主動權的，多是坐位姿勢。在行坐位性交時，室內溫度又必須適度，不可寒冷。同時在坐位時，比較不容易達到高潮，這又是因性器官構造所致。 古時，有許多皇帝很貪懶，所以喜歡自己躺在床上，由女子跨騎在他身上，面對面或是背對著進行性交。在這種姿勢下，可以飽覽女子雙乳因振動而顫抖，形成別具風味 的「乳波臀浪」。 許多女子以性交應該由男人主動才對，這是錯誤的觀念，正如同很多女子誤認性交 是羞恥一般。其實「性」與「食」一家，必須由主婦「主中饋」，求其變化才對。在性 交行為中，女子也是要配合男人行動的。而男人也希望女子能夠有時主動，從中獲得新鮮刺激。並不會因為女子的主動而誤認為對方太男性化。當然，像在新婚之夜，是宜由新娘主動的，否則准會使新郎抱頭鼠竄。
 
** 八益之三－－利藏
 
三益曰利藏令女人側臥屈其兩股男橫臥卻剌之行四九數數畢止令 人氣和又治女門寒日四行廿日愈
 
「八益之三是利藏。」 「女子側臥，彎曲兩腿，使臀股突出暴露。」「男人也側臥，由背後攻擊。陽具插入三十六次後即停止。」 「此法可使男人心平氣和，也能治癒女子的冷感症。」 「應用本法，要一天行四次，不洩為原則，連續作二十日，即可治好上述病症。
 
** 八益之四——強骨
 
四益曰強骨令女側臥屈左膝伸其右股男伏剌之行五九數數畢止令人開節調和又治女閉血日五行十日愈
 
「強骨是八益中的第四益法。」「女子側臥，曲卷左膝向胸，右腿伸直。」 「男人趴伏在她身上，陽具插入陰道作以正面攻擊側面的姿勢。」 「陽具刺插四十五次即停止，每日五次，連續十天。如此，便能使男女關節活絡， 身輕體快，又能治女子月經久閉症。」
 
** 八益之五——調脈
 
五益曰調脈令女惻臥屈其中右膝伸其左股男處地剌之行六九數數 畢上令人脈通利又治女門辟日六行二十日愈
 
「八益中的第五益是調脈。」
 
「女子側臥向右，彎曲右膝向胸，左腿伸直。」「男人趴伏在女子身上，以正面攻擊女子側面。」 「陽具插人陰道五十四次，每日六次，連續二十日。」「用這種方法可使男人氣脈通暢，又能治癒女性陰道的膣痙攣症。」 這種姿勢，女子的側臥與前法由卷左腿，本法則彎曲右腿。
 
** 八益之六——蓄血
 
六益曰蓄血男正偃臥令女戴尻跪其上極內之令女行七九數數畢止 令人力強又治女子月經不利日七行十日愈
 
「蓄血是八益之六。」
 
「男人正面向上仰躺，采被動姿勢。」「女子跨跪在男人胯上，雙膝跪在男臀兩側，陰戶正對陽具。」 「女子使陰戶夾湊陽具，讓陽具深深插入六十三次，然後停止。」 「此法可使男人氣強力壯，又能使女子的月經不順症痊癒。」 「本法需每日行七次，連續十天即可見效。」
 
** 八益之七——益液
 
七益曰血液令女人正伏舉俊男上往行八九數數畢止令人骨填
 
「第七益是益液。」
 
「這種性交姿勢中，女子俯趴向下，腹胯下墊高枕，使屁股高聳，陰戶凸出，以便陽具插人。」 「男人以雙掌及雙膝撐地，雙腳跨在女腿兩側，陽具插入陰戶，抽送七十二次後停止。」 「益液法，可使性交者骨骼質地堅硬。」 素女經原文雖然未載此法每日應交接幾次，但是照按前面六法，和最後的第八法看 來，益液似乎是日行八次，連續十天，較為正確。
 
兩點、正是素女經的要求，不如此則不能達到健康長壽的目的，兩相權衡，取其輕者以行之。
 
根據中日的說法，骨與骨髓都跟腎有關係，而腎被認是司掌生殖以及人體的生長發育，衰老等生命過程的藏精器官。所以，八益可使男性強精，調整身體，並且是可以治病的體位。
 
現代的日本人，有不少人從嬰兒期起到老年期止，由於紫外線的不足，所以，骨骼軟弱，腰部與關節發生了病痛。 他們年輕人的一輩雖然身材高大，但筋骨不見得很強，由於閱讀不少性生活方面的書，也許懂得不少性交體位的知識，但在實技方面，卻沒有持續力，甚至有很多人性無能。
 
現代日本人曾以立體前屈及上體反曲，當做測定身體柔軟性的方法，結果男性在二十歲前後，女性則在此年歲前就達到頂峰，這是早老的現象。 如學會八益，則可強健筋骨，關節圓滑，或強化內臟，結果自然疾病會減少，持續力增強，性無能也可以被治癒了。
 
不過，體位方面也有實用與不實用兩種，這就是指很實用與最佳體位而說。
 
在如何增強精方面，有幾種方法，例如用手掌在肚臍周圍，腰椎第二節附近及其下的仙骨之處按摩，並用深呼吸的腹壓法，或縮肛門忍住便意的姿勢，而行左右開弓方式的體操，這些都是強化腎臟機能的方法。
 
前面雖曾說及要按摩或腹壓法，加強精力，這是指「八段錦坐功」。武當拳法是中林拳法的分支，施展武當拳法前，必須先做預備體操——八段錦的獨自拳式，這是下半 身不動，而僅用上體與雙手動作的一種馬上武術。（拙著「八段錦健康法」附有詳細圖 解。） 馳名東北的日本馬賊頭子小日向白郎，曾控制全東北馬賊的千山道教的寺廟中 ，從預備體操學起，練就全身一擊必殺的猛烈鬥技。 八益的體位是強健法之一，這是從東洋醫學中想出來的秘訣。
 
有一位名叫香蛛的妓女，她從長久的經驗中獲悉若干實用的性交體位，但只推薦其中的。 香妹從老鴇處學到數十種體位，結果她認為下述兩種最好：「關於體位方面，老鴇雖然教我幾十種，但我想推薦兩種： （1）女性仰臥於床上，男性夥壓在上面，女性抬高兩腳纏住男性的腰部，互相用兩手緊抱，使身體密著為一體，這雖是常用的舊姿勢，但也不可等閒視之。 （2）女性臥床邊，男性站在床下，並握著女人雙腳，好像採取壓著兩柄一輪車的姿勢 。這樣一來，女性就無須擔心男性會從上面壓下，男人也不必彎膝駝背，一直一橫，一臥一立，一日罷自由行動，而且舒服無此，尤其夏天涼快，這種體位最適當。 至於其他體位，雖也會被我認為好奇而一一試用過，但全部不實用，所以我不採用 。」不過，體位的選用也要視體格如何而定，當然，喜好問題也有個人的差異。 在這兩種體位，可能身為妓女，不得不講究效率而選定第一種，這姿勢確能使男女軀體密著一體，而且下部的動作也能配合得好，彼此皆大歡喜，所以不愧為一種實用的體位
  
醫治性衰落的七種體位
 
本章的七損是與八益成對的，因身體不適而勉強做愛所生的疾症，都可用性交體位當作治療方法上？些在本章裏說明很清楚。 例如性的衰弱、早洩、無能、萎縮、過勞時性交、或因飲酒、內臟傷害，房事過多而引起的症狀等，都是頗使現代人苦惱的問題。
 
素女經視此為身心不平的問題，為了要提倡正常的性生活，那麽，她就以前述的幾種體位當做恢復機能的方法。 同時，加上上述的九法與八益時，素女經再求變化，苦心積慮的想出二十四種體位元她說的目標，含有強壯、長壽和快樂三項益處，從頭到尾都很重視自力更生，這無異給現代人打了一針強心劑。
 
現代人由於體力衰退，再加上緊張的壓力，以及穿著薄而透明的褲子、短衫 使用性交保險套等，結果使得性能力日漸低落。 由於很多現代人精神疲勞，以致得到性無能症，最後使性生活有如窮途末路 ，這才出現在適合身體與情調的性交體位裏，如何使對方滿足的方法。
 
** 七損之一－－絕氣
 
素女曰一損謂絕氣絕氣者心意不欲而強用之則汗洩氣少令心熱目 冥冥治之法令女正臥男擔其兩股深案之令女自搖女精出上男勿得 快日九行十日愈大大
 
素女說：「一損叫做絕氣，即精氣枯竭之意。性愛動機不強而勉強交合，則會滿身大汗，減少氣力，興奮而睜不開眼睛。若要醫治此病的體位，是讓女性正面仰臥，男性 則抬著她的雙腿，而後括人之，使女性自己擺動，女性津液流出，即行停止，男以不洩 為原則。若用此法，日行九次，則十日可洽愈此疾。」 精氣枯涸是指喪失「氣」的意思，國人以為「氣」是維持生命最要緊的東西。沒有 節制的性生活，會招致身心極不平衡的結果。 關於治癒此症的體位，乃是九法中之猿博型，這主要由女人主動。誠如上述 國視為屈曲位為一種正常位。 此項活動可以避免因密著度極高的體位所引發的興奮持續與疲勞，這對於男 快樂的表技，它與猿博型不同，但卻很強調女人主動這一點。 如因房事過多而減弱氣勢，以致患上眼睛睜不開的神經衰弱症，那就要變化 歡的體位，提高密著度，以讓女人採取主動。
 
** 七損之二——溢精
 
二損謂溢精者心意貪愛陰陽未合而用之精中道溢又醉飽而交接喘 息氣亂則傷肺令人亥逆上氣消渴喜怒或悲慘慘口乾身熱而難久立治之法令女人正臥屈其兩膝使男男淺剌內玉莖寸半令女子自搖女精出上男勿得快日九行十日愈
 
「二損叫做溢精，所謂溢精者，是指欲望在燃燒，氣勢在膨脹，陰陽尚未調和，即父合，結果中途洩精。 而且，酒醉後性交，會喘息不止，呼吸淩亂，傷及肺部，如呈現咳嗽、火眼、消渴 喉頭發乾，小便不洩之症（請病時，喜怒哀樂的情緒也會更嚴重，口頭發乾，身體發 熱，長期以後，還會變成性無能。」 「要治此症的體位，即女人正面仰臥，兩膝彎曲，並以雙腿交纏著男性，男性則以 陽具插進一寸半左右，使女性腰部擺動，女性的津液流出時，即行停止，以不洩為原則 。但用此方式，一天性交九次，則十日就可治癒上述諸症。」 溢精是在一損的絕氣之肉體症狀，與早洩症狀之下，房事過多，醉後性交，結果使得呼吸系統不調和，肺部傷痛，甚至發生長期的性無能症。 至於如何洽療這些疾症的體位問題，乃是以舒服的對向位元與淺進方式，期以防止早洩，並要讓女性掌主導性，減少男人的運動量。 因為行房需要相當於呼吸及迴圈器等運動量的精力，所以，一定要研究性交體位， 使得忍氣與溢精不要惡劣迴圈。酒醉後做愛，會使身心失去平衡，變成長期的性無能， 若用上述體位行房事，則十日可治癒以上諸疾。這對於女性來說，她掌握主導權，此種 體位可行腹筋的強化體操，這對醫治不感症很有效。同時，一面享受性的樂趣，一面治病，這可以說是中國人智慧活用的實例。
 
** 七損之三——奪脈
 
三損謂奪脈奪者陰不堅而強用之中道強為精氣竭及飽食訖交接傷脾令人食不化陰痿無精治之法令女人正臥以腳鉤男子尻男則處席 內之令女自搖精出止男勿快日九行十日愈
 
「三損稱為奪脈（全身脈搏不順之之狀）。」 所謂奪脈，乃是陽具不硬，而勉強用之，結果中途洩精，使得精力枯竭。吃飽行房事，會傷及脾臟，一旦消化不良，則陽具萎縮，精氣喪失。醫治此症的體位，先要使女性採取正面仰臥，並用雙腳纏住男性屁股的姿勢。男性用雙手抵在床上支垂著身體，陽具向內插人，使女性運動起來。女性滿足後，即行停止，男性雖沒有達到 快感，但用此種位式一日行九次時，十天可以洽愈上述諸症。」 消化不良系由錯誤的性生活而引起的。 脾臟在中醫裏是消化吸收器官，因溢精症而使喉嚨乾竭，或因奪脈症而傷及脾臟， 以致引起消化不良症時，這些都是因為消化器系統的不協調所使然的。 中國有句俗話說：「不要吃太飽，可以得長壽。意指胖一寸，會減三年壽命。 力不從心，也是脾傷的證據。
 
由於消化不良而引起便秘，也是傷脾的紅色信號，這些都會呈露性衰弱及老化的現象。 早上空腹飲水一杯，對於疏通大小便，極有效果，因為便秘是性生活的大敵，這一點務必要小心注意才好，對於脾臟有益的是大豆和牛肉等食品，生藥方面則以茯苓最有名。
 
** 觸而不洩的妙用
 
黃帝曰願閑動而不施其效何如素女曰一動不寫則氣力強再動不寫　耳目聰明三動不寫病消亡四動不寫神威安五動不寫血脈充長、六動 不寫腰背強七動不寫尻股益力八動不寫身體生光九動不寫壽命未 央十動下寫通於神明
 
黃帝問：「雖想要洩精，但稍加抑制即可不洩的話，那會有什麽好處呢？希望你詳細告訴我。」
 
素女回答說：
 
「初次想要洩出，但稍加抑制而洩不出來時，氣力就會飽滿。
 
第二次想要洩精，稍加抑制而洩二出來時，耳目會很清楚。
 
第三次也是如此，則百病也會消除。
 
第四次也會如此，則五臟也會平安。
 
第五次也是如此，血脈會充實而且舒暢。
 
第六次也是如此，腰背部都會健壯。
 
第七次也是如此，屁股和大腿會愈有力氣。
 
第八次也是如此，身體會發光動人。
 
第九次也是如此，自然會延長壽命。
 
第十次也是如此，則通往神仙的大門會大開。」
 
胎息法是中國古代的養生術之一，吐息少於吸氣，就會使「氣」蓄積體內，這是還老返童的秘訣。它與房中術有共同之處。生命的泉源就是氣寶精受氣乃是養生術之 一，也是房中術的秘訣。 中國古代的醫學認為血是氣之形態化的東西，而血與精液的本態原是同樣東西。因 此，他們以為洩精是逼出氣血，它有損於壽命的延長。 同時，男性藉性交而吸取女人之氣，為了要吸取很多女人之氣，所以要盡可能延長合交的時間，因此，「觸而不洩」之法，乃成了房中術的秘訣。
 
那麽，不洩精到底有什麽樂趣的呢？！這是采女的問題，但彭祖卻認為靠自製力，才能得到快樂。黃帝又問：「不讓精液洩出來的話，那又有什麽好處的呢？」素女列出十項好處，這才是強健身心與延長壽命之道。
 
老子曾說：「知足為富。」禮記上也說要「量入為出」，（這是財政健全的根本） 。國無九年之蓄叫不足。無六年之蓄叫急，無三年之蓄的國家，則不是國家。經營國家 時一定要準備不時的災害，若無三年之奮的國家，不能說是國家。」康得也說：「幼小 時不教以欲者，真是不幸」 「觸而不洩」，不但是快感而已，若能鍛鏈自製力，則能有十項好處，這是生理的 健康法，其目的在於蓄積精力，加強賀爾蒙的活動，並且鍛鏈抵抗力與持續力，它以肉體與精神的結合為目的，這是根據中醫原理來的。
 
「觸而不洩」，是根據呼吸法，而自由控制持續力的方法。 中國的呼吸法裏，有一種定息的基準，一呼吸為四脈拍，這是要使呼吸與身心安定的緣故。 在防止老衰，或醫治高血壓的情況裏，要慢慢地使呼吸或脈博舒暢，用深長而細微 的呼吸使身心調適，這樣可以調整血壓。或者，吸收許多酵素，長時間刺激心臟與肺部 活動，期能保持青春。
 
中國古代的養生法，是同時應用食餌療法和體操等。美國的h． 庫巴博士也提倡過，後來又曾在日本東京大學流行一陣時候，由此可見中國的養生法是很科學的。 做幾次深呼吸，會增加血液的酸素，經過長時間後，就能聯為一氣。若在地上鍛煉這種呼吸法，不多做運動時，那麽通常只做一分鐘左右的呼吸，就能收到二分鐘的呼吸效果，肺部的持續力也加倍增強。 另一種防止衰老的呼吸法也跟前面的要領一樣，吐息時腹部膨脹，吸氣時下腹部用力收縮，這就是「觸而不洩」的呼吸法。呵呵大笑與哭泣時呼吸狀態同，只是不用力， 而慢條斯理做著就行。
 
莊子呼吸法的要領：「凡此道中人的呼吸，好像深到腳底，凡人的呼吸淺到喉頭。但不隨便濫用，所以用十九年依然很新。」 印度的瑜伽法也用背梁做呼吸，這好像用腳呼吸一樣的要領，不舉肩，只是擴胸吸氣，先用勁兒，把氣收人下腹，下腹就是下丹田。 “玉房指要”所說的觸而不洩：「用力壓著陰溝子，吐出一口長而大的氣，同時不斷地咬緊牙齒，不斷作息。」「很敏捷地治頭注目，一面上下左右巡視，一面收縮下腹部 作息之後」。「用腹式呼吸會使腹部膨脹，集中精神之後，再收縮腹部」，「仰頭作息 之後，一面吐口大氣，一面睜眼四看，收縮腹部」，「吸進一口大氣，咬緊牙根做息， 耳中感到有風吹的聲音時，則應收縮腹部」。 後面兩項是加強視力與治療不聾的方法。 以上都用腹壓法，使呼吸的長度變化，興奮的情緒安靜，這是因呼吸短促與興奮很強的緣故。 用眼睛左右張望，為的是要看看或想想外面的事物，期能轉換氣氛，讓外面的景物使性中樞的興奮能安靜，只要陽具之力一松，則洩管的閉鎖筋括約筋之板機就會愈加強硬。 呼吸法也以為讀經，能改變性情，因為尊心讀經會使呼吸深長。
 
日本有一種宗教，每天早上六時半集合信徒，並要他們讀經三十分鐘。信徒們每天一面讀經，一面進行呼吸法，再飲一杯清水，這樣能使大小便舒通。深長的呼吸會使意識集中，精神安定，甚至忘卻煩惱。 俗語說：「呼吸很對勁。」這是說呼吸很均勻時，心情舒暢，說話也偷快，所以自然會笑出音來，歡笑也是能使精神安定的呼吸法之一。因此，信徒們的心情愈來鎮定， 身心也很平。若每天能勤練不息，則可以保持生活的節律，以及長生不老。
 
在印度的公僕貴族勤練一種類似「千金方」的壓迫法。他們用手強壓尿道的基部附近，不過，印度人認為練習這種方法時，即使洩精也不會外流，反而會返回原處。 有一種抑制法的特徵是：多行交接，觸而不洩，要常常更換女人，而且還要以年輕女人物件。 「千金方」裏說：「人類在三十歲前血氣旺盛，恣情縱欲。但過了三十歲時，突然會覺得氣力衰退。當此之時，不禁會懷疑自己是否在生病？假如不加治療，最後會變成無可救藥的結果。因此，年屆三十歲時，必須要勤練房中術才好。關於房中術的秘訣， 雖然人人都容易學會，但都不去實行。這個方法就是：一晚接觸十個女性，但都不流精液。如此而已，然後常吃補藥，一年下來，自然氣力百倍，頭腦清醒，每天都有新創意 ，這就是千金方之術。」
 
多方接觸女人，而且還要時常變換物件，尤要以年輕異性為主，這是人類的本能， 大家對於性也抱這種想法。不過這種舊觀念在現時代是行不通的。根據金賽博士的報告 ，婚後女人也有這種欲望。只是追求快樂，則容易損壞身體。總之，一定要控制洩精才 對，這是中國性學古典的觀點。該書以為男人年屆三十歲，氣力會衰退，故要勤練房中術，這真是一種卓見。 在性能力很衰退的狀態下，醫學上有句巧妙的名言，即二十年代的男人，是以量多量少決定勝負。三十年代著，則以質來決定勝負。至於四十年代的男人，系以間隔為泱定勝負的因素。 反之，也有句巧妙的俗語說：「三十寡婦不可通。」女性的生理與男性是互相矛盾的。天也不長眉發。
 
在中國古書裏，曾經記載一位元和尚，他利用「內觀法」治癒肺結核。其實，這個方法是利用坐禪與深呼吸的一種呼吸靜坐法。 漢朝有本《株林野史》，它是把春秋時代一位名叫夏姬的婦人寫成小說。夏姬年屆十五歲時，曾在夢中學到「吸精導氣」和「素女接戰術」之類的還老返童法。它的要訣是不斷吸取男人精氣，以保持年輕，當她被陳靈公摟在懷中時，就是使用「內視法」的房中術秘訣。 生產後不到三到，依然能恢復處女的姿態。她用這種奇異的方法，使得靈公非常吃驚，這准是在內視法中所說的秘訣。這是暗示以調息法，而鍛煉下部括約筋。總之，這是與「觸而不洩」一樣屬於女性方面的秘法。 此外，根據歌川大雅氏的說法，喇嘛教的性行法，也是為了要達到靈肉一致的理想境界，從性器附近沿著脊骨上升，一直到達蓋頂的深處。在動作過程中，男女雙方都要聚精會神於非常單純而超差別的境界裏，以禪定的觀念，要男女雙方都不洩出精氣，期能享受最佳的樂趣，這是他們的房中秘訣。 在「觸而不洩」法裏，有各種誤解，其中的一個反論是抑制不洩，對身體有害處。 不過，抑制的著眼點，在於男女交合，性之節制和持續力的鍛煉動方面。 雖然這一點正在尋求實證，但下面所要說的洩精次數，素女經並沒有絕對主張不洩。
 
** 洞玄子性技三十種
 
本章為著名的洞玄子態位論，洞玄子是唐代道家張鼎之號，三十法概括婚姻生活中最基本的性交姿式，其中有些是與前面所述的九法有所重覆，不過九法大抵以養生為目的，而三十法卻是以玩樂為主。
 
洞玄子說：「交接的姿勢大約不出三十種，其中有前後屈伸，上下俯仰等等，雖然大體相同，卻也各有小異之處。所以，此三十法可以說已網羅一切方法，絲毫沒有遺漏 的。」
 
（1）敘綢繆：「兩性親熱的擁抱在一起的情狀。」
 
（2）申繾綣：「男女兩性將手緊密的握住對方的情狀。」
 
（3）曝鰓魚：「形容女子陰阜興奮如魚將鰓暴露於空氣中而掙扎的樣子。」
 
（4）麒麟角：「形容陰莖興奮像麒麟之角。」
 
以上（1）至（4）型是屬於性行為的前奏階段，並不是各別獨立，而是在一連串列為中， 同時在的。
 
（5）蠶纏綿：「女子仰面正躺，雙臂抱住男子的頸部，雙腿交叉在男子背後，男人以兩手抱位女頸，跪伏在女子雙腿中間，插入陽具。］
 
（6）龍宛轉：「女子仰臥，彎曲兩腿，並高舉，男人跪伏在女子雙腿中間，以左手往前推女雙腿，使女子足趾能彎到乳房後面，然後插人陽具。」
 
（7）魚比目：「男女並行橫臥，女子一隻腿放在男身上，面對面介面吮舌。男人伸直雙腿，以手拉起女上腿，將陽具插人。」 　
（8）燕同心：「女子仰面正躺，兩腿伸直，分開。男人趴伏在女腹上，兩手並抱女頸 ，女子用兩手抱男腰部，然後送人陽具。」
 
（9）翡翠交：「女子仰躺，彎曲雙腿，男人蹲坐女股後兩腿分開，並夾在女子雙腿中間，以雙手抱住女腰，以便陽具攻擊陰蒂一帶。」
 
（10）鴛鴦合：「女子側臥，舉起兩腿，一隻置於男人腿上，男人從女背後，騎在女下腿上，一腳半跪，一腳踏前，插人陽具。」
 
（11）空翻蝶：「男人仰躺，兩腿伸直分開，女子面對面坐男人身上，並用手按住男膝蓋處，然後送人陽具。」
 
（12）背飛梟：「男人仰躺，兩腿伸直分開，女子背向男人並坐在男身上，頭放低，以便插人陽具。」
 
（13）偃蓋松：「女子仰臥，雙腿舉高交叉，男人雙手抱女腰，女亦雙手抱男腰，然後插入陽具。」
 
（14）臨壇竹：「男女相向站立，嘴對嘴相擁抱，並將陽具深深插入。」
 
（15）鸞雙舞：「男女兩人中，」人仰躺，一人伏臥，兩人相向，插入陽具。」
 
（16）鳳將雛：「女子個子大而肥胖的，用一少年來交接，好像女鳳凰在乳哺雛鳥的情狀。」
 
（17）海鷗翔：「女子仰躺床上，男人站在床邊，擔起女腿，將陽具插入。」
 
（18）野馬躍：「女子仰躺，雙腿架在男人左右肩上，然後深深插人陽具。」
 
（19）驥騁足：「女子仰躺，男人蹲坐女股後，左手套住女頸，右手扶助女腿，將陽具插人。」
 
（20）馬搖蹄：「女子仰躺，男人架起女腿，一隻放肩上，一隻由女子以手拉住，以便將陽具深深插入。」
 
（21）白虎騰：「女子伸躺，兩腿伸開，男人蹲坐在股內，兩腿彎曲，兩手抱女頸，並將陽具插入。」
 
（22）玄蟬附：「女子伏臥，兩腿分開，男人趴伏在女腿中間，雙手抱住女頸，從背後括人陽具。」
 
（23）山羊對樹：「男人蹲坐，女人背向男人，並坐在男身上，把頭部放低，望著陽具的插人，然後男人雙手緊抱腰，加速抽送。」
 
（24） 雞臨場：「男人坐在床沿，使一少女坐在身上，插人陽具，另使一少女從男身後撫弄，以增加快感。」
 
（25）丹穴鳳遊：「女子仰躺，以手舉起雙腿，男人跪在女股後，用手支持身體！然後把陽具插人。」
 
（26）玄溟鵬翥：「女子仰躺，男將女子雙腿放置在左右上膊都，然後伸手下抱女腰， 插進陽具。
 
（27）吟猿抱樹：「男人分開雙腿而坐，女子坐在男腿上，雙手抱住男人，男人一隻手勾住女臀部，一面插進陽具。」
 
（28）貓鼠同穴：「男人仰躺，分開雙腿，女俯伏在男身上，深深插進陽具。然後男子改變姿式，趴伏在女子背上，背後攻擊。」
 
（29）三春驢：「女子雙手按在床上，取爬行姿勢，男人站在女股後，雙手抱位女腰， 然後插入陽具。」
 
（30）三秋狗：「男女均取背向的姿勢，雙手放在床上，臂部互相緊貼，然後男人儘量把頭放低，用手將陽具送入。」
 
大凡婚後的夫妻，或是已有足夠性經驗的男女，對於性的好奇，已經毫無新鮮感。 尤其是處於現代生活的人們，早已對日常單調的生活感到厭煩，加上生活緊張，經濟壓力和生育問題的影響，處處都使人們對於性生活的樂趣銳減。即使大都按部就班，循規蹈矩的過日子，卻因不懂性愛情趣，使得性生活，只滯留在「發洩性欲」的階段。 假若男人能夠主動地交換交合姿勢，雙方互相配合，體驗其中的變化樂趣，會使性生活脫離「發洩性欲」的原始需要範圍，除非生理上的障礙，性交姿勢的變換，對於男女雙方，無論是生理或心理，都是絕對有益而無害的。
 
** 性交基本姿式
 
（一）男上位
 
（1）正常位女性仰臥，兩腿稍微彎曲分開，男性伏臥其上，兩膝與兩財均放床上，以支持身體 。雙腿放在女性雙腿中間。 男上位是男人握有主動權的姿式。因此，這個姿式能滿足男性的自尊心與優越感； 而女性則可以獲得愛撫與受到保護的滿足感。 但采此姿式時，由於陰道角度與陰莖的角度不一致，所以在插人性器時，有時會往 肛門滑脫，如果女性用枕頭將腰墊高，同時男性將陰莖稍微往上推進，即能順利插入。 正常位可以說是一切交姿式的基本型。以此姿式為基礎，可以變成許多姿式。
 
因此，由於身體情況差異或其他原因不適用正常位時，可以適宜改變其他姿式。但無論採取那一種姿式，通常達到性高潮時，男女都想緊抱在一起，做為性行的結果，正常位可以說是最自然的一種姿式。但這種姿式的缺點在於它的接觸感度並非頂好，因此，擁有主動權的男性，需要用一隻手勾拉女性的腰部，另外一隻手用愛撫。又陰重短小，勃起不全、腹部肥胖，或女性在懷孕時，這個 姿式較不適合。
 
（2）伸展位
 
照正常位元的順序結合，然後女性輕輕地把雙腿合攏再伸直， 男性雙腿夾住女性雙腿。 由於女性的大腿與外邊的男性大腿由外邊給予適度壓迫，陰道口小緊，夾住陰莖結果，陰莖所受刺激很大，增加男性快感， 又由於陰莖背面磨刺激陰蒂，或因男性的沁骨壓迫增大，所以女性性感也隨之增強。 但因為在伸展位，女性把雙腿伸直，所以結合度比正常姿式差，因此這種姿式不適合於陰道短淺或子宮發育不全的女性採用。 由於陰道口變窄，因此陰莖龜頭受到陰道後壁的強烈抵抗，所以這種姿式對於精h減退而勃起力不全者，大有幫助。因結合度淺，所以在性交運動時，陰莖容易往會陰或肛門滑出，精力減退的男性， 陰童一日一滑出，很快便萎縮，以致不能性交。又此姿式，因女性須承受男性體重，因此在懷孕時，與正常位一樣，最好避免採用 。 在伸展位，通常男性兩腿夾住女性雙腿，有時可以把雙腿並行放在女性腿上。由於 男性未用膝蓋部支援身體，女性需要承受男性體重，如果男性過度肥胖，對女性是一種 負擔。
 
（3）高腰型
 
女性仰臥，男人位。與伸展位一樣，是正常位的一種變型。其特色：女性把腰部墊高，男性的姿式亦應相對配合。 女性用腰枕，或仰臥，以男性上腿為台，稍微把腰部拉起。在此場合，男性以其上 腿承受女性腰部，把雙臂放在腰下，用以支持即可。 臥床時，女性腰部可放在床邊，雙腿下垂，稍微分開。男性配合床高亦即配合女性 腰部高度，採取站立位或膝位（半跪），位在女性雙腿中間。 高腰位因男性半身挺直，所以陰莖水平進人，無男性膝部之障礙，結合度較深。 又採取這個姿式時，陰莖沿陰道前壁進人，故在初夜采此姿式時，可減少疼痛到最低限度。 新婚後疼痛尚未消除者，或由於首次性交的刺激，陰道前庭發炎時，這種姿式能緩 和疼痛或減輕發炎部位的負擔。 只是因為男性上半身挺直，故陰蒂刺激甚少，接觸感度不甚理想。 對女性來說，高腰位是一種吃力的姿勢，故對於非健壯的女性，其負擔過重。因此 ，不適直於疲勞時病弱時採用，又會使女性的腹肌緊張，故懷孕時不宜採用。 由於這種姿式帶輕捷特技性質，故做為愛情的表示甚適宜，便會感到挑撥性興奮。
 
（4）屈曲位
 
女性仰臥，兩腿彎曲，約成一百三十五度，把腿貼在胸部上。男性與正常位時一樣，伏臥其上，把手臂放宜或財彎曲，上半身挺直，或跪坐均可。 采屈曲位時，陰莖與陰道口差不多成直角，所以結合度深，精液直接向子官口直射 ，因容易貯存於子宮口，容易懷孕。 採取屈曲位時，男性能自由運動，可飽覽女性胴體，感受刺激性興奮，但因不能磨 擦陰蒂，故女性不一定很舒適。這種姿式對於初夜或陰道短淺的女性不宜採用。
 
（二）女上位
 
（1）反位 反位與正常位相反。男性仰臥，雙腿分開，女性跪下，伏臥其間。 與正常位一樣，陰道軸方向與陰莖之進人方向不一致，因此插入有時陰莖會向肛門 方向滑出，故男性需要把膝部彎曲，挺高腰部，這樣才能增強對陰蒂的刺激。 採取這種姿式時，由於女性伏臥，乳房下垂，容易撫弄。 據說反位比正常位更容易使女性達到高潮。因女性上半身儘量挺直，子宮陰道部與陰莖龜頭直接衝刺抵觸，刺激增強之故。所以經常採用正常位者，有時因改用反位，而覺得鷳無比，另有一種滋味。 由於男女位置更換，主動權則轉移給女性。 在此婆式，女性的運動是，與其上下運動，不如用直線的前後運動的要領行之，較 為適宜。即沿著男性大腿或腹壁平行，以直線的、平面的擦動，增強男性性器的刺激， 或對本身的刺激。
 
（2）騎乘位
 
騎乘位指男性仰臥，女性騎乘其上的婆式。 采此姿式時，陰道軸與陰道對向，所以容易結合，而結合時，陰道口向下，射精後 精液容易往下流出，因此進人子宮口的精子少，雖然不能期待完全的避孕，但在某程度 能收到避孕效果。 騎乘位能使女性獲得新鮮的感覺，同時旋轉運動自如，能獲得仰臥時所不能獲得的 滿足感。 如果女性不把膝部放在上，採取用雙腿夾住男性身體的蹲伏姿式時，動作更能自如在騎乘位，女性上體較反位時挺宜，臉與上半身分離，故男性可以飽覽女性胴體。 因此，女性的害羞比在反位時更會受到刺激。 如果女性過份害羞，男性可閉上眼睛不看。
 
（三）側臥位
 
（1）前側位
 
前側位是男女對向，均橫臥的姿式。男性可以右手愛撫女性胴體。 女性並不完全側臥，上體差不多近乎仰臥狀，下半身橫臥。女性右腿，通常受男性體重壓迫，位放於男腰下。 這種姿式能使男女較少疲勞，缺點是男性不能自由運動，女性右腿要承受男體重 結合度淺，接觸感度不很強。很多人同睡一個房間時，這種姿式甚理想。
 
（2）後側位
 
後側位是男性從橫臥的女性背後擁抱的姿式。在此場合，如果男性胸部與女性背部緊貼在一起，便難於結合。因此。男性需要把身子往後挺直，上半身分離，女性如稍微 彎曲膝部，能使結合容易。
 
采這種姿式時，男性用右手愛撫女性 ，取左邊，女性則在右邊。這時男性要把右腿彎曲，放在女性腿上，或變三角形。 在後側位，如果女性把雙腿彎曲，向前蹲，同時男性往後挺直，則結合度深。 只是對女性刺激部位，限於陰道口後緣與 陰道前壁，而陰蒂則在刺激範圍之外，故男性必須同時愛撫陰蒂與乳房，以補不足 。 在懷孕期間，以對向位姿式交媾時， 無論如何小心，總會壓迫腹部，對胎兒有 害，如採取後側位，則無此顧慮。 而且，能使男性的身體緊貼，或調整 身體使結合度深，故不會傷害到陰道或子 宮口。 懷孕時，子宮頸部逐漸靠近骨盤度，而陰道變短，這時把陰重深插時有危險。因此進人度淺的後側位，可以說適合於懷孕期問。此外，這種姿式反應溫和，不致過份興奮 ，故在月經期間亦可採用之。但如果女性患不感症時，由於感度不佳，不適於採用。
 
（四）背向位
 
（1）背後位
 
與正常位相反，女性先伏臥，然後男性伏臥其上。 男女的雙腿位置與正常位一樣，女性可開可合，男性視情形，把雙腿放在女性內側或外邊。 在背後位，女性的臀部皮下脂肪成為墊物，可緩和男性對沁骨之衝擊。 如果男女均消瘦，採用正常位或騎乘位時，腸骨前面互相衝擊或腸骨碰到坐骨突起 ，而感覺疼痛，以致意識無法集中，但背後位則無此缺憾。因此，這種姿式適合消瘦者採用。 采背後位時，因此女性夥臥，故陰道口由上向下開，但男性性器指向前下方， 故方向背道而馳。 因此，在進人時，陰莖像弓一樣彎曲 ，不但結合度淺，如果抽送運動強烈，恐有滑出之虞。 而且，從背後接交時，女性之主要刺激中心局限於會陰、陰唇系帶、陰道口後緣，陰蒂並不在內，對女性來說，接觸感度不夠，而且心性的性動不自由。 對男性來說，有視覺效果。比橫臥姿勢所得刺激更大，而且男性能用雙手愛撫女性。
 
（2）膝肘位
 
女性伏臥，將雙膝放在床上，使上半身往前傾，男性在女後半跪，上半身挺直，采半坐姿式。男性雙臂環抱女性臀部，以便調節結合。 女性上半身前傾，男性宜與配合，否則陰莖會滑出，但一經結合，陰莖龜頭便強烈接觸到陰道後壁，陰莖則被壓迫成弓 形，磨擦感增加。男性甚俊。又由於陰莖下部給予陰蒂強烈刺激，快感增加。 采這種姿式時，女性可以說是無所事事，一切由男性主動，但女性可以動臀肌 ，或作些旋轉運動，以示女性也有意欲， 用以挑逗男性情欲。 又采此姿式時，女性陰道日，因陰壓而開啟，由於吸進空氣，因此陰道弛緩者或在性交運動時，空氣被擠出而發生令人不偷快的聲音。
 
（五）坐位
 
（1）前坐位
 
男性坐在床上，通常箕坐，女性面對跨坐男性大腿上，可以相擁抱。尤其男性可以環抱女腰，女性抱男頸部，以便穩定。 因女性把腿分開，陰道口露出，男性器容易進入，而且一旦結合完成，男性用雙手環抱女性下半身，女性因骨盤傾斜，陰蒂獲得刺激，陰道壁收縮，陰莖獲得緊迫括約感覺。又能增強勃起，使其持久。 同時這種姿式，能使雙方緊貼胸部，男性可把臉部投人女性懷中，因此可套牢性器 ，又可以吮吸乳房。 又男性可藉雙腿的上下運動與勾住臀部動作，能夠自由搖動女性骨盤，所以結合的深淺均能自由調節。 又這種姿式；適合懷孕期的性交。男性雙腿成半跪狀，結合度淺，在抽送往返運動時，能刺激陰蒂，以補接觸感度之不足，而且不會壓迫到腹部，能安全性交。 如果女性肥胖而想用這種姿式，可將上半身往後挺直後分離，但過分挺直，陰莖即深入。 男性肥胖時，雖往後挺直亦可，但不適宜。
 
（2）後坐位
 
男性采正坐姿勢，女性背向男性，騎乘男性大腿上。通常女性雙腿放在外邊，也可以採取正坐姿式。雙臂放在自己大腿部附近。男性的雙臂環抱女性腰部撫弄乳房。 采這種姿式時，男性跪坐床上，從女背後伸手環抱女腰或乳房。在這種姿式，可自由做性交運動。如果女性配合適宜，時間亦可以持久。 同時，可由女性領導性交行動，作前進後退、旋轉、斜行運動。 采後坐位時，陰道軸與陰莖的進人方向、角度大致一致，但因女性往前彎曲，背向男性，可得較深的結合。
 
這種姿式，因女性雙腿跨越男性外邊，故外性器露出。因此男性可同時愛撫乳房及陰蒂。用手指刺激陰蒂比性交時因沁骨壓迫刺激或磨擦刺激所得效果大。 採用椅子時，女性背向男性坐在其膝上。把雙腿置放外邊，雙腿並行而坐。如果要獲得較深的結合度，女性須把雙腿放外邊，因性器將因跨坐而張開。在沙發椅上，高或低，不易穩定時，女性可把雙腿放床上，可做上下運動或旋轉運 動。在此場合，在女性前放桌子，使其倚靠，效果更佳。
 
（六）立位
 
男性由女性背後保持站立姿式接近。雙方都站著時結合困難，女性要把腰部兩膝稍微彎曲，雙手放在兩膝上，男性稍微把腰部彎曲，以便結合。 女性雙腿稍微分開，上半身稍往前彎曲，臀部往後突出，以便穩定。男性把兩腿放在女性大腿內邊，稍微彎腰，向斜前上進入腰，雙臂放在乳房或環抱下腹部，保持乳房動作與保持身體的安定，一下子勾位，一下子放鬆，以獲得性交動作的效果
 
** 射精的抑制
 
本章為性交的調節篇，在房中術中，最怕精之消耗，為達到此目的，陰了儲精外，靠攝取異性的能量，亦能達到不老之目的。 玉房秘訣有這樣的記載：「二十歲者可經常二天射精一次，三十歲者三天一次，四十歲者四天一次，五十歲者五天一次，過了六十歲就不可能射精。」
 
素女對於黃帝的問題這樣回答：「每人性交的次數幅度，乃是根據體力差、年齡差和氣力差等因素來決定。」黃帝曾有宮女等一千二百人，故對房中術相當精通，其標準算是最大限度了。男性 從六十歲前後開始，賀爾蒙分泌就開始減少。到了七十歲時，也僅是最盛時的三分之一而已。
 
根據金賽博士的報告，七十五歲的男性三星期可性交一次，八十歲則二個月性交一次。所以，素女經的意見很恰當。 金賽博士說，七十年代及八十年代的老人，也有每週性交三、四次的例子。但從體質、食物和環境等不同條件來看時，古代的中國人和現代的白人與黑人是很難相提並論的。
 
在歐洲古代的例子裏，曾有一位希臘哲學家校古拉德斯十天性交一次，而基督教的路德爾認為每週一次最恰當，但他們對年齡的差別卻沒有提出。可惜，這些主張都相當抽象，總不如素女經上面所說的那麽具體。素女經主張的性交次數，對於現代人來說，實在是很得體的。素女經雖然沒有提及性交次數與季節的關係，但在《養生要訓》的書裏，卻說有一位名叫劉京的道士，春天三日性交一次，夏季與秋季一個月兩次，冬天最好不要洩精，這樣就可與天地自然的節韻互相符合。
 
在中國古代醫學裏，認為性交要順應春夏秋冬的變化，生、長、收、藏的活動反覆不停，冬天正是儲蓄陽氣的季節。交接的最適當時期在四月與五月，冬夏雖然不是非常適當，但在《養生要集》裏說，冬天性交一次，足抵春天的一百次。春天由於陽氣充足，所以性交次數多些也好。因為冬天陰氣較多，所以，應避免常常性交。總之，還是要尊重自然的節韻才好。
 
《洞玄子》一書上也曾說，為了要養精蓄銳，宜行中絕性交。這種觀察入微的程度，真是令人吃驚！正是洩精時，也得考慮女性的歡樂情況，一定要在雙雙進人高潮階段時洩精才好。 陽具淺進，只在陰核小帶與小陰曆之間遊樂，龜頭的深淺法一定要像嬰兒吸奶那樣才好。同時，閉目養神，舌抵住下腰，彎背鍋頭，張開鼻穴，閉緊肩膀，閉口吸氣，精氣很快可以延續射出。至於洩出量，一定會因人而差異，若用這種方法，最多只洩出十分之二、三。當然，這是利用呼吸法與古代養生術的柔軟體操——增強持續力而鍛煉出來的方法。現代人也可以活用這種方法。其要領只有一個，即要靠訓練來維持自信。素女經說的標準次數，在現實上也很適合，決不稀奇的。
 
** 洩精的次數與媚藥的處方
 
黃帝問素女曰這要不欲失精宜愛液者也即欲求子何可得寫素女曰 人有強弱年有老杜各隨其氣力不欲強快強快即有損故男年十五盛 者可一日再施疫者可一日一施年二十盛者日再施贏者可一日一施 年卅盛者可一日一施劣者二日一施冊盛者三百一施虛者四日一施 五十盛者可五日一施虛者可十日一施、六十盛者十一施虛者二十日 一施七十盛者可卅日一施虛者不寫
 
黃帝問素女道：「假如性交的要點，在於不洩精氣的話，那麽，精液必須要好好保存。不過，假如需要傳宗接代時，那恐怕就要洩精了。」
 
素女回答說：「人的身體有強弱，年齡也有老壯之別。每個人無不想盡力追求快樂，但若得到很大的快樂時，恐怕會損壞身體。因此，凡是年屆十五歲而精力飽滿者，一天可性兩次，瘦小者每天洩一次，亦無傷大雅。同樣地，二十歲者可日行兩次，弱者一次。三十歲的強壯者，可日行一次，弱者二日一次。 四十歲的強壯者，可三日一次，弱者四日一次。五十歲的強壯者，可五日一次，弱者十日一次。六十歲的強壯者，可十日一次，弱者二十日一次。 七十歲的強壯者，可三十日一次，弱者不可洩也。」
 
此外，《玉房秘訣》的記載如下：「二十歲者常常二天一次，三十歲者三天一次，四十歲者四天一次，五十歲者五天一次，過了六十歲就不可洩。」
 
此外又有如下的記載： 素女法人年二十者四日一洩年三十者八日一洩年冊者十六日一洩年五十者二十日一洩年六十者即畢閉精勿複更洩也若體力狗杜者一月一洩凡人氣力自相有強盛通 人者亦不可抑忍久而不洩致＊疽若年近六十而有數旬不得交換接中午者可閉精勿洩 也
 
素女的方法如下：「二十歲四天性交一次，三十歲者八天一次，四十歲者十六日一 次，五十歲二十一日一次，六十歲者閉精不洩。假如他體力強健的話（六十歲者），一月一次也無妨。大體上說，也有人的氣會自然強盛的，假如體格比平常人強盛者，即使 不勉強抑制，亦沒有多大關係。倘若長期不發洩的話，恐怕會變成癱疽的腫物。一旦過了六十歲時，數十天也不能交接，整十天也不能交接，整天愁眉不展者，則不洩精比較好些。」 前節所說的性交次數然大不相同，但均出自《玉房秘訣》上的事，不過，也有人說這是在《千金方》上的。
 
宋版《千金》方裏，把「禦女之法」誤刻為「素女之法」。 據說鼎鼎大名的貝益軒所寫之《養生訓》，也是根據上述觀點寫出來的。該書以人類一生只能性交一千八百次。金賽博士的報告，人到五十五歲的延長次數為三千八百三十一次，但也有人以為這個數字只能止於四十歲而已。 關於前節的方法，雖然現代人有其實在性，他們很重視陰陽交合的原理，總以為要蓄氣於體內。反之，一旦沒有新陳代謝，就會呈現腫物，這種說明自然是針對「觸而不洩」說的誤解，加以解說的。
 
有位日本人名叫小林一茶者，在日記裏記錄性生活。他的新婚是五十二歲，五十四歲八月八日起到二十一日止的性交次數記錄如下： 八　晴　菊女　回家 夜五交。 十二 晴 夜三交。 十五 晴 夫婦月見 三交。 十六 晴 三交。 十七 晴 墓諧 夜三交。 十八 晴 夜三交。 十九 晴 三交。 二十 晴 三交。 二十一 晴 四交。 菊女是他的妻子，丈夫五十四歲時，她正好二十八歲。 雖然小林一茶，曾因性無能，而服用淫羊藿當做催淫劑，這是一種富於情的賀爾蒙分泌的藥草，中國有句俗話說：「連羊吃了淫羊藿，也會熱中於交接。」根據經驗報告，吃了這種草後，精液會變濃，精量也會增加。由動物實驗裏，也發現老鼠和兔子吃了淫羊霍後，作用會更激烈。淫羊藿是媚藥之王。在日本也有一種草葉類似淫羊藿的藥草 。日本人稱之為碇草。經製成生藥之後，一直被認為是媚藥之王。
 
蔡一藩說：「以前有一位牧羊者，在羊群中發現一隻雄羊一天性交百次以上，他吃驚之餘，歷經多方調查，始知道這只羊與它所吃的草有關。他也照樣拿來吃，結果忽然欲火中燒，情況相似。」 淫羊藿雖被人當做治療性無能藥品，但一林一茶卻以為吃了碇後，對於防止老化的衰退很有效果。這種淫羊霍的效用，一直被視為一種特效藥－－即仙靈脾酒也。所以， 仙靈脾酒是淫羊藿的另一種名稱。蔡一藩的處方如下： 「淫羊蕾二十公克、茯苓十公克和三個大棗放入三合半水中，待剩下一合水時，即用火慢慢煎熬。」這是普通的強精強壯藥，媚藥和催淫劑的仙靈脾酒是根據下述的處方調製成的。另一種也跟上述處方相同。三種生藥量各加三倍，再好好地蒸，又讓日光曬乾，然後再蒸，反覆三次，再浸入一點澆酒，後加入百公克的蜂蜜，密封好了，過一個月，就可成為極佳的仙靈脾酒，蔡一藩很推薦前面的處方。總之，我們應該多服由中藥蒸發出來的強壯藥。
　
** 男人精力的盛衰
 
采女曰男之盛衰何以為候彭祖曰陽盛得氣則玉莖當熱陽精濃而凝 也其衰有五十曰精洩而出則氣傷也二曰精清而少此肉傷也三曰精 變而臭此筋傷也四曰精出不射此骨傷也五曰陰衰不起此體傷也凡 此眾傷皆由不徐交接而卒暴施寫之所致也治之法但禦而不施不過 百日氣力必致百倍
 
采女問說：「關於男人精力的盛衰，有什麽徵候可以看出來？」彭祖回答：「若男人精神飽滿，或是飽獲精氣，則陽具會發熱，精水濃凝。一退時，會有五個象徵出現：（1）精液洩出時，乃精神受到傷害。（2）精液薄時，乃系肉體受傷。（3）精液變臭時，乃系筋受傷。（4）雖然洩精，但不用射出，乃骨骼受傷。（5）精力衰弱，不能勃起，乃是身體受傷。一般而言，這些傷害都是由於交接匆促，以及情緒不安定時洩精所引起。
 
醫治的方法是：只是性交，但不洩精，則百日不到，一定可以氣力百倍。」為了不損壞體力，則不能亂暴，所以，性交時要慢慢地持續下去。 《玉房秘訣》說，由於交接的關係，常常會腰酸背痛，那麽脊樑靠壁而伸著腰，不要太低頭或過於仰首，腰部與脊樑要盡可能技著牆壁，就可以治好。
 
增強視力的強健法，即行將洩精之際，仰首止息，一面長吐一口氣，一面張目四望，收縮腹部，使行將洩出的精氣被呼回體內的迴圈器官裏。有一位仙人名叫沖和子，他曾經說：「這是吸取古代養生法的引導法，與胎息法等的醫療體操，配合呼吸法而練成的房中術。」 鍛練耳朵的方法，除了這些法術之外，尚有叩齒者，即叩打著上下牙齒，可以導出消除邪氣的強健法。這是由於齒與腎具有相當密切的關係而想出來強健法。大多數的男子，都以為自己患著早洩的毛病，因而煩惱，但事實上，部份的人是因為由於他們在觀念上誤解了早洩的意義，遂有杞人之憂。最多的誤會是把比較早期的射精——即女性未人快感高潮的射精認為是早洩。其實所謂早洩，是指極早期的射精而言，例如當陰莖剛插入陰道時，或性交運動才做了一下，或是陰莖還沒有插入，或者是在勃起時的一瞬間即開始射精。像這樣的情形，才是名副其實的早洩了。
 
至於僅僅是無法支持到妻子的快感高潮時即行射精，其中原因，是因為夫妻協調欠妥，尤以丈夫方面的努力不夠使然，而這一類的丈夫，除非他是極端的獨善其身者，或者是向來對妻子缺少體貼的人，或者是不僅性交藝術與性交經驗缺乏，在性交運動中缺乏協調要領的人，但這不必解釋為早洩，更不要自愧而杞憂，甚至將錯就錯，諱疾忌醫，那結果就會變成真正的早洩，甚至變成性無能。 有人要問，到底自性器接觸至射精，最低限度以多少時問才算正常呢？
 
這是個難題，因為在性交時，由於運動刺激的深淺、緩急、強弱及其刺激加重之分量而有差別，又運動刺激為一連串急迅的發展，抑或為間有停頓及減速現象，都可使時間上發生變化。但最大的影響，則由於丈夫本身大腦中的性興奮。就以不間斷的連續刺激來說，最少要有一分鐘以上，平均是三分鐘左右，如果中間有適當的減速或停歇時間，再加上因為意識的轉換而延遲射精，則其性支持續時間，竟有十分鐘乃至三十分鐘或更長久者。
 
又關於早洩的第二個錯誤判斷，常常是由於性興奮時興奮液（亦稱靠巴氏腺分泌粘液）自尿道口滲透出來，因而誤認為是洩精，這純是性知識缺乏的結果。許多妻子比丈夫更草率地下結論，認為自己的先生竟是如此的不爭氣，因此失望煩惱，真是莫明其妙的神經過敏。早期射精的原因，不外是生理方面的男性包皮的關係和心理方面的精神作用。特就此兩點加以說明： 男性陰莖頂端的龜頭，由一種極似粘膜極富彈性也極富知覺神經的皮膚所被覆著， 所以正是刺激極為敏感的部分，在男子的發育期前，這個龜頭一直為包皮所覆蓋著，爾後逐漸成長的時候，便自然從包皮裏露出，因為這樣敏感的龜頭表面，經常被衣服類的摩擦刺激，其感受性也便逐漸遲鈍，僅於一些輕微的刺激，不會容易興奮的，這倒是將來性交時可以充分接受刺激摩擦的有利條件。反之，如果男性婚後仍在包莖狀態，則勃起後露出的龜頭，比沒有包童男性的更為敏感，只要稍有性交運動，甚至剛好結合的一瞬間，那龜頭所受刺激即刻達到極點，於是引起射精了。因此在青年時，若是包莖的話，須常使包皮後退為妙，同時這樣做法，亦可預防包皮內藏垢積汙而發炎。如果是嚴重的包莖（即勃起時包皮絲毫不後退），那便反而對刺激極為遲鈍感，對女性方面也減低興趣，因此凡是包皮過長，或是包莖的話，總以早請醫生手術割除為妙。這對性生活是很重要的一件事。
 
另一種起因於精神方面的早洩，則比較麻煩，因為那要先研究發生病態的精神方面的因素，這是另外一種專門學問，大概說來，在單身時期對於自慰行為所懷的不安與厭惡觀念，或對性交缺乏自信，或極度的女性崇拜，以及相反的女性厭惡，懷孕忌避，宗教戒律與性欲的矛盾等等內在的原因，另有性交時環境的不適當，有的怕被人窺視，有的懼怕音響的驚擾，這些都是可能引起精神變化的因素。 此外男性的早洩，可成為女性冷感症的原因，同時女性的冷感症，亦可成為男性早洩的原因。為要防備精神上起因的早洩，最好對性方面要有正確的認識，並且對性交要有自信。至其治療，則應請專家探究原因，對症處理，才能夠獲得圓滿徹底的解決。上面說了許多早洩的界說及原因，我們已有一個概念——早洩的情形中許多是錯誤的感覺，不是真正的早洩。
 
為了要排除此一夫妻間幸福的絆腳石，丈夫不妨作有計劃的延遲射精。為了達到上述目的，首先，男性要有一種堅定自信的意志，以便與妻子共謀高潮的一致，假如夫妻倆對性生活經驗不夠時，丈夫便很難體會到妻子是否要進人快感高潮的徵兆，在此經驗不足的情形下，最好是夫妻倆預先約定一個表達的信號，妻子應將自己快感高潮即將來臨的消息，向丈夫發出通告。 如果丈夫覺得這個信號來得太遲，便可變更性交的態位元和運動方式。因為夫妻間往往有些態位使男方比女方更受刺激，另一種態位卻恰恰相反，妻子較丈夫受到刺激為多。當然丈夫應該在此時選擇減少自己刺激而對妻子有極大刺激的態位來適應當前的環境。至於那種態位有理想的妙用，倒是因每個人而不同。要夫妻們平時在性生活中去體驗，作成一些屬於他們自己的結論，以便在運用上求得方便。
 
當丈夫在應用態位元變化的方法還不自如時，不妨採用一些轉移注意力的方法，如算一算數字，或在思考中臨時找一點小事情輕輕的在腦際掠過一下，也可以使自己對性交運動的反應遲鈍一些的。不過先得知道自己究竟是不是屬於神經質的人，如屬神經質的男性，可能因此意識的轉變，遭致勃起不完全或萎縮的變化，那是弄巧成拙了。對態位變化無經驗，而又屬於神經質的人，則不妨在性交運動中保持一些間歇的動作！即是略作短時間的停頓，這種短暫的停頓，使妻子有隔間的休息，便愈加期待和焦急，因而促進了她的性興奮，這是對夫妻雙方同時進人高潮的有效方法，不過，施行此方法時要注意，不能使這個間歇的時間太長，這樣會使妻子的興奮冷卻，那就太掃興了。最好在間歇時施以其他的愛撫刺激，以代替運動刺激，以保持妻子的興奮持續乃至昂進。在運動中另外還有一種克止早洩的技巧。如果丈夫認為淺近的插人或徐緩的運動是微弱的刺激，那是誤解的，因為一般來說，男性若是使龜頭面尤其是龜頭冠受到刺激，其所引起的刺激亦強，如果丈夫為避免防止早洩，僅使龜頭在陰道口，做著淺近的性交運動，則所帶來並不是弱小刺激的效果，反而成為互相間更強烈的刺激效果了。為了要達到延遲射精的目的，便可能因方法的誤解，得來相反的結果。因此，徐緩的前進，急速的後退，這種運動的方法倒也是防止早洩的好辨法，而且這種運動的效果，使妻 所受的刺激比丈夫為大，亦可以協調夫妻倆高潮的一致。在這種運動方式中，要前進時可以安步當車的前進，要後退時則迅雷不及掩耳的退卻，但不可使兒頭冠滑出陰道口為妙。 如果對上述兩種方法加以體驗和研究，依順著自己的意思去靈活運用，終可將射精這一過程延遲。
 
有人認為女人需要有一個具有「綿羊」、「小狗」、「老虎」三種個性的丈夫，才是真正的滿足，解釋是：第一要像綿羊般馴善，第二要像小狗般親熱，第三要像老虎般的兇猛。我想這個老虎般的兇猛，只有在性交的最後階段才是極需要的。 照上面所說，有計劃的去達到延遲射精，並不是一件難事。只要男性明白與女性一同所經驗到的快感高潮才算為完滿的快感高潮，儘量照此目標去做，在夫妻間建立許多有性經驗上的默契，則更為容易排除那夫妻幸福上的絆腳石——早洩——了。在性生活的過程中，除了早洩以外，還有一種「遲精」（遲洩）的病態，不過遲精的名詞也許還有許多人感到陌生，但這卻是性生活上一種不亞於早洩的病態。在性交進行中，這種病態如果超過了女性所渴望男性快點達到高潮的階段，就會由期待而變成勉強，由勉強而變成厭煩，由厭煩而變成失望，最後，終於由失望而變成痛苦的感受時，於是運精亦就成了幸福夫妻的一條裹腳布，說起來，這也是順理成章的事。 一般丈夫在房事生活中，患遲洩的人固然遠不如早洩的那樣普遍，但這卻是性生活上一種不亞於早洩的病態。「遲洩」的後果，更會容易招致性無能的病症的。關於夫妻從性器接觸後到丈夫射精，在這過程中，由於運動的技巧，對性知識的瞭解以及刺激程度的強弱的不同，都可使交合的時間發生延長或縮短的變化；但最大的影響，則由於丈夫本身大腦中的興奮情緒。不過，性交延長到一小時以上，夫妻倆仍是得不到快感洩精，或者雖有少許快感但卻射不出精，這就叫做「遲洩」的病態了。遲洩的起因，多半是運用遲延射精的錯誤，如誤用意識轉移，經常想到性交以外的事體上去，那麽一旦成了習慣之後，便不能隨心所欲去射精了。或者自己認為已經有辨法自由地做有計劃的遲延射精，就經常做著長時間的性交。其結果也可能會發生遲洩的現象。這時，雖然丈夫急切指望達到射精，結束這次性交運動，但他無論如何對性器加以強烈的刺激，總是不容易達到目的，等到他感覺得非常疲勞時，就不得不把運動中止，便成為一種不完全的性交，他將得不到性交真正的樂趣了。在女性方面，如果受到男性過份遲延射精的影響，弄成了一種習慣，使她老是在等 候她的丈夫的射精，以便一起接受快感高潮，那麽終於超過焦急，渴望的階段，以後，反而對性交刺激由勉強而感到痛苦。一般身為妻子的，在交合中總是等待著丈夫的射精；以便迎合快感高潮的一致，同享夫妻間幸福的樂趣；如果丈夫射精過遲（甚至無法射精），使妻子由期待而焦躁，於是不得不先進人高潮，這並不是妻子所願意的，在她的心理，總是希望與丈夫共同享受那快樂的瞬間。就丈夫的心理來說，對於妻子性高潮以後的射精，也與早洩一樣的索然無味。所以遲洩對夫妻幸福的關係，是十分重大的。遲洩，除了上述那種類型外，有時不論任何人，由於當時的肉體或精神條件的影響，也會有達不到射精的情形。這時候，如果盡用急速淩亂的前後運動，妄圖促進，反會使效果變低上？時應選擇男性最感刺激的體位，特別是對龜頭冠予以強烈的刺激，為要做到此地步，不要忘記應以陰道口為界，使龜頭進進出出，往往會收到促進射精的效果勃起不全與陽萎，是男性性機能障礙上的一種特別的病症，而且範圍很廣。勃起不全，有時還可以從經驗中求得要領，在技巧上講究方法，運用愛撫、吮吻等刺激手段，使丈夫在意識上充滿肉欲的衝動，以克服這種性機能的障礙；但是陽萎，除非有充裕的治療時間，則一時是無法克制的。
 
當夫妻們正在情切切，意綿綿，情欲的渴望已達到頂點，正需要求得滿足的當兒，而“那個”竟來了一個相應不理，任憑夫妻倆如何的愛撫與刺激，卻依然我行我素，那才是煞風景的事呢！陽萎的症狀差不多把性交的使命完全失去，不但夫妻間享不到性的樂趣，而且阻礙生育，因而釀成夫妻的不睦，增加煩惱，總之，它是家庭的攪亂者，幸福夫妻的剋星。要達到性交的目的，當然以丈夫陰莖勃起為絕對的必要條件，然而婚後日久，則丈夫的性欲不一定和勃起同時產生。大概一般妻子們都會瞭解，只要對丈夫生殖器加以愛撫，即可使其勃起，但卻有許多妻子，一日一使其勃起以後，便以為大功告成，立即急著要進行性交了，這是錯誤的，勃起並不是已有了性交意志。因為當丈夫的性器得到愛撫刺激，當然會勃起，但這情形和丈夫本身實在有了性欲而勃起的時候，大不相同。未必即刻就有性欲，這時急促地進行性交，是僅以意志的力量強行性交，不是自然的發展，對丈夫精神、健康都是有害的，在這種情形下，對妻子未必能滿足。所以妻子要想主動引逗丈夫時，同樣要注意到培養一種足以令丈夫性興奮的氣氛。除了病態的勃起不全外，在漫長的婚姻歲月中，往往由於精神或肉體上的條件一時不濟，使丈夫有偶然勃起不全的現象，這時候，不管妻子如何的愛憮刺激，總達不到性器結合的目的。即使是結合了，不久就會萎縮下去，性交也無法持久。在這樣的時候，應該讓丈夫作充分休息，不宜勉強施行性交，尤其不要表示不滿的態度，甚至隨便批評，如果傷害了丈夫的自尊心，便會使他失去——倍，可能因生理上的勃起不全，懷疑到病理上的勃起不全，因而神經過敏，轉人病態了。
 
此外有一種近於猥褻的方法，對勃起不全可以振奮的，那就是性器接吻，用嘴去吻性器，對性的刺激是十分熱烈的。後天性陽萎的原因，有因生殖器疾病的反常，有因勃起中樞興奮性的缺乏，有因反射神經的障礙。生殖器的疾患，及反常的陽萎，可分作十數種。重的，是器質的陽萎，是生殖器反常畸形，或疾病的變化而得的。這是指那陰莖缺損，發育不全，高度彎曲， 陰莖破裂，包莖等的陽萎而說的。依勃起中樞興奮性的缺乏的陽萎，多半是性欲減退，或完全失去的。因為攝護腺部或尿道腺部的慢性淋病、梅毒、結核、腎臟病、溢血病、脊髓炎、肥胖病等疾患，性的昂奮完全受了妨礙。失去了性欲中樞的刺激，而發生陽萎。但其他麻醉品如咖啡等的中毒，也是原因之一。尤其是因手淫和性交過多，勃起和射精中樞失去了昂奮作用，而發生了陽萎，這名叫麻痹性陽萎。反射作用的神經障礙，是因驚悸、苦慮、羞恥、激怒、恐怖等強度的精神感動而成了的陽萎；也有純真的青年，深怕梅毒，為一種脅迫觀念所襲，因而成了陽萎的；還有埋頭於科學的發明，把精神集中於某方面的結果，因而發生陽萎的。實在是不勝枚舉。陽萎的治療，並不是藥物上問題，而是時間上的問題，譬如像馬錢子那種藥。一般人以為它是治療的良藥，其實它對性器官及中樞神經只有刺激作用，如果本來是興奮過度的陽萎，用它比不用它更壞。所以在治療之先，必須求教於醫生，瞭解那個致萎的原因，在醫療時期，必須慎守攝生的規則，對於有刺激的食物，諸如油、酒、辣椒等類，應完全禁絕，多食蛋白質和富有營養之食物，並行冷水浴，經常以冷水毛巾洗擦陰部，也是有效的療法；神經性的陽萎，應特別把生活弄得很有規律，每晨作適當的運動，選擇清淡的食物，避免身心的過於疲勞，這是很好的自律療法；但是有慢性淋病攝護腺炎等病的人，對於運動是不可不考慮的。患陽萎的人，應該禁止性交，因為性交會使病更趨嚴重的，尤其不能去找妓女。長時期的想念著性交的欲望，焦急、煩惱，一切精神上的緊張都是不利的
 
** 女性行房的最佳時辰
 
素女曰求子法自有常體清心遠慮安定其矜袍垂齊戒以婦人月經後 三日夜半之後雞鳴之前嬉戲令女盛動乃往從之適其道理同其快樂 卻身施寫勿通遠至麥齒遠則通子門不入子戶若依道術有子賢良而 老壽也。
 
素女說：「求子的方法，自有其一貫的法則，身體輕快，心無憂慮，情緒平靜，衣冠整齊，專心齋戒，當女人月經完畢的三天之後，即深夜過後，雞鳴之前，開始撫愛。先使女人漸漸興奮，接著方行做愛，按照房中術的道理，共同享受其間的快樂。洩出精液時陽具不要從小陰唇拉出外面。因為抽出過度時，會脫離子宮門，精液就進不去子宮假如依照這種技術而得子的話，那他一定是一個很傑出而且很長壽的人。」
 
彭祖說女人月經完畢後的第十五天夜半受船時，可以生下一個聰明伶俐，長壽而且高貴的兒子。但素女卻以為月經完畢後的第三天性交。這對於現代人來說，還算比較實際可行。夜半後，天亮前的時刻，會使人有奇異的感受，所謂夜半，就是子時（午後十一時 起至午前一時）為止，接著就是丑時（午前一時至三時止），天亮就是寅時（午前三時起至五時止）。因此，夜半後，天亮前正是丑時的時間。這段時刻之所以很好，乃是因為這段時刻跟肝有關係。而肝跟持久力又是關係最密切的。肝也與性器的脈脈連通。這個時刻的中心為午前二時，在這個時辰裏，肝的經脈流動最好，睡眠也很充足，故是最理想的做愛時間。素女經說，陽具的淺進方式比較容易受胎，這恐怕是根據古代性生活的經驗得來的
　
** 如何才有好胎
 
素女曰夫人合陰陽當避禁忌常乘生氣無不老壽若夫婦俱老雖生化 有子皆不壽
 
素女說：「人類為了要符合陰陽之道，一定要避免若干禁忌。當氣勢最好時，生下的孩子，通常都會長壽的。如果夫婦都很年老，即使在氣勢最佳時，生下孩子，也都不會長壽的。」
 
在氣勢最佳時做愛生下的孩子是很健全的，由於自古以來，年輕得子都很健全的緣故。假使很年輕，但若身體不適，或在酒醉時也不能做愛的。假如雙親的氣勢不是很好，那是因為身體欠佳。所謂氣勢，乃是精力飽滿，這是男女做愛的最佳條件，故能給予受胎很好的影響。
 
素女經雖沒提到年齡問題，但在《玉房秘訣》裏認為男女年紀太大時所生下的孩子不能長生，素女經說八十歲的男子，娶一位十七、八歲的少女，也照樣能生子。反之，五十歲的女性跟年輕丈夫也會生育子女。男人八十歲結婚而生子的人有卓別林，還有一位日本東都清水寺的管長——大西良 慶師，他七十五歲，娶一位二十三歲的年輕太太，到了八十六歲，才生下了孩子。
 
卓別林是一位貧窮年輕的猶太人，他後來成為國際聞名的電影明星，但終身追求食欲、工作和戀愛。大西師也一樣，當他年輕時，曾經被女人叫做大西惡慶，可見他在男女關係方面，真是聲名狼狽！ 總之，他們兩人自年輕時代開始，就對於女人相當精進。所謂「精進」者，乃是指性能力很實在，而且容量豐富。即使年屆高齡，也依然能生貴子。所以，我們各個年代的人，對於性的知識，也一定要有相當研究才好。
　
** 令人心動的女人
 
黃帝曰入相女人云何謂其事素女曰入相女人天性婉順氣聲濡行絲 發黑弱肌細骨不長不短不大不小鑿孔居高陰上無毛多精液者年五 五以上三十以還未在產期交接之時精液流漾身體動搖不能自定汗 流四逋隨人舉止男子者雖不行法得此人由不為損
 
黃帝問：「所謂長相令人喜愛的女人，到底是指些什麽呢？」
 
素女回答：「所謂長相令人喜歡者，就是天性溫和，聲音不乾涸，頭髮細黑，肌肉柔軟，骨骼精細，身體不高不矮，不胖不瘦，小腿結實，陰戶局部不長毛，而且黏液一直好像水溝一樣濕濕地，年紀大約在二十五到三十歲之間的未婚女人。她們做愛時，津液濕潤，身體擺動得不自己，汗流滿身，任男人去擺佈，而且還會隨著男人的意思而行動。如果男人獲得這種女人的話，即使沒有遵循交合的規則，也不會損壞身體的。」
 
素女對於黃帝問題，曾舉出各種條件，並且解釋得好像女體浮現在眼前那樣生動。大體來說，音域遼闊而且響亮，才是女中豪傑。當她一出聲，就有充份的準備。「恥丘殷實」，若以別種表現法，則相當於「陰戶向前」的意思，乃是骨盤構造的特徵。「九法」中的第三項——猿搏的姿態，與第五項——龜勝的姿態等屈曲位，這些都近於正常位，也是在春宮書裏常常被人描寫的體位。有人說：「好淫者，牝上不長毛。」這就是說好淫的女人，陰部不長毛。據計牝毛的數量，跟眉毛和手腳的體毛幾乎成比例。
 
在中國稱女人的同性愛為「磨鏡」，這是由於無毛被視為當然而引起的。在我國古代的醫學書裏，認為鑒定一個女人的好壤，首先要詳細調查她陰戶與腋下的毛髮。如果毛發軟軟地，靜靜地，則那個女人就屬於上品。同時，如果她的發色是紅的，這是表示會損壞男身的象徵。所以，紅發是被男人所忌諱的。
 
「白、鼓、軟、紅、緊」五字的排列順序，也就是表示被男人喜愛的情況。此外，聲音要細，也就是說女人的嘎聲是好的象徵。假如男人獲有這種條件的女人，他不但會樂此不疲，而且還能飽養精氣，延年益壽。曾有一本《雜事秘辛》的書，內容記載後漢恒帝的選妃標準，女人身上各部份的尺寸，都被記得很具體。例如：「肩寬一尺六寸，屁股比肩寬少三寸，從肩到手指上，各長為二尺七寸，指離拿四寸，細小比較受人歡迎，從腿到腳止的長度是三尺二寸，腳的長度八寸，脛與甲要肥而豔，腳底很平，腳指很短，沒有黑子與麻子……」 現在傳說的仙道，也就是古代的房中術，它說能否給予男性某種陽氣，這完全要看女人的條件是否被男人看中來決定。
 
照古代房中術的說法，擇伴時要考慮以下四個條件——眉清、目秀、唇紅，齒白。這四個條件說來真是有趣。
 
首先是眉毛，凡是一字眉的女人，被認為性交技術不佳，缺乏羞答答的姿態，不能得到男人的歡心。兩邊的眉毛相系的女人，其持續力衰弱，而且神經質。除了八字眉外，只有眉毛叢生的女人才最喜歡陰陽交接之道，她的床上工夫會使得男人如醉如癡。這種女人的眉叫做「眉清」。此外，瞳偏向上方，好像怪眼的下三白眼，或使媚眼兒的女性也會令男人銷魂。這種女人稱為「目秀」。瞳偏向下方的上三白眼的女人，則會使男人身體衰弱和生病，所以要嚴加警惕才好。口唇血紅，或者口唇紫色的女人，容易引起心臟麻痹。但只有紅色的口唇，才是一個健康女性的象徵，這種女性的口唇，稱為「唇紅」。齒列漂白的女人，可謂陽氣飽滿，齒與腎的關係很深。當列不好的人，常因病弱而不能過度做愛。
 
從《肉蒲團》書中，獲悉男人最喜歡的女人，乃是平凡而新鮮，即要求精通床上工夫的意思。有位名叫花辰的女人，她曾授與未央生的真傳：「要先看書，接著一面行陰陽之道 ，一面要讀書和聽聲音。」不過，一般人看過了幾張圖和幾本書後，就沒有作用了。應當備上數百張，或數百冊書，要先看看畫，但不宜很快進人陰陽之道的境界，僅在十分興奮時進人陰陽之道。在這一進一出的狀態中，一面互相讀書和聽聲音。待人興奮狀態，才開始運動。但是，事情並非如此繼續下去就好，而是暫停片刻，讓陽具依然放在陰戶裏，再次看書讀書。此外，再聞聲音，也就是聽人的聲音，當然是指聽在陰陽道上那個人的聲音，而且單人做亦可。花辰叫女傭人單獨使用道具，照這種方式表演。未央生在世時，所謂看、讀、聽的動作，其實不過如此罷了。現在也是花樣百出，花辰的方法，正是好好利用男人喜愛的，女性之床上工夫，「溫故知新」就是指這件事而言。素女說男人所喜愛的條件，也是指男人喜歡一個能給自己快樂，與長壽的女人。其次，素女也從房中術談到一般交接的禁忌。所謂禁忌者，乃是指陰陽道理論，以及根據這個理論而來的民信仰。例如素女經雖也提到房事的禁忌日期等，但由於此中迷信味道很濃，所以這部份的原文恕不贅述。《玉房秘訣》有下面一段有趣的敍述：「姦淫所以不能長生者，不但是觸怒鬼神，而且自作自受。如放入粉末的媚藥，或用象牙做道具來用，都會衰老，甚至夭壽。」由此可見這是放入媚藥以及使用道具的情況。媚藥者雖然詳情不悉，但這是男性用在增強性欲，好像西方王母陰道中放的乾棗等。
　
** 射精的抑制
 
本章為性交的調節篇，在房中術中，最怕精之消耗，為達到此目的，陰了儲精外，靠攝取異性的能量，亦能達到不老之目的。 玉房秘訣有這樣的記載：「二十歲者可經常二天射精一次，三十歲者三天一次，四十歲者四天一次，五十歲者五天一次，過了六十歲就不可能射精。」
 
素女對於黃帝的問題這樣回答：「每人性交的次數幅度，乃是根據體力差、年齡差和氣力差等因素來決定。」黃帝曾有宮女等一千二百人，故對房中術相當精通，其標準算是最大限度了。男性 從六十歲前後開始，賀爾蒙分泌就開始減少。到了七十歲時，也僅是最盛時的三分之一而已。
 
根據金賽博士的報告，七十五歲的男性三星期可性交一次，八十歲則二個月性交一次。所以，素女經的意見很恰當。 金賽博士說，七十年代及八十年代的老人，也有每週性交三、四次的例子。但從體質、食物和環境等不同條件來看時，古代的中國人和現代的白人與黑人是很難相提並論的。
 
在歐洲古代的例子裏，曾有一位希臘哲學家校古拉德斯十天性交一次，而基督教的路德爾認為每週一次最恰當，但他們對年齡的差別卻沒有提出。可惜，這些主張都相當抽象，總不如素女經上面所說的那麽具體。素女經主張的性交次數，對於現代人來說，實在是很得體的。素女經雖然沒有提及性交次數與季節的關係，但在《養生要訓》的書裏，卻說有一位名叫劉京的道士，春天三日性交一次，夏季與秋季一個月兩次，冬天最好不要洩精，這樣就可與天地自然的節韻互相符合。
 
在中國古代醫學裏，認為性交要順應春夏秋冬的變化，生、長、收、藏的活動反覆不停，冬天正是儲蓄陽氣的季節。交接的最適當時期在四月與五月，冬夏雖然不是非常適當，但在《養生要集》裏說，冬天性交一次，足抵春天的一百次。春天由於陽氣充足，所以性交次數多些也好。因為冬天陰氣較多，所以，應避免常常性交。總之，還是要尊重自然的節韻才好。
 
《洞玄子》一書上也曾說，為了要養精蓄銳，宜行中絕性交。這種觀察入微的程度，真是令人吃驚！正是洩精時，也得考慮女性的歡樂情況，一定要在雙雙進人高潮階段時洩精才好。 陽具淺進，只在陰核小帶與小陰曆之間遊樂，龜頭的深淺法一定要像嬰兒吸奶那樣才好。同時，閉目養神，舌抵住下腰，彎背鍋頭，張開鼻穴，閉緊肩膀，閉口吸氣，精氣很快可以延續射出。至於洩出量，一定會因人而差異，若用這種方法，最多只洩出十分之二、三。當然，這是利用呼吸法與古代養生術的柔軟體操——增強持續力而鍛煉出來的方法。現代人也可以活用這種方法。其要領只有一個，即要靠訓練來維持自信。素女經說的標準次數，在現實上也很適合，決不稀奇的。
 
** 洩精的次數與媚藥的處方
 
黃帝問素女曰這要不欲失精宜愛液者也即欲求子何可得寫素女曰 人有強弱年有老杜各隨其氣力不欲強快強快即有損故男年十五盛 者可一日再施疫者可一日一施年二十盛者日再施贏者可一日一施 年卅盛者可一日一施劣者二日一施冊盛者三百一施虛者四日一施 五十盛者可五日一施虛者可十日一施、六十盛者十一施虛者二十日 一施七十盛者可卅日一施虛者不寫
 
黃帝問素女道：「假如性交的要點，在於不洩精氣的話，那麽，精液必須要好好保存。不過，假如需要傳宗接代時，那恐怕就要洩精了。」
 
素女回答說：「人的身體有強弱，年齡也有老壯之別。每個人無不想盡力追求快樂，但若得到很大的快樂時，恐怕會損壞身體。因此，凡是年屆十五歲而精力飽滿者，一天可性兩次，瘦小者每天洩一次，亦無傷大雅。同樣地，二十歲者可日行兩次，弱者一次。三十歲的強壯者，可日行一次，弱者二日一次。 四十歲的強壯者，可三日一次，弱者四日一次。五十歲的強壯者，可五日一次，弱者十日一次。六十歲的強壯者，可十日一次，弱者二十日一次。 七十歲的強壯者，可三十日一次，弱者不可洩也。」
 
此外，《玉房秘訣》的記載如下：「二十歲者常常二天一次，三十歲者三天一次，四十歲者四天一次，五十歲者五天一次，過了六十歲就不可洩。」
 
此外又有如下的記載： 素女法人年二十者四日一洩年三十者八日一洩年冊者十六日一洩年五十者二十日一洩年六十者即畢閉精勿複更洩也若體力狗杜者一月一洩凡人氣力自相有強盛通 人者亦不可抑忍久而不洩致＊疽若年近六十而有數旬不得交換接中午者可閉精勿洩 也
 
素女的方法如下：「二十歲四天性交一次，三十歲者八天一次，四十歲者十六日一 次，五十歲二十一日一次，六十歲者閉精不洩。假如他體力強健的話（六十歲者），一月一次也無妨。大體上說，也有人的氣會自然強盛的，假如體格比平常人強盛者，即使 不勉強抑制，亦沒有多大關係。倘若長期不發洩的話，恐怕會變成癱疽的腫物。一旦過了六十歲時，數十天也不能交接，整十天也不能交接，整天愁眉不展者，則不洩精比較好些。」 前節所說的性交次數然大不相同，但均出自《玉房秘訣》上的事，不過，也有人說這是在《千金方》上的。
 
宋版《千金》方裏，把「禦女之法」誤刻為「素女之法」。 據說鼎鼎大名的貝益軒所寫之《養生訓》，也是根據上述觀點寫出來的。該書以人類一生只能性交一千八百次。金賽博士的報告，人到五十五歲的延長次數為三千八百三十一次，但也有人以為這個數字只能止於四十歲而已。 關於前節的方法，雖然現代人有其實在性，他們很重視陰陽交合的原理，總以為要蓄氣於體內。反之，一旦沒有新陳代謝，就會呈現腫物，這種說明自然是針對「觸而不洩」說的誤解，加以解說的。
 
有位日本人名叫小林一茶者，在日記裏記錄性生活。他的新婚是五十二歲，五十四歲八月八日起到二十一日止的性交次數記錄如下： 八　晴　菊女　回家 夜五交。 十二 晴 夜三交。 十五 晴 夫婦月見 三交。 十六 晴 三交。 十七 晴 墓諧 夜三交。 十八 晴 夜三交。 十九 晴 三交。 二十 晴 三交。 二十一 晴 四交。 菊女是他的妻子，丈夫五十四歲時，她正好二十八歲。 雖然小林一茶，曾因性無能，而服用淫羊藿當做催淫劑，這是一種富於情的賀爾蒙分泌的藥草，中國有句俗話說：「連羊吃了淫羊藿，也會熱中於交接。」根據經驗報告，吃了這種草後，精液會變濃，精量也會增加。由動物實驗裏，也發現老鼠和兔子吃了淫羊霍後，作用會更激烈。淫羊藿是媚藥之王。在日本也有一種草葉類似淫羊藿的藥草 。日本人稱之為碇草。經製成生藥之後，一直被認為是媚藥之王。
 
蔡一藩說：「以前有一位牧羊者，在羊群中發現一隻雄羊一天性交百次以上，他吃驚之餘，歷經多方調查，始知道這只羊與它所吃的草有關。他也照樣拿來吃，結果忽然欲火中燒，情況相似。」 淫羊藿雖被人當做治療性無能藥品，但一林一茶卻以為吃了碇後，對於防止老化的衰退很有效果。這種淫羊霍的效用，一直被視為一種特效藥－－即仙靈脾酒也。所以， 仙靈脾酒是淫羊藿的另一種名稱。蔡一藩的處方如下： 「淫羊蕾二十公克、茯苓十公克和三個大棗放入三合半水中，待剩下一合水時，即用火慢慢煎熬。」這是普通的強精強壯藥，媚藥和催淫劑的仙靈脾酒是根據下述的處方調製成的。另一種也跟上述處方相同。三種生藥量各加三倍，再好好地蒸，又讓日光曬乾，然後再蒸，反覆三次，再浸入一點澆酒，後加入百公克的蜂蜜，密封好了，過一個月，就可成為極佳的仙靈脾酒，蔡一藩很推薦前面的處方。總之，我們應該多服由中藥蒸發出來的強壯藥。
　
** 男人精力的盛衰
 
采女曰男之盛衰何以為候彭祖曰陽盛得氣則玉莖當熱陽精濃而凝 也其衰有五十曰精洩而出則氣傷也二曰精清而少此肉傷也三曰精 變而臭此筋傷也四曰精出不射此骨傷也五曰陰衰不起此體傷也凡 此眾傷皆由不徐交接而卒暴施寫之所致也治之法但禦而不施不過 百日氣力必致百倍
 
采女問說：「關於男人精力的盛衰，有什麽徵候可以看出來？」彭祖回答：「若男人精神飽滿，或是飽獲精氣，則陽具會發熱，精水濃凝。一退時，會有五個象徵出現：（1）精液洩出時，乃精神受到傷害。（2）精液薄時，乃系肉體受傷。（3）精液變臭時，乃系筋受傷。（4）雖然洩精，但不用射出，乃骨骼受傷。（5）精力衰弱，不能勃起，乃是身體受傷。一般而言，這些傷害都是由於交接匆促，以及情緒不安定時洩精所引起。
 
醫治的方法是：只是性交，但不洩精，則百日不到，一定可以氣力百倍。」為了不損壞體力，則不能亂暴，所以，性交時要慢慢地持續下去。 《玉房秘訣》說，由於交接的關係，常常會腰酸背痛，那麽脊樑靠壁而伸著腰，不要太低頭或過於仰首，腰部與脊樑要盡可能技著牆壁，就可以治好。
 
增強視力的強健法，即行將洩精之際，仰首止息，一面長吐一口氣，一面張目四望，收縮腹部，使行將洩出的精氣被呼回體內的迴圈器官裏。有一位仙人名叫沖和子，他曾經說：「這是吸取古代養生法的引導法，與胎息法等的醫療體操，配合呼吸法而練成的房中術。」 鍛練耳朵的方法，除了這些法術之外，尚有叩齒者，即叩打著上下牙齒，可以導出消除邪氣的強健法。這是由於齒與腎具有相當密切的關係而想出來強健法。大多數的男子，都以為自己患著早洩的毛病，因而煩惱，但事實上，部份的人是因為由於他們在觀念上誤解了早洩的意義，遂有杞人之憂。最多的誤會是把比較早期的射精——即女性未人快感高潮的射精認為是早洩。其實所謂早洩，是指極早期的射精而言，例如當陰莖剛插入陰道時，或性交運動才做了一下，或是陰莖還沒有插入，或者是在勃起時的一瞬間即開始射精。像這樣的情形，才是名副其實的早洩了。
 
至於僅僅是無法支持到妻子的快感高潮時即行射精，其中原因，是因為夫妻協調欠妥，尤以丈夫方面的努力不夠使然，而這一類的丈夫，除非他是極端的獨善其身者，或者是向來對妻子缺少體貼的人，或者是不僅性交藝術與性交經驗缺乏，在性交運動中缺乏協調要領的人，但這不必解釋為早洩，更不要自愧而杞憂，甚至將錯就錯，諱疾忌醫，那結果就會變成真正的早洩，甚至變成性無能。 有人要問，到底自性器接觸至射精，最低限度以多少時問才算正常呢？
 
這是個難題，因為在性交時，由於運動刺激的深淺、緩急、強弱及其刺激加重之分量而有差別，又運動刺激為一連串急迅的發展，抑或為間有停頓及減速現象，都可使時間上發生變化。但最大的影響，則由於丈夫本身大腦中的性興奮。就以不間斷的連續刺激來說，最少要有一分鐘以上，平均是三分鐘左右，如果中間有適當的減速或停歇時間，再加上因為意識的轉換而延遲射精，則其性支持續時間，竟有十分鐘乃至三十分鐘或更長久者。
 
又關於早洩的第二個錯誤判斷，常常是由於性興奮時興奮液（亦稱靠巴氏腺分泌粘液）自尿道口滲透出來，因而誤認為是洩精，這純是性知識缺乏的結果。許多妻子比丈夫更草率地下結論，認為自己的先生竟是如此的不爭氣，因此失望煩惱，真是莫明其妙的神經過敏。早期射精的原因，不外是生理方面的男性包皮的關係和心理方面的精神作用。特就此兩點加以說明： 男性陰莖頂端的龜頭，由一種極似粘膜極富彈性也極富知覺神經的皮膚所被覆著， 所以正是刺激極為敏感的部分，在男子的發育期前，這個龜頭一直為包皮所覆蓋著，爾後逐漸成長的時候，便自然從包皮裏露出，因為這樣敏感的龜頭表面，經常被衣服類的摩擦刺激，其感受性也便逐漸遲鈍，僅於一些輕微的刺激，不會容易興奮的，這倒是將來性交時可以充分接受刺激摩擦的有利條件。反之，如果男性婚後仍在包莖狀態，則勃起後露出的龜頭，比沒有包童男性的更為敏感，只要稍有性交運動，甚至剛好結合的一瞬間，那龜頭所受刺激即刻達到極點，於是引起射精了。因此在青年時，若是包莖的話，須常使包皮後退為妙，同時這樣做法，亦可預防包皮內藏垢積汙而發炎。如果是嚴重的包莖（即勃起時包皮絲毫不後退），那便反而對刺激極為遲鈍感，對女性方面也減低興趣，因此凡是包皮過長，或是包莖的話，總以早請醫生手術割除為妙。這對性生活是很重要的一件事。
 
另一種起因於精神方面的早洩，則比較麻煩，因為那要先研究發生病態的精神方面的因素，這是另外一種專門學問，大概說來，在單身時期對於自慰行為所懷的不安與厭惡觀念，或對性交缺乏自信，或極度的女性崇拜，以及相反的女性厭惡，懷孕忌避，宗教戒律與性欲的矛盾等等內在的原因，另有性交時環境的不適當，有的怕被人窺視，有的懼怕音響的驚擾，這些都是可能引起精神變化的因素。 此外男性的早洩，可成為女性冷感症的原因，同時女性的冷感症，亦可成為男性早洩的原因。為要防備精神上起因的早洩，最好對性方面要有正確的認識，並且對性交要有自信。至其治療，則應請專家探究原因，對症處理，才能夠獲得圓滿徹底的解決。上面說了許多早洩的界說及原因，我們已有一個概念——早洩的情形中許多是錯誤的感覺，不是真正的早洩。
 
為了要排除此一夫妻間幸福的絆腳石，丈夫不妨作有計劃的延遲射精。為了達到上述目的，首先，男性要有一種堅定自信的意志，以便與妻子共謀高潮的一致，假如夫妻倆對性生活經驗不夠時，丈夫便很難體會到妻子是否要進人快感高潮的徵兆，在此經驗不足的情形下，最好是夫妻倆預先約定一個表達的信號，妻子應將自己快感高潮即將來臨的消息，向丈夫發出通告。 如果丈夫覺得這個信號來得太遲，便可變更性交的態位元和運動方式。因為夫妻間往往有些態位使男方比女方更受刺激，另一種態位卻恰恰相反，妻子較丈夫受到刺激為多。當然丈夫應該在此時選擇減少自己刺激而對妻子有極大刺激的態位來適應當前的環境。至於那種態位有理想的妙用，倒是因每個人而不同。要夫妻們平時在性生活中去體驗，作成一些屬於他們自己的結論，以便在運用上求得方便。
 
當丈夫在應用態位元變化的方法還不自如時，不妨採用一些轉移注意力的方法，如算一算數字，或在思考中臨時找一點小事情輕輕的在腦際掠過一下，也可以使自己對性交運動的反應遲鈍一些的。不過先得知道自己究竟是不是屬於神經質的人，如屬神經質的男性，可能因此意識的轉變，遭致勃起不完全或萎縮的變化，那是弄巧成拙了。對態位變化無經驗，而又屬於神經質的人，則不妨在性交運動中保持一些間歇的動作！即是略作短時間的停頓，這種短暫的停頓，使妻子有隔間的休息，便愈加期待和焦急，因而促進了她的性興奮，這是對夫妻雙方同時進人高潮的有效方法，不過，施行此方法時要注意，不能使這個間歇的時間太長，這樣會使妻子的興奮冷卻，那就太掃興了。最好在間歇時施以其他的愛撫刺激，以代替運動刺激，以保持妻子的興奮持續乃至昂進。在運動中另外還有一種克止早洩的技巧。如果丈夫認為淺近的插人或徐緩的運動是微弱的刺激，那是誤解的，因為一般來說，男性若是使龜頭面尤其是龜頭冠受到刺激，其所引起的刺激亦強，如果丈夫為避免防止早洩，僅使龜頭在陰道口，做著淺近的性交運動，則所帶來並不是弱小刺激的效果，反而成為互相間更強烈的刺激效果了。為了要達到延遲射精的目的，便可能因方法的誤解，得來相反的結果。因此，徐緩的前進，急速的後退，這種運動的方法倒也是防止早洩的好辨法，而且這種運動的效果，使妻 所受的刺激比丈夫為大，亦可以協調夫妻倆高潮的一致。在這種運動方式中，要前進時可以安步當車的前進，要後退時則迅雷不及掩耳的退卻，但不可使兒頭冠滑出陰道口為妙。 如果對上述兩種方法加以體驗和研究，依順著自己的意思去靈活運用，終可將射精這一過程延遲。
 
有人認為女人需要有一個具有「綿羊」、「小狗」、「老虎」三種個性的丈夫，才是真正的滿足，解釋是：第一要像綿羊般馴善，第二要像小狗般親熱，第三要像老虎般的兇猛。我想這個老虎般的兇猛，只有在性交的最後階段才是極需要的。 照上面所說，有計劃的去達到延遲射精，並不是一件難事。只要男性明白與女性一同所經驗到的快感高潮才算為完滿的快感高潮，儘量照此目標去做，在夫妻間建立許多有性經驗上的默契，則更為容易排除那夫妻幸福上的絆腳石——早洩——了。在性生活的過程中，除了早洩以外，還有一種「遲精」（遲洩）的病態，不過遲精的名詞也許還有許多人感到陌生，但這卻是性生活上一種不亞於早洩的病態。在性交進行中，這種病態如果超過了女性所渴望男性快點達到高潮的階段，就會由期待而變成勉強，由勉強而變成厭煩，由厭煩而變成失望，最後，終於由失望而變成痛苦的感受時，於是運精亦就成了幸福夫妻的一條裹腳布，說起來，這也是順理成章的事。 一般丈夫在房事生活中，患遲洩的人固然遠不如早洩的那樣普遍，但這卻是性生活上一種不亞於早洩的病態。「遲洩」的後果，更會容易招致性無能的病症的。關於夫妻從性器接觸後到丈夫射精，在這過程中，由於運動的技巧，對性知識的瞭解以及刺激程度的強弱的不同，都可使交合的時間發生延長或縮短的變化；但最大的影響，則由於丈夫本身大腦中的興奮情緒。不過，性交延長到一小時以上，夫妻倆仍是得不到快感洩精，或者雖有少許快感但卻射不出精，這就叫做「遲洩」的病態了。遲洩的起因，多半是運用遲延射精的錯誤，如誤用意識轉移，經常想到性交以外的事體上去，那麽一旦成了習慣之後，便不能隨心所欲去射精了。或者自己認為已經有辨法自由地做有計劃的遲延射精，就經常做著長時間的性交。其結果也可能會發生遲洩的現象。這時，雖然丈夫急切指望達到射精，結束這次性交運動，但他無論如何對性器加以強烈的刺激，總是不容易達到目的，等到他感覺得非常疲勞時，就不得不把運動中止，便成為一種不完全的性交，他將得不到性交真正的樂趣了。在女性方面，如果受到男性過份遲延射精的影響，弄成了一種習慣，使她老是在等 候她的丈夫的射精，以便一起接受快感高潮，那麽終於超過焦急，渴望的階段，以後，反而對性交刺激由勉強而感到痛苦。一般身為妻子的，在交合中總是等待著丈夫的射精；以便迎合快感高潮的一致，同享夫妻間幸福的樂趣；如果丈夫射精過遲（甚至無法射精），使妻子由期待而焦躁，於是不得不先進人高潮，這並不是妻子所願意的，在她的心理，總是希望與丈夫共同享受那快樂的瞬間。就丈夫的心理來說，對於妻子性高潮以後的射精，也與早洩一樣的索然無味。所以遲洩對夫妻幸福的關係，是十分重大的。遲洩，除了上述那種類型外，有時不論任何人，由於當時的肉體或精神條件的影響，也會有達不到射精的情形。這時候，如果盡用急速淩亂的前後運動，妄圖促進，反會使效果變低上？時應選擇男性最感刺激的體位，特別是對龜頭冠予以強烈的刺激，為要做到此地步，不要忘記應以陰道口為界，使龜頭進進出出，往往會收到促進射精的效果勃起不全與陽萎，是男性性機能障礙上的一種特別的病症，而且範圍很廣。勃起不全，有時還可以從經驗中求得要領，在技巧上講究方法，運用愛撫、吮吻等刺激手段，使丈夫在意識上充滿肉欲的衝動，以克服這種性機能的障礙；但是陽萎，除非有充裕的治療時間，則一時是無法克制的。
 
當夫妻們正在情切切，意綿綿，情欲的渴望已達到頂點，正需要求得滿足的當兒，而“那個”竟來了一個相應不理，任憑夫妻倆如何的愛撫與刺激，卻依然我行我素，那才是煞風景的事呢！陽萎的症狀差不多把性交的使命完全失去，不但夫妻間享不到性的樂趣，而且阻礙生育，因而釀成夫妻的不睦，增加煩惱，總之，它是家庭的攪亂者，幸福夫妻的剋星。要達到性交的目的，當然以丈夫陰莖勃起為絕對的必要條件，然而婚後日久，則丈夫的性欲不一定和勃起同時產生。大概一般妻子們都會瞭解，只要對丈夫生殖器加以愛撫，即可使其勃起，但卻有許多妻子，一日一使其勃起以後，便以為大功告成，立即急著要進行性交了，這是錯誤的，勃起並不是已有了性交意志。因為當丈夫的性器得到愛撫刺激，當然會勃起，但這情形和丈夫本身實在有了性欲而勃起的時候，大不相同。未必即刻就有性欲，這時急促地進行性交，是僅以意志的力量強行性交，不是自然的發展，對丈夫精神、健康都是有害的，在這種情形下，對妻子未必能滿足。所以妻子要想主動引逗丈夫時，同樣要注意到培養一種足以令丈夫性興奮的氣氛。除了病態的勃起不全外，在漫長的婚姻歲月中，往往由於精神或肉體上的條件一時不濟，使丈夫有偶然勃起不全的現象，這時候，不管妻子如何的愛憮刺激，總達不到性器結合的目的。即使是結合了，不久就會萎縮下去，性交也無法持久。在這樣的時候，應該讓丈夫作充分休息，不宜勉強施行性交，尤其不要表示不滿的態度，甚至隨便批評，如果傷害了丈夫的自尊心，便會使他失去——倍，可能因生理上的勃起不全，懷疑到病理上的勃起不全，因而神經過敏，轉人病態了。
 
此外有一種近於猥褻的方法，對勃起不全可以振奮的，那就是性器接吻，用嘴去吻性器，對性的刺激是十分熱烈的。後天性陽萎的原因，有因生殖器疾病的反常，有因勃起中樞興奮性的缺乏，有因反射神經的障礙。生殖器的疾患，及反常的陽萎，可分作十數種。重的，是器質的陽萎，是生殖器反常畸形，或疾病的變化而得的。這是指那陰莖缺損，發育不全，高度彎曲， 陰莖破裂，包莖等的陽萎而說的。依勃起中樞興奮性的缺乏的陽萎，多半是性欲減退，或完全失去的。因為攝護腺部或尿道腺部的慢性淋病、梅毒、結核、腎臟病、溢血病、脊髓炎、肥胖病等疾患，性的昂奮完全受了妨礙。失去了性欲中樞的刺激，而發生陽萎。但其他麻醉品如咖啡等的中毒，也是原因之一。尤其是因手淫和性交過多，勃起和射精中樞失去了昂奮作用，而發生了陽萎，這名叫麻痹性陽萎。反射作用的神經障礙，是因驚悸、苦慮、羞恥、激怒、恐怖等強度的精神感動而成了的陽萎；也有純真的青年，深怕梅毒，為一種脅迫觀念所襲，因而成了陽萎的；還有埋頭於科學的發明，把精神集中於某方面的結果，因而發生陽萎的。實在是不勝枚舉。陽萎的治療，並不是藥物上問題，而是時間上的問題，譬如像馬錢子那種藥。一般人以為它是治療的良藥，其實它對性器官及中樞神經只有刺激作用，如果本來是興奮過度的陽萎，用它比不用它更壞。所以在治療之先，必須求教於醫生，瞭解那個致萎的原因，在醫療時期，必須慎守攝生的規則，對於有刺激的食物，諸如油、酒、辣椒等類，應完全禁絕，多食蛋白質和富有營養之食物，並行冷水浴，經常以冷水毛巾洗擦陰部，也是有效的療法；神經性的陽萎，應特別把生活弄得很有規律，每晨作適當的運動，選擇清淡的食物，避免身心的過於疲勞，這是很好的自律療法；但是有慢性淋病攝護腺炎等病的人，對於運動是不可不考慮的。患陽萎的人，應該禁止性交，因為性交會使病更趨嚴重的，尤其不能去找妓女。長時期的想念著性交的欲望，焦急、煩惱，一切精神上的緊張都是不利的
　
** 女性行房的最佳時辰
 
素女曰求子法自有常體清心遠慮安定其矜袍垂齊戒以婦人月經後 三日夜半之後雞鳴之前嬉戲令女盛動乃往從之適其道理同其快樂 卻身施寫勿通遠至麥齒遠則通子門不入子戶若依道術有子賢良而 老壽也。
 
素女說：「求子的方法，自有其一貫的法則，身體輕快，心無憂慮，情緒平靜，衣冠整齊，專心齋戒，當女人月經完畢的三天之後，即深夜過後，雞鳴之前，開始撫愛。先使女人漸漸興奮，接著方行做愛，按照房中術的道理，共同享受其間的快樂。洩出精液時陽具不要從小陰唇拉出外面。因為抽出過度時，會脫離子宮門，精液就進不去子宮假如依照這種技術而得子的話，那他一定是一個很傑出而且很長壽的人。」
 
彭祖說女人月經完畢後的第十五天夜半受船時，可以生下一個聰明伶俐，長壽而且高貴的兒子。但素女卻以為月經完畢後的第三天性交。這對於現代人來說，還算比較實際可行。夜半後，天亮前的時刻，會使人有奇異的感受，所謂夜半，就是子時（午後十一時 起至午前一時）為止，接著就是丑時（午前一時至三時止），天亮就是寅時（午前三時起至五時止）。因此，夜半後，天亮前正是丑時的時間。這段時刻之所以很好，乃是因為這段時刻跟肝有關係。而肝跟持久力又是關係最密切的。肝也與性器的脈脈連通。這個時刻的中心為午前二時，在這個時辰裏，肝的經脈流動最好，睡眠也很充足，故是最理想的做愛時間。素女經說，陽具的淺進方式比較容易受胎，這恐怕是根據古代性生活的經驗得來的
　
** 如何才有好胎
 
素女曰夫人合陰陽當避禁忌常乘生氣無不老壽若夫婦俱老雖生化 有子皆不壽
 
素女說：「人類為了要符合陰陽之道，一定要避免若干禁忌。當氣勢最好時，生下的孩子，通常都會長壽的。如果夫婦都很年老，即使在氣勢最佳時，生下孩子，也都不會長壽的。」
 
在氣勢最佳時做愛生下的孩子是很健全的，由於自古以來，年輕得子都很健全的緣故。假使很年輕，但若身體不適，或在酒醉時也不能做愛的。假如雙親的氣勢不是很好，那是因為身體欠佳。所謂氣勢，乃是精力飽滿，這是男女做愛的最佳條件，故能給予受胎很好的影響。
 
素女經雖沒提到年齡問題，但在《玉房秘訣》裏認為男女年紀太大時所生下的孩子不能長生，素女經說八十歲的男子，娶一位十七、八歲的少女，也照樣能生子。反之，五十歲的女性跟年輕丈夫也會生育子女。男人八十歲結婚而生子的人有卓別林，還有一位日本東都清水寺的管長——大西良 慶師，他七十五歲，娶一位二十三歲的年輕太太，到了八十六歲，才生下了孩子。
 
卓別林是一位貧窮年輕的猶太人，他後來成為國際聞名的電影明星，但終身追求食欲、工作和戀愛。大西師也一樣，當他年輕時，曾經被女人叫做大西惡慶，可見他在男女關係方面，真是聲名狼狽！ 總之，他們兩人自年輕時代開始，就對於女人相當精進。所謂「精進」者，乃是指性能力很實在，而且容量豐富。即使年屆高齡，也依然能生貴子。所以，我們各個年代的人，對於性的知識，也一定要有相當研究才好。
 
** 令人心動的女人
 
黃帝曰入相女人云何謂其事素女曰入相女人天性婉順氣聲濡行絲 發黑弱肌細骨不長不短不大不小鑿孔居高陰上無毛多精液者年五 五以上三十以還未在產期交接之時精液流漾身體動搖不能自定汗 流四逋隨人舉止男子者雖不行法得此人由不為損
 
黃帝問：「所謂長相令人喜愛的女人，到底是指些什麽呢？」
 
素女回答：「所謂長相令人喜歡者，就是天性溫和，聲音不乾涸，頭髮細黑，肌肉柔軟，骨骼精細，身體不高不矮，不胖不瘦，小腿結實，陰戶局部不長毛，而且黏液一直好像水溝一樣濕濕地，年紀大約在二十五到三十歲之間的未婚女人。她們做愛時，津液濕潤，身體擺動得不自己，汗流滿身，任男人去擺佈，而且還會隨著男人的意思而行動。如果男人獲得這種女人的話，即使沒有遵循交合的規則，也不會損壞身體的。」
 
素女對於黃帝問題，曾舉出各種條件，並且解釋得好像女體浮現在眼前那樣生動。大體來說，音域遼闊而且響亮，才是女中豪傑。當她一出聲，就有充份的準備。「恥丘殷實」，若以別種表現法，則相當於「陰戶向前」的意思，乃是骨盤構造的特徵。「九法」中的第三項——猿搏的姿態，與第五項——龜勝的姿態等屈曲位，這些都近於正常位，也是在春宮書裏常常被人描寫的體位。有人說：「好淫者，牝上不長毛。」這就是說好淫的女人，陰部不長毛。據計牝毛的數量，跟眉毛和手腳的體毛幾乎成比例。
 
在中國稱女人的同性愛為「磨鏡」，這是由於無毛被視為當然而引起的。在我國古代的醫學書裏，認為鑒定一個女人的好壤，首先要詳細調查她陰戶與腋下的毛髮。如果毛發軟軟地，靜靜地，則那個女人就屬於上品。同時，如果她的發色是紅的，這是表示會損壞男身的象徵。所以，紅發是被男人所忌諱的。
 
「白、鼓、軟、紅、緊」五字的排列順序，也就是表示被男人喜愛的情況。此外，聲音要細，也就是說女人的嘎聲是好的象徵。假如男人獲有這種條件的女人，他不但會樂此不疲，而且還能飽養精氣，延年益壽。曾有一本《雜事秘辛》的書，內容記載後漢恒帝的選妃標準，女人身上各部份的尺寸，都被記得很具體。例如：「肩寬一尺六寸，屁股比肩寬少三寸，從肩到手指上，各長為二尺七寸，指離拿四寸，細小比較受人歡迎，從腿到腳止的長度是三尺二寸，腳的長度八寸，脛與甲要肥而豔，腳底很平，腳指很短，沒有黑子與麻子……」 現在傳說的仙道，也就是古代的房中術，它說能否給予男性某種陽氣，這完全要看女人的條件是否被男人看中來決定。
 
照古代房中術的說法，擇伴時要考慮以下四個條件——眉清、目秀、唇紅，齒白。這四個條件說來真是有趣。
 
首先是眉毛，凡是一字眉的女人，被認為性交技術不佳，缺乏羞答答的姿態，不能得到男人的歡心。兩邊的眉毛相系的女人，其持續力衰弱，而且神經質。除了八字眉外，只有眉毛叢生的女人才最喜歡陰陽交接之道，她的床上工夫會使得男人如醉如癡。這種女人的眉叫做「眉清」。此外，瞳偏向上方，好像怪眼的下三白眼，或使媚眼兒的女性也會令男人銷魂。這種女人稱為「目秀」。瞳偏向下方的上三白眼的女人，則會使男人身體衰弱和生病，所以要嚴加警惕才好。口唇血紅，或者口唇紫色的女人，容易引起心臟麻痹。但只有紅色的口唇，才是一個健康女性的象徵，這種女性的口唇，稱為「唇紅」。齒列漂白的女人，可謂陽氣飽滿，齒與腎的關係很深。當列不好的人，常因病弱而不能過度做愛。
 
從《肉蒲團》書中，獲悉男人最喜歡的女人，乃是平凡而新鮮，即要求精通床上工夫的意思。有位名叫花辰的女人，她曾授與未央生的真傳：「要先看書，接著一面行陰陽之道 ，一面要讀書和聽聲音。」不過，一般人看過了幾張圖和幾本書後，就沒有作用了。應當備上數百張，或數百冊書，要先看看畫，但不宜很快進人陰陽之道的境界，僅在十分興奮時進人陰陽之道。在這一進一出的狀態中，一面互相讀書和聽聲音。待人興奮狀態，才開始運動。但是，事情並非如此繼續下去就好，而是暫停片刻，讓陽具依然放在陰戶裏，再次看書讀書。此外，再聞聲音，也就是聽人的聲音，當然是指聽在陰陽道上那個人的聲音，而且單人做亦可。花辰叫女傭人單獨使用道具，照這種方式表演。未央生在世時，所謂看、讀、聽的動作，其實不過如此罷了。現在也是花樣百出，花辰的方法，正是好好利用男人喜愛的，女性之床上工夫，「溫故知新」就是指這件事而言。素女說男人所喜愛的條件，也是指男人喜歡一個能給自己快樂，與長壽的女人。其次，素女也從房中術談到一般交接的禁忌。所謂禁忌者，乃是指陰陽道理論，以及根據這個理論而來的民信仰。例如素女經雖也提到房事的禁忌日期等，但由於此中迷信味道很濃，所以這部份的原文恕不贅述。《玉房秘訣》有下面一段有趣的敍述：「姦淫所以不能長生者，不但是觸怒鬼神，而且自作自受。如放入粉末的媚藥，或用象牙做道具來用，都會衰老，甚至夭壽。」由此可見這是放入媚藥以及使用道具的情況。媚藥者雖然詳情不悉，但這是男性用在增強性欲，好像西方王母陰道中放的乾棗等。
