* 荣枯鉴

** 作者简介

冯道，八八二年生，九五四年卒,享年七十二岁，生逢五代乱世，自号长乐老。一生事五朝（后唐、后晋、后汉、后周和契丹）、十一帝（唐庄宗、明宗、闵帝、末帝，晋高祖、出帝，汉高祖、隐帝，周太祖、世宗，辽太宗耶律德光），前后三十一年。五代总共五十四年，冯道历经大半。

冯道著《荣枯鉴》，曾国藩称：“一部《荣枯鉴》，道尽小人之秘技，人生之荣枯。它使小人汗颜，君子惊悚，实乃二千年不二之异书也。”

** 圆通卷一

*善恶有名，智者不拘也。*
善恶这种事儿都有个定义，但真正有智慧的人根本不理会。
 
*天理有常，明者不弃也。*
世上什么事儿都有个规律，真正的明白人不会随意视而不见、自以为是。
 
*道之靡通，易者无虞也。*
是不是合乎道理，顺应变化的人根本也不关心这个。
 
*惜名者伤其名，惜身者全其身。*
珍视名声者，名誉易损，爱惜自己者，保全自身。
 
*名利无咎，逐之非罪，过乃人也。*
名利不是坏事，追名逐利也不是罪过，以此为恶是人的主观想法而已。
 
*君子非贵，小人非贱，贵贱莫以名世。*
君子没什么可自以为尊贵的，小人也没什么低贱的，尊贵还是低贱都是虚名，不足以称道一世。
 
*君子无得，小人无失，得失无由心也。*
君子不一定就能得到什么，小人也不一定会失去什么，得到、失去，跟思想境界也毫无关系。
 
*名者皆虚，利者惑人，人所难拒哉。*
名誉都是虚的，利益才能真正诱人，是人就难以抗拒。
 
*荣或为君子，枯必为小人。*
事成显贵的，有可能会被传颂为君子；身败落魄的，必定会被当作小人。
 
*君子无及，小人乃众，众不可敌矣。*
因此，君子永远是少数（因为即使成功也不都是君子），小人永远是多数，多数人的力量，无可抗拒。
 
*名可易事难易也，心可易命难易也，人不患君子，何患小人焉？*
名誉容易转变，思想境界可以变化，但事情的成败、人生的命运，却难以更改。反正君子小人不是根本问题，你觉得当君子受苦没有什么不好，当小人来享福又有什么可怕的呢？反正名誉根本都不靠谱。
 
** 闻达卷二
 
*仕不计善恶，迁无论奸小。*
做官不做官，升职不升职这类事情，根本不是以善还是恶、君子还是小人来作为判断标准的。
 
*悦上者荣，悦下者蹇。*
让上边的领导高兴的，日子必定好过；让下边的群众高兴的，碰到的困难却会更多。
 
*君子悦下，上不惑名。*
君子让下边的群众高兴，可上头的领导并不觉得你在群众里的好名声有什么意义。
 
*小人悦上，下不惩恶。*
小人讨好上头的领导，下边的群众可能会反感，但是，这样的反感并不能对你有任何损伤。
 
*下以直为美，上以媚为忠。*
下边的群众以道德高尚刚正不阿为美德，上头的领导会把谄媚顺应当做忠诚。
 
*直而无媚，上疑也；媚而无直，下弃也。*
道德高尚，但是毫不顺应领导，上头就该不信任你了；顺应领导，但是让下头人觉得你不地道，下头人就该反对你了。
 
*上疑祸本，下弃毁誉，荣者皆有小人之谓，盖固本而舍末也。*
可是，上头不信任你，你就完了——这是根本，下头反对你，顶多是给你来个坏名誉——无所谓的事儿。因此，那些功成名就大富大贵的人都难免被人称作小人，就是因为他们选择了保住根本，顾不得那些没有意义的名誉了。
 
*富贵有常，其道乃实。*
想富贵么？规律很简单：一切从实际出发。
 
*福祸非命，其道乃察。*
祸福其实并非命运注定，也有规律可循：看你是否善于观察和判断。
 
*实不为虚名所羁，察不以奸行为耻。*
一切从实际出发，就别受那些毫无实际意义的虚名的束缚。善于观察判断，就别老以坏人坏事为耻辱，那会搞得很不客观。
 
*无羁无耻，荣之义也。*
没有名誉的羁绊，没有耻辱感的束缚，你离显贵发达也就不远了。
 
*求名者莫仕，位非名也。*
要是真想追求名誉，你就别去当官，好名誉不是当官儿可以当出来的。
 
*求官者莫名，德非荣也。*
要是真想当官，你就别管什么名誉了，道德高尚跟富贵荣华是两码事儿。

*君子言心，小人攻心，其道不同，其效自异哉。*
君子讲的是道德、理念，小人则专门对付这种道德理念，价值观不同，行为不同，结果自然不同。
 
** 解厄卷三
 
*无忧则患烈也。*
什么都不操心，你就离倒霉不远了。
 
*忧国者失身，忧己者安命。*
不过，操心根操心不一样。为国家操心的人，只能把自己搭上；为自己操心的人，却能乐享安然。
 
*祸之人拒，然亦人纳；祸之人怨，然亦人遇。*
祸事是人不想要的，但也是人自找的，人人都讨厌有祸事，但人人都难免碰上。
 
*君子非恶，患事无休；小人不贤，余庆弗绝。*
君子不做坏事儿，但倒霉事儿一个接一个，小人不干什么好事儿，却能够常年乐呵呵。
 
*上不离心，非小人难为；下不结怨，非君子勿论。*
让上头领导对自己完全放心，不是小人就难以做到；让下头群众不怨恨自己，不是君子您就别想了。
 
*祸于上，无辩自罪者全。祸于下，争而罪人者免。*
上头要找别扭的时候，只有装孙子认罪才能保全自己；要是下头起了负面意见，就只有抢先把责任推到别人头上，装好人，才能免去责任。
 
*君子不党，其祸无援也。小人利交，其利人助也。*
君子不爱拉帮结伙，所以，真有了祸事，没人会帮助君子。小人有一大帮酒肉朋友，成事解围，全都靠这帮人帮助。
 
*道义失之无惩，祸无解处必困，君子莫能改之，小人或可谅矣。*
不讲道义不会造成什么实际的恶果，有了祸事没人帮可就必然倒霉。做君子倒了霉只能束手无措，所以，大家选择做小人，也就是可以理解的了。
 
** 交结卷四
 
*智不拒贤，明不远恶，善恶咸用也。*
真正的聪明人不拒绝好人，也不疏远坏人，这两款都有用。
 
*顺则为友，逆则为敌，敌友常易也。*
都是拿顺应自己的人当朋友，拿反对自己的人当敌人——敌人朋友是随时可以转化的。
 
*贵以识人者贵，贱以养奸者贱。*
用尊重的态度看待别人的人，日后将发达显贵，用轻贱的态度对待别人，日后难免潦倒。
 
*贵不自贵，贱不自贱，贵贱易焉。*
显贵的人不自重，不知道摆出个尊贵的样子来，而潦倒的人不做轻贱别人的贱事儿，贵贱就该掉个儿了。
 
*贵不贱人，贱不贵人，贵贱久焉。*
显贵的人永远不轻视别人，潦倒的人永远不尊重别人，贵贱就这么一直下去了。
 
*人冀人愚而自明，示人以愚，其谋乃大。*
人盼着别人傻自己聪明，但还是成天装傻给人看，这是真正有主意的人。
 
*人忌人明而自愚，智无潜藏，其害无止。*
不乐意别人机灵自己傻，就玩儿命抖机灵，这就纯属作死。
 
*明不接愚，愚者勿长其明。*
聪明的人不接触傻子，接触傻子不会让聪明人变得更聪明。
 
*智不结怨，仇者无惧其智。*
有智慧的人不跟人结仇，仇人不会因为你聪明就怕你。
 
*君子仁交，惟忧仁不尽善。小人阴结，惟患阴不制的。*
君子人用仁义与人交往，生怕自己不够仁义；小人满怀阴损与人交往，生怕阴损的不够，达不到目的。
 
*君子弗胜小人，殆于此也。*
君子注定吃小人的亏，就是因为这个。
 
** 节仪卷五
 
*外君子而内小人者，真小人也。*
外表君子作派，内心小人肚肠的，这是真小人。
 
*外小人而内君子者，真君子也。*
行事手段并不比小人差，内心却有君子情怀的，这才配称真君子。
 
*德高者不矜，义重者轻害。*
道德高尚的人以道德高自居，就不太知道保重自己，看重仁义的人太重仁义，总是忽视自己面对的危害。
 
*人慕君子，行则小人，君子难为也。*
人们满嘴说的都是仰慕君子，办出来的却还都是小人事儿，那谁要真当君子，谁就该倒霉了。
 
*人怨小人，实则忘义，小人无羁也。*
人们口口声声憎恶小人，实际上做事情还是不仁不义，也就是说，做小人其实是没有任何阻碍的——憎恶全是空喊。
 
*难为获寡，无羁利丰，是以人皆小人也。*
可谁也不愿意当倒霉蛋，因为倒霉蛋比别人倒霉，谁都愿意没有任何阻碍，因为没有任何阻碍就比别人牛B，所以，所有人就都成了小人了。
 
*位高节低，人贱义薄。*
社会阶层越高，气节越低——因为要装孙子；人越贫贱，义气越是狗屁——因为先要活着。
 
*君子不堪辱其志，小人不堪坏其身。*
君子最受不了的是精神屈辱，小人最受不了的是身体上的困苦。
 
*君子避于乱也，小人达于朝堂。*
所以，一有乱子，君子就躲起来自保高洁去了，小人却常能当上国家领导。
 
*节不抵金，人困难为君子。*
气节比不上金钱实在，所以，人一穷了，就做不成君子——因为讲不起气节。
 
*义不抵命，势危难拒小人。*
义气也不如生命重要，所以，身处危困就没办法不当小人，因为活命更重要。
 
*不畏人言，惟计利害，此非节义之道，然生之道焉。*
不管别人如何夸奖或批评，只管自己的利益存亡，这不是追求气节仁义的道理，却是能让你安身立命、生存下来的道理。
 
** 明鉴卷六
 
*福不察非福，祸不预必祸。*
有福气，可你自己不知道，这就白费。有祸事，你自己不能预先避免，那就准得倒霉。
 
*福祸先知，事尽济耳。*
要是福祸都能提前预知，那就牛B了。
 
*施小信而大诈逞，窥小处而大谋定。*
偶尔装装实在，大阴谋就能得逞；多偷偷看看细节，大的决策就能搞定。
 
*事不可绝，言不能尽，至亲亦戒也。*
做事情要留后路，说话要留半句，纵然是亲爹也得防着点儿。
 
*佯惧实忍，外恭内忌，奸人亦惑也。*
心里头有火儿也要憋着，假装畏惧，心里头满是仇恨也得藏着，假装恭敬，您要能这么办，坏心眼儿再多的人也得上当。
 
*知戒近福，惑人远祸，俟变则存矣。*
知道克制自己的表现、学会迷惑人，就可以少惹事儿、多成事儿了——反正就是得会变化、会掩饰，您就放心大胆的活着吧。
 
*私人惟用，其利致远。*
只跟用得上的人套近乎，讲交情，这是可以长远地对你有利的。
 
*天恩难测，惟财可恃。*
别指望领导的保护，包括领导在内的一切都是钱的孙子。
 
*以奸治奸，奸灭自安。*
用坏人治坏人，坏人被整死了，整人的那位自己也知道了厉害，也就老实了。
 
*伏恶勿善，其患不生。*
别干什么坏事儿，但也别傻了吧唧干什么好事儿，这样就能永远不惹事儿。
 
*计非金者莫施，人非智者弗谋，愚者当戒哉。*
计策不牛逼，就别一条道走到黑；要是知道谁傻B，就别跟丫商量事儿，珍惜生命，远离傻B——如果您自己脑子就不怎么好使，那就更得注意以上这两条儿。
 
** 谤言卷七
 
*人微不诤，才庸不荐。*
职位低贱的人，没必要老给他提意见帮助他成长，真没什么本事的那些货，也别到处瞎推荐，推了也没用——该整的要整，该毁的要毁。
 
*攻其人忌，人难容也。*
攻击一个人，就找他最遭人羡慕嫉妒恨的那一点，大伙儿就都帮你毁他了。
 
*陷其窘地人自污，谤之易也。*
或者把他推到一个进退两难怎么办都只有难办的境地，别人就会替你开始戳他脊梁骨了，这是简易诽谤法。
 
*善其仇者人莫识，谤之奇也。*
好好对待那些跟他有仇的人，他们早晚会跳出来毁他，而别人又不知道跟你有关系，这就又上一个层次，算是奇招了。
 
*究其末事人未察，谤之实也。*
把别人不知道的他干过的各种小事儿揪出来，挑出毛病公诸于世，这是实在有效的毁谤法。
 
*设其恶言人弗辩，谤之成也。*
把关于他的种种坏话全给散播出去，真真假假的谁也分辨不了，这算直接毁谤成功了。
 
*谤而不辩，其事自明，人恶稍减也。*
被人毁谤，要是不争辩，只等事实慢慢儿冒出来，旁人的厌恶或许还能稍微减少一些。
 
*谤而强辩，其事反浊，人怨益增也。*
可要是他非争辩不可，只能是越描越黑，纯属找死。
 
*失之上者，下必毁之；失之下者，上必疑之。*
上头对谁印象不好了，你看着吧，很快下边的人也该开始毁他了。同样，要是下头的人对谁不满意了，上头很快也将对这人产生怀疑。
 
*假天责人掩私，假民言事见信，人者尽惑焉。*
借助上头的意见打压别人实现自己的目的，或者借助下头的舆论来说事儿讨取上头的信任，任谁都得上当。
 
** 示伪卷八
 
*无伪则无真也。*
没有虚假，也就没有真实。
 
*真不忌伪，伪不代真，忌其莫辩。*
真的不怕假的，因为假的无论如何也真不了，怕的是真真假假掺合一块儿分不清楚。
 
*伪不足自祸，真无忌人恶。*
虚伪却又虚伪的不够，那就会给自己惹祸；真诚要是真诚到毫无忌讳，那就是缺心眼儿。
 
*顺其上者，伪非过焉。*
顺应上头的意思，哪怕是装的，也不是什么过错。
 
*逆其上者，真亦罪焉。*
悖逆上头的意思，哪怕是真诚，也是找倒霉。
 
*求忌直也，曲之乃得。*
要求什么东西，别说的太直了，用点技巧含蓄点，才容易成功。
 
*拒忌明也，婉之无失。*
拒绝什么东西，也别有什么说什么，委婉点儿，照样能达到目的。
 
*忠主仁也，君子仁不弃旧。*
“忠”往往会指向“仁”，仁厚的人不忍弃旧，自然也就忠了；
 
*仁主行也，小人行弗怀恩。*
“仁”往往就要起而行之，君子知道通过行动来感恩，这就是仁，而小人就不会这样。
 
*君子困不惑人，小人达则背主，伪之故，非困达也。*
君子落魄了也不会骗人，小人一发达了就开始在主子背后耍花活，这是因为君子不虚伪、小人虚伪，跟发达不发达毫无关系。
 
*俗礼，不拘者非伪；事恶，守诺者非信。物异而情易。*
如果是虚礼俗套，一副浑不吝偏不服就跟别人不一样的姿态，也不算什么虚伪，明明是坏事儿，还说一不二一条道走到黑的，也算不上什么实诚，得具体问题具体分析。
 
** 降心卷九
 
*以智治人，智穷人背也。*
用智慧来管理下属，智慧什么时候枯竭了，那些人也就都背弃你了。
 
*伏人慑心，其志无改矣。*
改用攻心，让他们从心里、从灵魂深处被慑服住，那么无论什么时候他们也不会改变方向了。
 
*上宠者弗明贵，上怨者休暗结。*
被上头宠信的人，别太拿自己当回事儿；被上头瞧不上的，也别私下解党与上头作对。
 
*术不显则功成，谋暗用则致胜。*
权谋手段，隐蔽的好才能成功，要悄悄地来，打枪地不要。
 
*君子制于亲，亲为质自从也。*
君子的弱点在于他们珍爱亲属，拿他们亲属做人质相要挟，也就从了。
 
*小人畏于烈，奸恒施自败也。*
小人的弱点在于害怕比他们更狠的，你就比他们更恶毒，他们就服了。
 
*理不直言，谏非善辩，无嫌乃及焉。*
说理、劝谏不一定是有什么说什么或者跟人争辩，别遭人恨才能达到目的。
 
*情非彰示，事不昭显，顺变乃就焉。*
有什么态度、做什么事情，也没必要先弄得天下人都知道，顺应形势该藏着就藏着才能成功。
 
*仁堪诛君子，义不灭小人，仁义戒滥也。*
仁义二字，能够拖累死君子，却灭不掉小人，还是不要滥施仁义，适度才好。
 
*恩莫弃贤者，威亦施奸恶，恩威戒偏也。*
施好处别忘了那些你以为不喜欢好处的好人，惩罚措施也别忘了给那些谄媚的坏人来点儿，好事儿坏事儿得掺合者来，得让吃肉的也挨挨板子，挨板子的也来点儿肉尝尝。
 
** 揣知卷十
 
*善察者知人，善思者知心。*
善于观察，就能了解人，善于思考，你才能理解人。
 
*知人不惧，知心堪御。*
了解了他们，你就不会怕他们了；理解了他们，你就已经能搞定他们了。
 
*知不示人，示人者祸也。*
智慧别让别人看见，让别人看见就会惹祸。
 
*密而测之，人忌处解矣。*
偷偷地猜度、揣测，不让他们知道，人们对你的嫉恨就会消除掉。
 
*君子惑于微，不惑于大。*
君子总是在大事儿上明白，小事儿上糊涂。
 
*小人虑于近，不虑于远。*
小人总是在眼前事儿上考虑多，未来的事儿上考虑少。
 
*设疑而惑，真伪可鉴焉。*
掌握了这个规律，制造些问题给他们，看看他们的反应，你就知道谁真诚谁虚伪，谁是君子谁是小人了。
 
*附贵而缘，殃祸可避焉。*
然后认准你觉得有前途的、能富贵的，攀附一下，以后的祸事就可以避免了。
 
*结左右以观情，无不知也。*
结交各路朋友，留神各路的消息和反映，那就什么事儿也瞒不过你了。
 
*置险难以绝念，无不破哉。*
常如身处险境般心存忧患，抛掉无关的累赘想法——恭喜您，您已经神光护体，攻无不克了。

** 后记

《荣枯鉴》为五代时的“四朝元老”冯道所著，全书分十卷，分别名之谓“圆通”、“闻达”、“解厄”、“交结”、“节义”、“明鉴”、“谤言”、“示伪”、“降心”、“揣知”，一开卷就直截了当：“善恶有名，智者不拘也。天理有常，明者不弃也。道之靡通，易者无虞也”，把“原则”的“不拘”和“变易”视为当然，以这样直言不讳的“义理解构”开宗明义，奠定了全部言说的基调。全书约三千言，除了“君子”、“小人”这两个名词似源儒学本义外，几乎于礼教无涉。

它言说“圆通”，不批“圆通”，只说“名者皆虚，利者惑人，人所难拒哉……名可易事难易也，心可易命难易也，人不患君子，何患小人焉？”——说法是空的，利益的诱惑是实在的；说法变来变去，人们该怎么办还怎么办——揣诸生活常识，你说是耶非耶？

它透视“闻达”，不作褒贬：“悦上者荣，悦下者蹇。君子悦下，上不惑名；小人悦上，下不惩恶……上疑祸本，下弃毁誉，荣者皆有小人之谓，盖固本而舍末也。”——一个人是受上峰赏识还是受下民拥戴，其命运就大不相同；看重名节毁誉的君子与看重利害得失的小人，其生活遭遇否泰悬殊——在一个权力本位且由最高权力者“口含天宪”的社会结构中，这是不是事实？

它试图“解厄”，冷峻异常：“忧国者失身，忧己者安命……君子不党，其祸无援也。小人利交，其利人助也。”——注重道德操守的“君子”容易招灾惹祸，善于搞利益交换的“小人”却每每如鱼得水——古往今来，这样对比鲜明的事例，难道还少吗？
 
它剖析“结交”，不留情面：“顺则为友，逆则为敌，敌友常易也……人冀人愚而自明，示人以愚，其谋乃大；人忌人明而自愚，智无潜藏，其害弗止。”多附和人家就广交朋友，说人家的不是则容易树敌；装傻守拙容易谋得利益，而显得聪明了往往要吃亏——以此衡量各自接触过的种种“圈子”，把“对不对”的判断暂时放到一边，你说这些话准还是不准？

它拆解“节义”，坦率清晰：“位高节低，人贱义薄。……不畏人言，惟计利害，此非节义之道，然生之道焉。”——爬得高的人肯定付出了道德上的代价，地位低的人很难追求什么崇高目标；多算计利害而少一些道德顾忌，或许不合什么风范，但这是过好日子的窍门——我们将社会阶梯上下打量一下，或者看看“守法都成竞争劣势”的非规范竞争现实，还能说它是瞎话吗？ 

——象这样冷峻、客观、低调、切实的陈述和分析，《荣枯鉴》中比比皆是，如果一一引述，这帖子就太长了。但我在写这篇读后感时，写着写着就生了推荐之心，唯愿所有心性良善尚却不谙世情的朋友都来读读这本书。因为，象这样的言说方式，从难以回避的生活现实中剖析真实，与揪着人离地的说教大唱反调，在我们这个崇尚“文以载道”的文化中，本来就很少见，再加上一些人奉行什么“教育人、引导人”的“舆论导向”，真话就更不易听到。但空洞的教义无助于严酷的生活，轻信高调甚至是打拼人生时的美丽陷阱，这于今天的许多人来说，早已是心照不宣的常识。缄口不宣易，而违拗常识难，于是就阳奉阴违，说一套做一套，昧良心说假话成了迫不得已的选择，反而从根本上摧毁了道德底线，其结果就是越来越普遍的道德沦丧，让口是心非成了社会常态。李贽批评明朝士大夫们“阳为礼教，阴为富贵”；严复感慨“华风之敝，八字尽之：始于作伪，终于无耻。”——验之于当今，历史的积弊到底是在减少还在增加呢？ 

为此，我从《荣枯鉴》其后五卷中各摘一句罗列于后，是良药还是毒饵，请诸君自品——

“事不可绝，言不能尽，至亲亦戒也。”（明鉴卷六）

“失其上者，下必毁之；失于下者，上必疑之。”（谤言卷七）

“求忌直也，曲之乃得；拒忌明也，婉之无失”（示伪卷八）

“仁堪诛君子，义不灭小人，仁义戒滥也。”（降心卷九）

“君子惑于微，不惑于大。小人虑于近，不虑于远。（揣知卷十）

冯道生活的五代，是中国历史上最动荡的时期之一。他出生寒微，也曾仕途坎坷：坐过牢，打过仗，遭过权贵之嫉，三遇亡国之祸，还替“儿皇帝”石敬塘出使契丹，颇似黄郛替蒋介石的“交涉日本”，帮得罪不起的当家人背了千古骂名。但他终能履险如夷，得以善终，在后唐、后晋、后汉、后周四个王朝都官至宰相，位极人臣。《旧五代史·冯道传》赞曰：“道之履行，郁有古人之风；道之字量（器量），深得大臣之体”，可以想见其当年的官声很不错；《新五代史》载：冯道死后，“时人皆共称叹，以为与孔子同寿，其喜为之称誉盖如此。”冯也自命“长乐老”，在《长乐老自叙》中对一生颇为自得。从以上所述来看，他似乎有骄傲的理由。将自己在乱世中远害全身的心得写下来，供他人参考，不也是一种实实在在的智慧总结吗？

在正统史官们的笔下，“长乐老”的形象并不好。这固然与冯道“事四朝，相六帝，可得为忠乎”的履历有关（见于薛居正：《旧五代史·冯道传》中的评价），但这种将生活放在礼教之上的态度，也是遭人诟病的重要原因。欧阳修编《新五代史》时，斥冯道为“无廉耻者”；司马光在《资治通鉴》中，更骂他是“奸臣之尤”；一直到范文澜写《中国通史》，仍不胜鄙夷地说：“想到冯道，就会想到官僚是多么可憎的腐朽物”。史官们骂他，认为他的多变无节的政治表现，不可饶恕的品格问题，但葛建雄教授在其所著的《乱世的两难选择》中说得好：“冯道一生所事四朝，合计不过三十一年，如果他生在康熙、乾隆时代，他的一生仕途，刚刚超过皇帝享国时间之半，不用说换代，还等不到易君……冯道除非住进桃花源，或者悠游林下，否则总得为这些皇帝效劳。”——换句话说，是皇帝们自己不争气，没法让身为宰辅的人尽忠，不幸而伴上了这些目不识丁、鲜廉寡耻而又杀人不眨眼的皇帝，不愿象王子比干、范滂、李膺那样的愚忠，有何不可呢？如果以为唐末帝李丛珂、晋出帝石重贵、汉隐帝刘承佑这些末代君王丢江山都是冯道不尽职守，那岂不是要周恩来代毛泽东为“文革”负责？ 

与史官们大义凛然的苛责不同，与冯道同一时代的人，多赞誉他的品行修养和从政才能。为政之才，不必多论，即以德操言，冯道“为人能自刻苦为俭约”，行军时与士卒同吃同住，领俸禄便与随从和仆人共享；同僚抢了个民女送给他，要他纳以为妾，他却把民女送还其家长；大军俘获了敌国的女眷，他把她们保护在尼姑蓭中；居丧时不仅亲事稼穑，倾家赈灾，而且悄悄替人家耕种荒地，还不受谢——这些是说私德。在仕途中，他第一次坐牢就是因直谏刘守光不要称帝而获罪，临死前又因力阻周世宗劳师远征而遭嫌，可见其为官并非如范文澜所说的“观望形势，计算利害，谋而后动，丝毫不差。”在长达30余年的官宦生涯中，除了对矜骄的安重海不予提醒听其惹祸身亡、替造反的郭威诱骗后汉王族刘贇，并无其他恶行，多的是劝君勤政、讽君悯农、谏君勿行轻躁的“直臣”所为；而且自担任宰相后，提拔重用的多是“孤寒士子、抱才业、素知识者”，对那些品行不正、办事浮躁的世家显贵则多有抑制——这些事例，史实铭在，范文澜却说人家“舍弃败弱，奉还胜强，按照时机来做，不过早也不过迟，被舍弃者来不及怨恨，被奉还者正适合需要，他就这样避免危害，长享富贵”，显失公平。司马光在“通鉴”中就说冯道：“人莫测其喜愠，滑稽多智，浮沉取容……依违两可，无所操决。——一个“马克思义史学权威”，一个恪守礼教的封建权臣，持论如此一致，不禁令人慨叹：千载倏忽，一脉相承！但年复一年、代复一代的“唱高调”，效果又如何呢？ 老子说：“大道废，有仁义；智慧生，有大伪；六亲不和，有孝慈，国家昏乱，有忠臣。”——这样的吊诡，就是实践的回答。


道义是社会生活的必须，否则，“人之所以异于禽兽者几希”。但道义绝不能靠说教来建立，这也是人类文明的常识。罗素就很实事求是，他说：“延绵了许多世代的动荡不宁，尽管能够容许少数人有着极高度的圣洁，但它确乎是敌视体面的公民的平凡的日常德行的。”也就是说：如果世风浇薄，应该从社会动荡中去找原因。而在儒家文化和皇权专制的通力合作之下，中土强调的是“人而不仁何以为人”，宣称“饿死事小，失节事大”，连《增广贤文》这类总结人情世故的东西都被视为洪水猛兽，看似言说崇高以明大义，实则蒙蔽民智以驯羔羊，是史官文化及其驯导的“集体无意识”的一大特色，渊源国粹，至今依然：小说家捅了一句“逃避崇高”，顿成千夫所指；经济学家说了句“为富人说话，为穷人办事”，被揪着前半句话骂得狗血淋头；中学老师对学生说：“只有升学才有希望升官发财娶美女”，马上就饭碗不保；从多如牛毛的历史事实中概括一些“潜规则”，就成了“歪曲历史、误导大众”——“精神文明”在这样地建设着，谁还敢来挑明皇帝穿没穿衣裳呢？当此之际，有人来出《荣枯鉴》，把史官文化筛子下的这条漏网之鱼放归生活，真是恰逢其时。
