守弱学

* 守弱学

世之强弱，天之常焉。强者为尊，不敬则殃。生之大道，乃自知也。

君子不惧死，而畏无礼。小人可欺天，而避实祸。非敬，爱己矣。智不代力，贤者不显其智。弱须待时，明者毋掩其弱。奉强损之，以其自乱也示弱愚之，以其自谬焉。

人不知者多矣。知之幸也，不知未咎。智以取胜，智不及则乖。愚以愚胜，愚有余则逮。智或难为，愚则克之，得无人者皆愚乎？上不忌愚，忌异志也。下不容诈，容有诚也。上明而下愚，危亦安。下聪而上昏，运必近。言智者莫畏，畏言愚也。贫无所依，不争惟大。困有心贼，抑之无恙。

不恶窘者，知天也。惰以致贫，羞也。廉以不富，荣也。蹇以无货，嗟也。

贵生败儿，贱出公卿。达无直友，难存管鲍。勿失仁者终富，天酬焉。莫道苦者终盛，人敬矣。

智尊者未必强，名实弗契也。霸者存其弱，胜败无常焉。弱不称尊，称必害。强勿逾礼，逾则寇。

不罪于下，祸寡也。目无贵贱，君子也。心系名利，小人也。君子尊而泽人，小人贵而害众。

至善无迹，然惠存也。至尊无威，然心慑耳。智人卑莫僭，羸马勿弛。草木同衰，咸存其荣君不正臣焉。臣谲，君之过也。上无私下谠，上之功也。

功过由人，尊卑守序。卑不弄权，轻焉。

宠不树敌，绝焉。陋不论道，暴焉。堪亲者非贵，远之不辱也。毋失者乃节，恃之必成矣。天非尽善，人无尽美。不理之璞，其真乃存。

求人休言吾能。悦上故彰己丑。治下不夺其功。君子示其短，不示其长。小人用其智，不用其拙。不测之人，高士也。内不避害，害止于内焉。外不就祸，祸拒于外哉。

至辱非辱，乃自害也。至忍非忍，乃自谅也。君子不怨小人，怨天也。小人不畏君子，畏罚也。君子小人，辱之可鉴焉。强而无仁，天辱之，弱而不振，人辱之。辱不灭人，灭于纵怒。大辱加于智者，寡焉。大难止于忍者，息焉。

天威贵德，非罚也。人望贵量，非显也。恕人恕己，愈蹙愈为君子可恕，其心善焉。小人可恕，其情殆焉。不恕者惟事也。富而怜贫，莫损其富。贫而助人，堪脱其贫。人不恕吾，非人过也。吾不恕人，乃吾罪矣。

名弱者，实大用也。致胜者，未必优也。弱而人怜。怜则助。劣而人恕，恕则幸。庸而人纳，纳则遇。以贱为耻，其人反复强调奋。一绌为憾，其人乃进。无依者自强，势所迫焉。贤以义胜，义不容恶也。忠以诚归，诚不输奸也。

* 守弱学全译

人世间的强弱之分,是天道中很正常的事。强者尊贵,不敬重它就会招来祸秧。生存的第一准则，是要有自知之明。君子不恐惧死亡，而害怕失去礼节。小人可以欺瞒上天，却躲避了实际的灾祸。并不是真正地敬重强者，而是爱护自己。智慧不能代替实力，贤明的人不会显露他的智慧。弱者需要等待时机，明智的人不会遮蔽他的弱小。尊奉强者可以损害他，用这个方法能促其自我变乱。显现弱小可以愚弄强者，用这个方法能使其自生错误。

人们不懂的事情太多了。懂得的事情多是好事，不懂也未必是什么坏事。智者用其智慧作为取胜之道，智计一旦失败就会事与愿违。愚人用其愚笨作为取胜的办法，愚笨十足就能达到目的。智计有时难以做到的事，愚笨的办法却可以解决它，这恐怕是人们都是愚人的缘故吧？当权者不忌惮愚人，而忌惮不忠的人。地位低下的人不容奸诈之人，而容纳诚信之人。上司精明下属愚笨，虽然危险但可以平安脱困。下属聪明而上司昏庸，好运一定会完结。说自己聪明的人不要去怕他，要留心自己说自己愚笨的人。

贫穷没有依靠，不争强好胜是最重要的。困境催生邪念，遏制它才没有祸患。不憎恨窘迫之境，即是通晓自然社会了。因为懒惰而导致贫穷，是值得羞愧的；因为恪守清廉原则而不富足，是荣耀的；因为命运坎坷而穷困潦倒，是令人叹息的。富贵之家，多有不屑子孙，贫寒之家常出高官显贵。得时没有正直的朋友，落难时却有管鲍之交。不失去仁爱终究会富有，这来自于上天的酬报。不诉说苦楚的人终究会兴盛，这源自于人们的敬爱。

地位高的人未必是强者，名声和实际不是相契合的。称霸的人也有他的弱点，胜败没有固定的规律。弱者不能自称尊贵，自称尊贵一定会受到伤害。强者不能超越礼法，超越礼法就是贼寇了。对身份低微的人不轻易谴责，祸患就会减少了。眼里没有贵贱之分，是君子的行为；心中只有名利二字，是小人的行径；君子身处高位会造福世人，小人有权有势就会危害百姓。最大的善行是没有痕迹的，但它的恩惠却是实实在在的；最高贵的人没有威仪，但他能让人心悦诚服。

地位低的人不要冒用地位高的人的名号行事，瘦弱的马不要拼命奔跑。草木同时衰败，它们都有茂盛的时候。君主不公正致使臣子欺诈他，这是君主的过错；上司没有私心才能使下属对他直言，这是上司的功德。功过是由人来决定的，尊卑是靠秩序来维护的。卑微的人不要玩弄权力，因为人们轻视他；受宠信的人不要树立强敌，因为这是一条绝路；浅陋的人不要谈论大道理，因为这会暴露自己的无知。可以亲近的人不是达官贵人，远离他们能免遭羞辱；不能失去的是气节，依靠他一定会有所成就。

上天不是最善良的，人没有最完美的；没有加工过的玉石，它的本性才会存在。求助他人不要说自己很有才能；使上司高兴要故意显示自己的丑陋；管理下属不能夺取他们的功劳。君子显现他的短处，不显现他的长处；小人使用他的智慧，不使用他的笨拙。深不可测的人才是真正的高人。对内不回避害处，害处就会在内部得到解决；对外不接近祸乱，祸乱就会被阻挡在外面。

最大的耻辱不是受人侮辱，而是自我伤害；最大的忍让不是容忍他人，而是原谅自己。君子不怨恨小人，怨恨上天的不公；小人不害怕君子，害怕人们的惩罚。一个人是君子还是小人，羞辱他就可以鉴别出来。强者没有仁爱，上天会侮辱他；弱者不能振作，人们会侮辱他。侮辱不能毁灭人，毁灭人的是放纵和愤怒。有智慧的人常常要忍受大的侮辱，因为能理解他们的人很少；忍受屈辱的人往往能躲过大的灾难，因为他们使对手停止了进攻。

上天的威严以仁德为贵，而不是惩罚；人的声望以器量为贵，而不是声名显赫。宽恕他人就是宽恕自己，形势越是困难越是要这样做。君子可以宽恕，因为他们的心地善良；小人可以宽恕，因为他们的处境危险。不能宽恕的只是具体的事情。富人怜惜穷人，不会损害他们的富有；穷人帮助他人，可以使他摆脱贫穷。他人不宽恕自己，不是他人的过错。自己不宽恕他人，则是自己的罪过。

被人称为弱处的东西，实际上是大有用处的。能导致胜利的东西未必是人们所说的优势。弱者令人同情，同情就是强大的动力；处于劣势的人，人们会宽恕他，宽恕就是难得的幸运；平庸者人们会接纳他，接纳他就是难逢的机遇。把地位低下视为耻辱，人们才能奋发有为。把自己的不足视为遗憾，人们才能不断进取。没有依靠的人会自我图强，这是形势逼迫的结果。贤德的人凭着正义取胜，正义不会宽容邪恶；忠贞的人凭着真诚令人归附，真诚不会输给奸诈。

* 译文

** 卷一 敬强篇
人世间的强弱之分，是天道中很正常的事 
生存的第一准则，是要有自知之明 
掩饰弱者身份的人，便会永远是弱者 
小人可以欺瞒上天，却躲避实际的灾祸 
一个真正有智慧的弱者，总是宠辱不惊 
由弱致强是一个漫长的过程，等待是必须的 

** 卷二 保愚篇
聪不外露愚宜外显 
愚以愚胜，是愚人成功的途径 
智计难以做到的事，愚笨却可以解决它 
虚心的人，才能领悟世事的真谛 
说自己聪明的人不要怕他，要怕说自己愚笨的人 
上位者不忌惮愚人，却忌惮聪明人 

** 卷三 安贫篇
困境催生邪念，遏止它才没有祸患 
穷不叫苦，富不贪恋，便离识破天道不远了 
贵生败儿，*出公卿 
上天不会亏待有仁心的人，要对此坚信不疑 
一肚子苦水的人，赢得不了别人的敬重 
懒惰是贫困的第一成因 

** 卷四 抑尊篇
显现弱小可以愚弄强者 
尊奉强者可以损害他，用这个方法能促其自我变乱 
抓住强者弱点的弱者同样能取得胜利 
弱者自称尊贵，伤害便不远了 
君子尊而泽人，小人贵而害众 
无休止的恭维和赞颂，是腐蚀强者的利器 

** 卷五 守卑篇
人卑莫僭，羸马勿驰 
草木同时衰败，他们都有茂盛的时候 
只要气节不失，便不是最贫*者 
如果想做一个可笑的浅陋者，那就夸夸其谈吧 
达官贵人不是可以亲近的人，离开他们可远离羞辱 
气节是弱者的青山 

** 卷六 示缺篇
缺陷是世界的本相，过度追求完美不智 
死要面子不智，不说真话不通，向人求助且忌趾高气扬 
使上司高兴要故意显示自己的丑陋 
以本色面目出现，缺陷便会被人容忍 
自损声名，能解除上司的戒心，得大于失 
有见识的人是不求独美的 

** 卷七 忍辱篇
小人不怕君子，却怕惩罚 
弱者不能振作，人们会侮辱他 
羞辱虽伤人，愤怒却致命 
大智者常有大辱，忍大辱者则有大成 
松懈对手意志，减轻将至的打击力度 

** 卷八 恕人篇
声望以器量为贵，而不是名声显赫 
宽恕他人就是宽恕自己 
仁恕之道不仅能感染人，更能改变人 
扶助处于困境的人，是智者的行为 
过于求全责备，受害的是自身 
富而泽贫，无损其富 

** 卷九 弱胜篇
强大处下，柔弱处上 
坚强者死之徙，柔弱者生之徒 
要善用其“弱”，“弱”的威力便显现了 
弱者令人同情，同情就是强大的助力 
进取心是上天对下层人士的无形“褒奖” 
诚心对人，更应该成为弱者的座右铭 

* 作者简介

杜预，字元凯，西晋名臣，在西晋统一大业中，居功至伟，深得晋武帝宠信。因其才学广博、触类旁通，被誉为“杜武库”。杜预“身不跨马，射不穿札”，以智谋统军，堪称儒将之典范。这部由今人集录而成的杜预谋略专论“守弱”，而“守弱”恰是杜预平生的“图存”“图强”之道。
